import { useEffect, useRef, useState } from "react";
import { Link } from "react-router-dom";

import api from "@/services/api";

import SEO from "@/components/common/SEO";
import ToolLayout from "@/components/tool-layout/ToolLayout";
import ToolHeader from "@/components/tool-layout/ToolHeader";
import ToolForm from "@/components/tool-layout/ToolForm";

function SectionHeading({ children, color = "blue" }) {
  const colors = {
    red: "border-red-500 bg-red-500/5 text-red-400",
    yellow: "border-yellow-400 bg-yellow-400/5 text-yellow-300",
    green: "border-green-500 bg-green-500/5 text-green-400",
    blue: "border-blue-500 bg-blue-500/5 text-blue-400",
  };

  return (
    <h2
      className={`border-l-4 rounded-r-xl px-5 py-3 text-2xl font-bold tracking-tight sm:text-3xl ${colors[color]}`}
    >
      {children}
    </h2>
  );
}

function DescriptionExtractor({ query = "" }) {
  const [loading, setLoading] = useState(false);
  const [description, setDescription] = useState("");
  const [lastFormData, setLastFormData] = useState(null);
  const [videoInfo, setVideoInfo] = useState(null);
  const [noDescriptionFound, setNoDescriptionFound] = useState(false);

  const autoGeneratedQuery = useRef("");

  /* =========================================================
     EXTRACT DESCRIPTION
     ========================================================= */

  const handleGenerate = async (formData) => {
    try {
      setLoading(true);
      setLastFormData(formData);
      setDescription("");
      setVideoInfo(null);
      setNoDescriptionFound(false);

      const url = String(formData?.topic || "").trim();

      if (!url) {
        alert("Please enter a YouTube video URL.");
        return;
      }

      const response = await api.get("/youtube/description", {
        params: {
          url,
        },
      });

      if (response.data.success) {
        const data = response.data.data || {};
        const extractedDescription = String(
          data.description || ""
        ).trim();

        setVideoInfo({
          videoId: data.videoId || "",
          videoUrl: data.videoUrl || url,
          title: data.title || "",
          channelTitle: data.channelTitle || "",
          channelId: data.channelId || "",
        });

        setDescription(extractedDescription);

        if (!extractedDescription) {
          setNoDescriptionFound(true);
        }
      } else {
        setDescription("");
        alert(
          response.data.message ||
            "Failed to extract YouTube description"
        );
      }
    } catch (error) {
      console.error("DESCRIPTION EXTRACTOR ERROR:", error);
      console.error("RESPONSE:", error.response);
      console.error("REQUEST:", error.request);

      alert(
        error.response?.data?.message ||
          error.message ||
          "Failed to extract YouTube description"
      );

      setDescription("");
      setVideoInfo(null);
      setNoDescriptionFound(false);
    } finally {
      setLoading(false);
    }
  };

  /* =========================================================
     HERO SEARCH -> AUTO EXTRACT
     ========================================================= */

  useEffect(() => {
    const value = query.trim();

    if (!value) return;
    if (autoGeneratedQuery.current === value) return;

    autoGeneratedQuery.current = value;

    handleGenerate({
      topic: value,
    });
  }, [query]);

  /* =========================================================
     COPY
     ========================================================= */

  const copyDescription = async () => {
    if (!description) return;

    try {
      await navigator.clipboard.writeText(description);
      alert("Description copied!");
    } catch (error) {
      console.error("COPY ERROR:", error);
    }
  };

  /* =========================================================
     FAQ
     ========================================================= */

  const faqs = [
    {
      question: "What is a YouTube Description Extractor?",
      answer:
        "A YouTube Description Extractor retrieves the available description associated with a YouTube video.",
    },
    {
      question: "How do I extract a YouTube video description?",
      answer:
        "Paste a valid YouTube video URL into TubeKit and click Extract YouTube Description.",
    },
    {
      question: "Which YouTube URL formats are supported?",
      answer:
        "TubeKit supports standard watch URLs, youtu.be URLs, Shorts URLs, embed URLs, live URLs, mobile URLs, www URLs, and URLs containing additional query parameters.",
    },
    {
      question: "Can I extract descriptions from YouTube Shorts?",
      answer:
        "Yes. A valid YouTube Shorts URL can be used to identify the video and retrieve its available description.",
    },
    {
      question: "Why does a video sometimes show no description?",
      answer:
        "Some YouTube videos may have an empty description. In that case TubeKit clearly shows that no description was found instead of treating the tool as broken.",
    },
    {
      question: "Can I copy the extracted description?",
      answer:
        "Yes. Use the Copy Description button to copy the complete extracted description.",
    },
    {
      question: "Is the YouTube Description Extractor free?",
      answer:
        "TubeKit provides this YouTube Description Extractor as a free creator tool.",
    },
    {
      question: "Can extracted descriptions be used for research?",
      answer:
        "Yes. Extracted descriptions can be used as research references when studying content structure, keywords, links, and calls to action.",
    },
  ];

  const breadcrumbs = [
    {
      name: "Home",
      path: "/",
    },
    {
      name: "YouTube Description Extractor",
      path: "/tools/description-extractor",
    },
  ];

  return (
    <>
      <SEO
        title="YouTube Description Extractor - Extract Video Descriptions | TubeKit"
        description="Extract available descriptions from YouTube videos with TubeKit's free YouTube Description Extractor. Supports videos, Shorts, shortened URLs, embed URLs, live URLs and more."
        keywords="YouTube description extractor, extract YouTube description, YouTube video description extractor, YouTube description finder, find YouTube description, extract video description, YouTube Shorts description extractor"
        canonical="/tools/description-extractor"
        breadcrumbs={breadcrumbs}
        faqs={faqs}
      />

      <ToolLayout>
        <ToolHeader
          title="YouTube Description Extractor"
          description="Extract available descriptions from YouTube videos quickly using a simple video URL."
        />

        <ToolForm
          onGenerate={handleGenerate}
          loading={loading}
          config={{
            buttonText: "Extract YouTube Description",
            topicLabel: "YouTube Video URL",
            topicPlaceholder:
              "Paste YouTube video URL (watch, youtu.be, Shorts, embed, live)...",
            initialTopic: query,
          }}
        />

        {/* ===================================================
            VIDEO INFO
            =================================================== */}

        {!loading && videoInfo && (
          <div className="mt-8 overflow-hidden rounded-2xl border border-blue-500/20 bg-slate-900/80">
            <div className="border-b border-slate-800 px-5 py-4">
              <p className="text-sm font-medium text-blue-400">
                Video Analyzed
              </p>
            </div>

            <div className="p-5">
              <div className="flex flex-col gap-4 sm:flex-row sm:items-center">
                <div className="min-w-0 flex-1">
                  <h2 className="text-xl font-bold text-white">
                    {videoInfo.title || "YouTube Video"}
                  </h2>

                  {videoInfo.channelTitle && (
                    <p className="mt-2 text-sm text-slate-400">
                      Channel: {videoInfo.channelTitle}
                    </p>
                  )}
                </div>

                {videoInfo.videoUrl && (
                  <a
                    href={videoInfo.videoUrl}
                    target="_blank"
                    rel="noreferrer"
                    className="shrink-0 rounded-xl border border-red-500/30 bg-red-500/5 px-4 py-2 text-sm font-semibold text-red-400 transition hover:border-red-400 hover:bg-red-500/10"
                  >
                    Open Video
                  </a>
                )}
              </div>
            </div>
          </div>
        )}

        {/* ===================================================
            NO DESCRIPTION FOUND
            =================================================== */}

        {!loading && noDescriptionFound && (
          <div className="mt-8 rounded-2xl border border-yellow-400/20 bg-yellow-400/5 p-6">
            <div className="flex items-start gap-4">
              <div className="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl bg-yellow-400/10 text-xl text-yellow-300">
                !
              </div>

              <div>
                <h2 className="text-2xl font-bold text-white">
                  No YouTube Description Found
                </h2>

                <p className="mt-2 leading-7 text-slate-400">
                  This video was found successfully, but no available
                  YouTube description was returned for its metadata.
                </p>

                <p className="mt-2 text-sm leading-6 text-slate-500">
                  Try another public YouTube video to check whether
                  a description is available.
                </p>
              </div>
            </div>
          </div>
        )}

        {/* ===================================================
            DESCRIPTION OUTPUT
            =================================================== */}

        {!loading && !noDescriptionFound && description && (
          <div className="mt-8 overflow-hidden rounded-2xl border border-slate-800 bg-black">
            <div className="flex flex-col gap-4 border-b border-slate-800 px-5 py-4 sm:flex-row sm:items-center sm:justify-between">
              <div>
                <p className="text-sm font-medium text-blue-400">
                  Extracted Description
                </p>
                <p className="mt-1 text-xs text-slate-500">
                  Available YouTube video description
                </p>
              </div>

              <button
                type="button"
                onClick={copyDescription}
                className="rounded-xl border border-red-500/30 bg-red-500/5 px-4 py-2 text-sm font-semibold text-red-400 transition hover:border-red-400 hover:bg-red-500/10"
              >
                Copy Description
              </button>
            </div>

            <div className="whitespace-pre-wrap break-words p-5 text-sm leading-7 text-slate-300 sm:p-7">
              {description}
            </div>
          </div>
        )}

        {/* ===================================================
            SEO CONTENT
            =================================================== */}

        <section className="mt-16 space-y-12">
          <div>
            <SectionHeading color="red">
              Free YouTube Description Extractor
            </SectionHeading>

            <p className="mt-5 leading-8 text-slate-300">
              TubeKit's free YouTube Description Extractor helps
              creators retrieve the available description associated
              with a YouTube video. Enter a YouTube video URL and the
              available description is displayed in an easy-to-read
              format.
            </p>

            <p className="mt-4 leading-8 text-slate-300">
              YouTube descriptions can contain useful information
              such as keywords, links, calls to action, timestamps,
              social profiles, and additional video context.
            </p>
          </div>

          <div>
            <SectionHeading color="yellow">
              How to Use the YouTube Description Extractor
            </SectionHeading>

            <p className="mt-5 leading-8 text-slate-300">
              Extracting an available YouTube description takes only
              a few steps:
            </p>

            <ol className="mt-5 list-decimal space-y-3 pl-6 leading-8 text-slate-300">
              <li>Copy the URL of the YouTube video.</li>
              <li>Paste the URL into the extractor.</li>
              <li>
                Click the{" "}
                <strong className="text-white">
                  Extract YouTube Description
                </strong>{" "}
                button.
              </li>
              <li>Review the available description.</li>
              <li>Use Copy Description to copy the text.</li>
            </ol>
          </div>

          <div>
            <SectionHeading color="green">
              Supported YouTube URL Formats
            </SectionHeading>

            <p className="mt-5 leading-8 text-slate-300">
              TubeKit supports common YouTube URL formats, including:
            </p>

            <div className="mt-6 grid gap-4 sm:grid-cols-2">
              <div className="rounded-xl border border-red-500/20 bg-red-500/5 p-5">
                <p className="font-semibold text-red-400">
                  Standard Watch URL
                </p>
                <p className="mt-2 break-all text-sm text-slate-300">
                  https://www.youtube.com/watch?v=VIDEO_ID
                </p>
              </div>

              <div className="rounded-xl border border-yellow-400/20 bg-yellow-400/5 p-5">
                <p className="font-semibold text-yellow-300">
                  Short URL
                </p>
                <p className="mt-2 break-all text-sm text-slate-300">
                  https://youtu.be/VIDEO_ID
                </p>
              </div>

              <div className="rounded-xl border border-green-500/20 bg-green-500/5 p-5">
                <p className="font-semibold text-green-400">
                  Shorts URL
                </p>
                <p className="mt-2 break-all text-sm text-slate-300">
                  https://www.youtube.com/shorts/VIDEO_ID
                </p>
              </div>

              <div className="rounded-xl border border-blue-500/20 bg-blue-500/5 p-5">
                <p className="font-semibold text-blue-400">
                  Embed URL
                </p>
                <p className="mt-2 break-all text-sm text-slate-300">
                  https://www.youtube.com/embed/VIDEO_ID
                </p>
              </div>

              <div className="rounded-xl border border-red-500/20 bg-red-500/5 p-5">
                <p className="font-semibold text-red-400">
                  Live URL
                </p>
                <p className="mt-2 break-all text-sm text-slate-300">
                  https://www.youtube.com/live/VIDEO_ID
                </p>
              </div>

              <div className="rounded-xl border border-yellow-400/20 bg-yellow-400/5 p-5">
                <p className="font-semibold text-yellow-300">
                  Mobile URL
                </p>
                <p className="mt-2 break-all text-sm text-slate-300">
                  https://m.youtube.com/watch?v=VIDEO_ID
                </p>
              </div>

              <div className="rounded-xl border border-green-500/20 bg-green-500/5 p-5">
                <p className="font-semibold text-green-400">
                  WWW URL
                </p>
                <p className="mt-2 break-all text-sm text-slate-300">
                  https://www.youtube.com/watch?v=VIDEO_ID
                </p>
              </div>

              <div className="rounded-xl border border-blue-500/20 bg-blue-500/5 p-5">
                <p className="font-semibold text-blue-400">
                  URL With Extra Parameters
                </p>
                <p className="mt-2 break-all text-sm text-slate-300">
                  https://www.youtube.com/watch?v=VIDEO_ID&feature=share
                </p>
              </div>
            </div>
          </div>

          <div>
            <SectionHeading color="blue">
              What Is a YouTube Description Extractor?
            </SectionHeading>

            <p className="mt-5 leading-8 text-slate-300">
              A YouTube Description Extractor is a tool that retrieves
              the available description associated with a YouTube
              video. A description can provide context about the
              video and may include links, keywords, timestamps, and
              calls to action.
            </p>

            <p className="mt-4 leading-8 text-slate-300">
              Creators can use description extraction as part of
              their content research, competitor review, and YouTube
              optimization workflow.
            </p>
          </div>

          <div>
            <SectionHeading color="red">
              Why Use a YouTube Description Extractor?
            </SectionHeading>

            <ul className="mt-5 list-disc space-y-3 pl-6 leading-8 text-slate-300">
              <li>Quickly inspect an available video description.</li>
              <li>
                Research description structures used by similar
                content.
              </li>
              <li>
                Review keywords, links, timestamps, and calls to
                action.
              </li>
              <li>Copy the complete description quickly.</li>
              <li>
                Analyze videos using multiple YouTube URL formats.
              </li>
            </ul>
          </div>

          <div>
            <SectionHeading color="yellow">
              How to Use Extracted Descriptions for YouTube Research
            </SectionHeading>

            <p className="mt-5 leading-8 text-slate-300">
              Extracted descriptions can be used as one source of
              information during YouTube content research. Compare
              relevant videos to understand how creators organize
              context, links, keywords, timestamps, and calls to
              action.
            </p>

            <p className="mt-4 leading-8 text-slate-300">
              Do not copy another creator's description as your own.
              Use extracted information as a research reference and
              create original content that accurately represents your
              video.
            </p>
          </div>

          <div>
            <SectionHeading color="green">
              TubeKit YouTube Description Extractor Features
            </SectionHeading>

            <ul className="mt-6 grid gap-3 text-slate-300 sm:grid-cols-2">
              <li className="rounded-lg border border-red-500/20 bg-red-500/5 p-3">
                [OK] Extract available YouTube descriptions
              </li>

              <li className="rounded-lg border border-yellow-400/20 bg-yellow-400/5 p-3">
                [OK] Supports standard YouTube URLs
              </li>

              <li className="rounded-lg border border-green-500/20 bg-green-500/5 p-3">
                [OK] Supports youtu.be URLs
              </li>

              <li className="rounded-lg border border-blue-500/20 bg-blue-500/5 p-3">
                [OK] Supports YouTube Shorts URLs
              </li>

              <li className="rounded-lg border border-red-500/20 bg-red-500/5 p-3">
                [OK] Supports embed URLs
              </li>

              <li className="rounded-lg border border-yellow-400/20 bg-yellow-400/5 p-3">
                [OK] Supports live URLs
              </li>

              <li className="rounded-lg border border-green-500/20 bg-green-500/5 p-3">
                [OK] Copy extracted description
              </li>

              <li className="rounded-lg border border-blue-500/20 bg-blue-500/5 p-3">
                [OK] Video information preview
              </li>

              <li className="rounded-lg border border-red-500/20 bg-red-500/5 p-3">
                [OK] Regenerate or retry extraction
              </li>

              <li className="rounded-lg border border-yellow-400/20 bg-yellow-400/5 p-3">
                [OK] Mobile-friendly interface
              </li>

              <li className="rounded-lg border border-green-500/20 bg-green-500/5 p-3">
                [OK] Simple creator workflow
              </li>

              <li className="rounded-lg border border-blue-500/20 bg-blue-500/5 p-3">
                [OK] Free to use
              </li>
            </ul>
          </div>

          <div>
            <SectionHeading color="blue">
              Important Notes About YouTube Descriptions
            </SectionHeading>

            <p className="mt-5 leading-8 text-slate-300">
              Not every YouTube video will necessarily return a
              description. Availability depends on the video's
              available metadata and the data returned by the YouTube
              service.
            </p>

            <p className="mt-4 leading-8 text-slate-300">
              If a video is private, unavailable, deleted, invalid,
              or cannot be accessed, the extractor may not return a
              description.
            </p>
          </div>

          <div>
            <SectionHeading color="yellow">
              More Free YouTube Tools
            </SectionHeading>

            <p className="mt-5 leading-8 text-slate-300">
              Use TubeKit's other creator tools for titles, tags,
              keywords, hashtags, thumbnails, and scripts.
            </p>

            <div className="mt-6 grid gap-4 sm:grid-cols-2">
              <Link
                to="/tools/title-generator"
                className="rounded-xl border border-red-500/20 bg-red-500/5 p-5 transition hover:border-red-400 hover:bg-red-500/10"
              >
                <span className="font-semibold text-red-400">
                  YouTube Title Generator
                </span>
                <p className="mt-2 text-sm text-slate-400">
                  Generate YouTube title ideas.
                </p>
              </Link>

              <Link
                to="/tools/tags-generator"
                className="rounded-xl border border-green-500/20 bg-green-500/5 p-5 transition hover:border-green-400 hover:bg-green-500/10"
              >
                <span className="font-semibold text-green-400">
                  YouTube Tags Generator
                </span>
                <p className="mt-2 text-sm text-slate-400">
                  Generate tag ideas for your own content.
                </p>
              </Link>

              <Link
                to="/tools/tag-extractor"
                className="rounded-xl border border-blue-500/20 bg-blue-500/5 p-5 transition hover:border-blue-400 hover:bg-blue-500/10"
              >
                <span className="font-semibold text-blue-400">
                  YouTube Tag Extractor
                </span>
                <p className="mt-2 text-sm text-slate-400">
                  Extract available video tags.
                </p>
              </Link>

              <Link
                to="/tools/hashtag-generator"
                className="rounded-xl border border-yellow-400/20 bg-yellow-400/5 p-5 transition hover:border-yellow-300 hover:bg-yellow-400/10"
              >
                <span className="font-semibold text-yellow-300">
                  YouTube Hashtag Generator
                </span>
                <p className="mt-2 text-sm text-slate-400">
                  Generate relevant YouTube hashtags.
                </p>
              </Link>

              <Link
                to="/tools/keyword-generator"
                className="rounded-xl border border-red-500/20 bg-red-500/5 p-5 transition hover:border-red-400 hover:bg-red-500/10"
              >
                <span className="font-semibold text-red-400">
                  YouTube Keyword Generator
                </span>
                <p className="mt-2 text-sm text-slate-400">
                  Find keyword ideas for YouTube.
                </p>
              </Link>

              <Link
                to="/tools/thumbnail-generator"
                className="rounded-xl border border-green-500/20 bg-green-500/5 p-5 transition hover:border-green-400 hover:bg-green-500/10"
              >
                <span className="font-semibold text-green-400">
                  YouTube Thumbnail Generator
                </span>
                <p className="mt-2 text-sm text-slate-400">
                  Generate thumbnail concepts.
                </p>
              </Link>
            </div>
          </div>

          <div>
            <SectionHeading color="green">
              Learn More About YouTube SEO
            </SectionHeading>

            <div className="mt-6 grid gap-4 sm:grid-cols-2">
              <Link
                to="/blog/best-youtube-seo-tools-for-creators"
                className="rounded-xl border border-blue-500/20 bg-blue-500/5 p-5 transition hover:border-blue-400 hover:bg-blue-500/10"
              >
                <span className="font-semibold text-blue-400">
                  Best YouTube SEO Tools for Creators
                </span>
                <p className="mt-2 text-sm text-slate-400">
                  Explore useful YouTube SEO tools and workflows.
                </p>
              </Link>

              <Link
                to="/blog/how-to-write-youtube-titles-that-get-more-clicks"
                className="rounded-xl border border-green-500/20 bg-green-500/5 p-5 transition hover:border-green-400 hover:bg-green-500/10"
              >
                <span className="font-semibold text-green-400">
                  How to Write YouTube Titles That Get More Clicks
                </span>
                <p className="mt-2 text-sm text-slate-400">
                  Learn practical YouTube title techniques.
                </p>
              </Link>
            </div>
          </div>

          <div>
            <SectionHeading color="blue">
              Frequently Asked Questions
            </SectionHeading>

            <div className="mt-6 space-y-4">
              {faqs.map((faq, index) => {
                const colors = [
                  "border-red-500/20 bg-red-500/5",
                  "border-yellow-400/20 bg-yellow-400/5",
                  "border-green-500/20 bg-green-500/5",
                  "border-blue-500/20 bg-blue-500/5",
                ];

                return (
                  <div
                    key={faq.question}
                    className={`rounded-xl border p-5 ${
                      colors[index % 4]
                    }`}
                  >
                    <h3 className="text-lg font-semibold text-white">
                      {faq.question}
                    </h3>

                    <p className="mt-2 leading-7 text-slate-400">
                      {faq.answer}
                    </p>
                  </div>
                );
              })}
            </div>
          </div>
        </section>
      </ToolLayout>
    </>
  );
}

export default DescriptionExtractor;