import { useEffect, useRef, useState } from "react";
import { Link } from "react-router-dom";

import api from "@/services/api";

import SEO from "@/components/common/SEO";
import ToolLayout from "@/components/tool-layout/ToolLayout";
import ToolHeader from "@/components/tool-layout/ToolHeader";
import ToolForm from "@/components/tool-layout/ToolForm";
import ToolOutput from "@/components/tool-layout/ToolOutput";

function SectionHeading({ children, color = "blue" }) {
  const colors = {
    red: "border-red-500 bg-red-500/5 text-red-400",
    yellow: "border-yellow-400 bg-yellow-400/5 text-yellow-300",
    green: "border-green-500 bg-green-500/5 text-green-400",
    blue: "border-blue-500 bg-blue-500/5 text-blue-400",
  };

  return (
    <h2
      className={`border-l-4 rounded-r-xl px-5 py-3 text-2xl font-bold tracking-tight sm:text-3xl ${colors[color]}`}
    >
      {children}
    </h2>
  );
}

function HashtagExtractor({ query = "" }) {
  const [loading, setLoading] = useState(false);
  const [results, setResults] = useState([]);
  const [lastFormData, setLastFormData] = useState(null);
  const [videoInfo, setVideoInfo] = useState(null);
  const [noHashtagsFound, setNoHashtagsFound] = useState(false);

  const autoGeneratedQuery = useRef("");

  /* =========================================================
     EXTRACT HASHTAGS
     ========================================================= */

  const handleGenerate = async (formData) => {
    try {
      setLoading(true);
      setLastFormData(formData);
      setResults([]);
      setVideoInfo(null);
      setNoHashtagsFound(false);

      const url = String(formData?.topic || "").trim();

      if (!url) {
        alert("Please enter a YouTube video URL.");
        return;
      }

      const response = await api.get("/youtube/hashtags", {
        params: {
          url,
        },
      });

      if (response.data.success) {
        const data = response.data.data || {};

        const hashtags = Array.isArray(data.hashtags)
          ? data.hashtags
              .map((hashtag) => String(hashtag).trim())
              .filter(Boolean)
              .map((hashtag) =>
                hashtag.startsWith("#") ? hashtag : `#${hashtag}`
              )
          : [];

        setVideoInfo({
          videoId: data.videoId || "",
          videoUrl: data.videoUrl || url,
          title: data.title || "",
          channelTitle: data.channelTitle || "",
          channelId: data.channelId || "",
        });

        setResults(hashtags);

        if (hashtags.length === 0) {
          setNoHashtagsFound(true);
        }
      } else {
        setResults([]);
        alert(
          response.data.message ||
            "Failed to extract YouTube hashtags"
        );
      }
    } catch (error) {
      console.error("HASHTAG EXTRACTOR ERROR:", error);
      console.error("RESPONSE:", error.response);
      console.error("REQUEST:", error.request);

      alert(
        error.response?.data?.message ||
          error.message ||
          "Failed to extract YouTube hashtags"
      );

      setResults([]);
      setVideoInfo(null);
      setNoHashtagsFound(false);
    } finally {
      setLoading(false);
    }
  };

  /* =========================================================
     HERO SEARCH -> AUTO EXTRACT
     ========================================================= */

  useEffect(() => {
    const value = query.trim();

    if (!value) return;
    if (autoGeneratedQuery.current === value) return;

    autoGeneratedQuery.current = value;

    handleGenerate({
      topic: value,
    });
  }, [query]);

  /* =========================================================
     COPY
     ========================================================= */

  const copyHashtag = async (text) => {
    try {
      await navigator.clipboard.writeText(text);
      alert("Copied!");
    } catch (error) {
      console.error("COPY ERROR:", error);
    }
  };

  const copyAll = async () => {
    if (!results.length) return;

    try {
      await navigator.clipboard.writeText(
        results.join(", ")
      );
      alert("All hashtags copied!");
    } catch (error) {
      console.error("COPY ALL ERROR:", error);
    }
  };


  /* =========================================================
     FAQ
     ========================================================= */

  const faqs = [
    {
      question: "What is a YouTube Hashtag Extractor?",
      answer:
        "A YouTube Hashtag Extractor retrieves available hashtags associated with a YouTube video.",
    },
    {
      question: "How do I extract hashtags from a YouTube video?",
      answer:
        "Paste a valid YouTube video URL into TubeKit and click Extract YouTube Hashtags.",
    },
    {
      question: "Which YouTube URL formats are supported?",
      answer:
        "TubeKit supports standard watch URLs, youtu.be URLs, Shorts URLs, embed URLs, live URLs, mobile URLs, www URLs, and URLs containing additional query parameters.",
    },
    {
      question: "Can I extract hashtags from YouTube Shorts?",
      answer:
        "Yes. A valid YouTube Shorts URL can be used to identify the video and retrieve available hashtags.",
    },
    {
      question: "Why does a video sometimes show no hashtags?",
      answer:
        "Some YouTube videos may not have hashtags available in their returned metadata. In that case TubeKit clearly shows that no hashtags were found instead of treating the tool as broken.",
    },
    {
      question: "Can I copy all extracted hashtags?",
      answer:
        "Yes. Use Copy All to copy the extracted hashtags as a comma-separated list.",
    },
    {
      question: "Is the YouTube Hashtag Extractor free?",
      answer:
        "TubeKit provides this YouTube Hashtag Extractor as a free creator tool.",
    },
    {
      question: "Can extracted hashtags be used for research?",
      answer:
        "Yes. Extracted hashtags can be used as research references, but hashtags used on your own videos should accurately describe your content.",
    },
  ];

  const breadcrumbs = [
    {
      name: "Home",
      path: "/",
    },
    {
      name: "YouTube Hashtag Extractor",
      path: "/tools/hashtag-extractor",
    },
  ];

  return (
    <>
      <SEO
        title="YouTube Hashtag Extractor - Extract YouTube Hashtags | TubeKit"
        description="Extract available hashtags from any YouTube video with TubeKit's free YouTube Hashtag Extractor. Supports videos, Shorts, shortened URLs, embed URLs, live URLs and more."
        keywords="YouTube hashtag extractor, YouTube hashtags extractor, extract YouTube hashtags, YouTube video hashtag extractor, YouTube hashtag finder, find YouTube hashtags, YouTube SEO hashtags, extract video hashtags, YouTube Shorts hashtags"
        canonical="/tools/hashtag-extractor"
        breadcrumbs={breadcrumbs}
        faqs={faqs}
      />

      <ToolLayout>
        <ToolHeader
          title="YouTube Hashtag Extractor"
          description="Extract available hashtags from YouTube videos quickly using a simple video URL."
        />

        <ToolForm
          onGenerate={handleGenerate}
          loading={loading}
          config={{
            buttonText: "Extract YouTube Hashtags",
            topicLabel: "YouTube Video URL",
            topicPlaceholder:
              "Paste YouTube video URL (watch, youtu.be, Shorts, embed, live)...",
            initialTopic: query,
          }}
        />

        {/* ===================================================
            VIDEO INFO
            =================================================== */}

        {!loading && videoInfo && (
          <div className="mt-8 overflow-hidden rounded-2xl border border-blue-500/20 bg-slate-900/80">
            <div className="border-b border-slate-800 px-5 py-4">
              <p className="text-sm font-medium text-blue-400">
                Video Analyzed
              </p>
            </div>

            <div className="p-5">
              <div className="flex flex-col gap-4 sm:flex-row sm:items-center">
                <div className="min-w-0 flex-1">
                  <h2 className="text-xl font-bold text-white">
                    {videoInfo.title || "YouTube Video"}
                  </h2>

                  {videoInfo.channelTitle && (
                    <p className="mt-2 text-sm text-slate-400">
                      Channel: {videoInfo.channelTitle}
                    </p>
                  )}
                </div>

                {videoInfo.videoUrl && (
                  <a
                    href={videoInfo.videoUrl}
                    target="_blank"
                    rel="noreferrer"
                    className="shrink-0 rounded-xl border border-red-500/30 bg-red-500/5 px-4 py-2 text-sm font-semibold text-red-400 transition hover:border-red-400 hover:bg-red-500/10"
                  >
                    Open Video
                  </a>
                )}
              </div>
            </div>
          </div>
        )}

        {/* ===================================================
            NO HASHTAGS FOUND
            =================================================== */}

        {!loading && noHashtagsFound && (
          <div className="mt-8 rounded-2xl border border-yellow-400/20 bg-yellow-400/5 p-6">
            <div className="flex items-start gap-4">
              <div className="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl bg-yellow-400/10 text-xl text-yellow-300">
                !
              </div>

              <div>
                <h2 className="text-2xl font-bold text-white">
                  No YouTube Hashtags Found
                </h2>

                <p className="mt-2 leading-7 text-slate-400">
                  This video was found successfully, but no available
                  YouTube hashtags were returned for its metadata.
                </p>

                <p className="mt-2 text-sm leading-6 text-slate-500">
                  Try another public YouTube video to check whether
                  hashtags are available.
                </p>
              </div>
            </div>
          </div>
        )}

        {/* ===================================================
            HASHTAG OUTPUT
            =================================================== */}

        {!noHashtagsFound && (
          <ToolOutput
            results={results}
            loading={loading}
            onCopy={copyHashtag}
            onCopyAll={copyAll}
            onRegenerate={() => {
              if (lastFormData) {
                handleGenerate(lastFormData);
              }
            }}
          />
        )}

              What Is a YouTube Hashtag Extractor?
            </SectionHeading>

            <p className="mt-5 leading-8 text-slate-300">
              A YouTube Hashtag Extractor is a tool that retrieves
              available hashtags associated with a YouTube video.
              These hashtags can provide additional context about
              topics associated with the video.
            </p>

            <p className="mt-4 leading-8 text-slate-300">
              Creators can use hashtag extraction as part of their
              content research and YouTube optimization workflow.
            </p>
          </div>

          <div>
            <SectionHeading color="red">
              Why Use a YouTube Hashtag Extractor?
            </SectionHeading>

            <ul className="mt-5 list-disc space-y-3 pl-6 leading-8 text-slate-300">
              <li>Quickly inspect available video hashtags.</li>
              <li>
                Research topics associated with similar content.
              </li>
              <li>
                Collect hashtags for content planning and analysis.
              </li>
              <li>Copy the complete hashtag list quickly.</li>
              <li>
                Analyze videos using multiple URL formats.
              </li>
            </ul>
          </div>
<div>
            <SectionHeading color="yellow">
              How to Use Extracted Hashtags for YouTube Research
            </SectionHeading>

            <p className="mt-5 leading-8 text-slate-300">
              Extracted hashtags can be used as one source of
              information during YouTube content research. Compare
              hashtags across relevant videos to identify recurring
              topics and terminology.
            </p>

            <p className="mt-4 leading-8 text-slate-300">
              Do not automatically copy every extracted hashtag into
              your own video. Use hashtags that genuinely describe
              your content.
            </p>
          </div>

          <div>
            <SectionHeading color="green">
              TubeKit YouTube Hashtag Extractor Features
            </SectionHeading>

            <ul className="mt-6 grid gap-3 text-slate-300 sm:grid-cols-2">
              <li className="rounded-lg border border-red-500/20 bg-red-500/5 p-3">
                [OK] Extract available YouTube hashtags
              </li>

              <li className="rounded-lg border border-yellow-400/20 bg-yellow-400/5 p-3">
                [OK] Supports standard YouTube URLs
              </li>

              <li className="rounded-lg border border-green-500/20 bg-green-500/5 p-3">
                [OK] Supports youtu.be URLs
              </li>

              <li className="rounded-lg border border-blue-500/20 bg-blue-500/5 p-3">
                [OK] Supports YouTube Shorts URLs
              </li>

              <li className="rounded-lg border border-red-500/20 bg-red-500/5 p-3">
                [OK] Supports embed URLs
              </li>

              <li className="rounded-lg border border-yellow-400/20 bg-yellow-400/5 p-3">
                [OK] Supports live URLs
              </li>

              <li className="rounded-lg border border-green-500/20 bg-green-500/5 p-3">
                [OK] Copy individual hashtags
              </li>

              <li className="rounded-lg border border-blue-500/20 bg-blue-500/5 p-3">
                [OK] Copy all extracted hashtags
              </li>

              <li className="rounded-lg border border-red-500/20 bg-red-500/5 p-3">
                [OK] Regenerate or retry extraction
              </li>

              <li className="rounded-lg border border-yellow-400/20 bg-yellow-400/5 p-3">
                [OK] Mobile-friendly interface
              </li>

              <li className="rounded-lg border border-green-500/20 bg-green-500/5 p-3">
                [OK] Simple creator workflow
              </li>

              <li className="rounded-lg border border-blue-500/20 bg-blue-500/5 p-3">
                [OK] Free to use
              </li>
            </ul>
          </div>

          <div>
            <SectionHeading color="blue">
              Important Notes About YouTube Hashtags
            </SectionHeading>

            <p className="mt-5 leading-8 text-slate-300">
              Not every YouTube video will necessarily return a list
              of hashtags. Availability depends on the video's
              available metadata and the data returned by the
              YouTube service.
            </p>

            <p className="mt-4 leading-8 text-slate-300">
              If a video is private, unavailable, deleted, invalid,
              or cannot be accessed, the extractor may not return
              hashtags.
            </p>
          </div>

          <div>
            <SectionHeading color="yellow">
              More Free YouTube Tools
            </SectionHeading>

            <p className="mt-5 leading-8 text-slate-300">
              Use TubeKit's other creator tools for titles,
              descriptions, tags, keywords, thumbnails, and scripts.
            </p>

            <div className="mt-6 grid gap-4 sm:grid-cols-2">
              <Link
                to="/tools/title-generator"
                className="rounded-xl border border-red-500/20 bg-red-500/5 p-5 transition hover:border-red-400 hover:bg-red-500/10"
              >
                <span className="font-semibold text-red-400">
                  YouTube Title Generator
                </span>
                <p className="mt-2 text-sm text-slate-400">
                  Generate YouTube title ideas.
                </p>
              </Link>

              <Link
                to="/tools/description-generator"
                className="rounded-xl border border-blue-500/20 bg-blue-500/5 p-5 transition hover:border-blue-400 hover:bg-blue-500/10"
              >
                <span className="font-semibold text-blue-400">
                  YouTube Description Generator
                </span>
                <p className="mt-2 text-sm text-slate-400">
                  Create YouTube description ideas.
                </p>
              </Link>

              <Link
                to="/tools/tags-generator"
                className="rounded-xl border border-green-500/20 bg-green-500/5 p-5 transition hover:border-green-400 hover:bg-green-500/10"
              >
                <span className="font-semibold text-green-400">
                  YouTube Tags Generator
                </span>
                <p className="mt-2 text-sm text-slate-400">
                  Generate tag ideas for your own content.
                </p>
              </Link>

              <Link
                to="/tools/keyword-generator"
                className="rounded-xl border border-yellow-400/20 bg-yellow-400/5 p-5 transition hover:border-yellow-300 hover:bg-yellow-400/10"
              >
                <span className="font-semibold text-yellow-300">
                  YouTube Keyword Generator
                </span>
                <p className="mt-2 text-sm text-slate-400">
                  Find keyword ideas for YouTube.
                </p>
              </Link>

              <Link
                to="/tools/thumbnail-generator"
                className="rounded-xl border border-red-500/20 bg-red-500/5 p-5 transition hover:border-red-400 hover:bg-red-500/10"
              >
                <span className="font-semibold text-red-400">
                  YouTube Thumbnail Generator
                </span>
                <p className="mt-2 text-sm text-slate-400">
                  Generate thumbnail concepts.
                </p>
              </Link>

              <Link
                to="/tools/hashtag-generator"
                className="rounded-xl border border-green-500/20 bg-green-500/5 p-5 transition hover:border-green-400 hover:bg-green-500/10"
              >
                <span className="font-semibold text-green-400">
                  YouTube Hashtag Generator
                </span>
                <p className="mt-2 text-sm text-slate-400">
                  Generate relevant YouTube hashtags.
                </p>
              </Link>
            </div>
          </div>

          <div>
            <SectionHeading color="green">
              Learn More About YouTube SEO
            </SectionHeading>

            <div className="mt-6 grid gap-4 sm:grid-cols-2">
              <Link
                to="/blog/best-youtube-seo-tools-for-creators"
                className="rounded-xl border border-blue-500/20 bg-blue-500/5 p-5 transition hover:border-blue-400 hover:bg-blue-500/10"
              >
                <span className="font-semibold text-blue-400">
                  Best YouTube SEO Tools for Creators
                </span>
                <p className="mt-2 text-sm text-slate-400">
                  Explore useful YouTube SEO tools and workflows.
                </p>
              </Link>

              <Link
                to="/blog/how-to-write-youtube-titles-that-get-more-clicks"
                className="rounded-xl border border-green-500/20 bg-green-500/5 p-5 transition hover:border-green-400 hover:bg-green-500/10"
              >
                <span className="font-semibold text-green-400">
                  How to Write YouTube Titles That Get More Clicks
                </span>
                <p className="mt-2 text-sm text-slate-400">
                  Learn practical YouTube title techniques.
                </p>
              </Link>
            </div>
          </div>

          <div>
            <SectionHeading color="blue">
              Frequently Asked Questions
            </SectionHeading>

            <div className="mt-6 space-y-4">
              {faqs.map((faq, index) => {
                const colors = [
                  "border-red-500/20 bg-red-500/5",
                  "border-yellow-400/20 bg-yellow-400/5",
                  "border-green-500/20 bg-green-500/5",
                  "border-blue-500/20 bg-blue-500/5",
                ];

                return (
                  <div
                    key={faq.question}
                    className={`rounded-xl border p-5 ${
                      colors[index % 4]
                    }`}
                  >
                    <h3 className="text-lg font-semibold text-white">
                      {faq.question}
                    </h3>

                    <p className="mt-2 leading-7 text-slate-400">
                      {faq.answer}
                    </p>
                  </div>
                );
              })}
            </div>
          </div>
        </section>
      </ToolLayout>
    </>
  );
}

export default HashtagExtractor;