import { useEffect, useRef, useState } from "react";
import { Link } from "react-router-dom";
import api from "@/services/api";

import SEO from "@/components/common/SEO";
import ToolLayout from "@/components/tool-layout/ToolLayout";
import ToolHeader from "@/components/tool-layout/ToolHeader";
import ToolForm from "@/components/tool-layout/ToolForm";
import ToolOutput from "@/components/tool-layout/ToolOutput";

function HashtagGenerator({ query = "" }) {
  const [loading, setLoading] = useState(false);
  const [results, setResults] = useState([]);
  const [lastFormData, setLastFormData] = useState(null);

  // Prevent duplicate automatic API requests
  const autoGeneratedQuery = useRef("");

  const handleGenerate = async (formData) => {
    try {
      setLoading(true);
      setLastFormData(formData);

      const response = await api.post("/generate", {
        tool: "hashtag-generator",
        ...formData,
      });

      if (response.data.success) {
        const hashtags = response.data.data
          .split("\n")
          .map((item) => item.trim())
          .filter(Boolean);

        setResults(hashtags);
      } else {
        setResults([]);
      }
    } catch (error) {
      console.error("HASHTAG GENERATOR ERROR:", error);
      console.error("RESPONSE:", error.response);
      console.error("REQUEST:", error.request);

      alert(
        error.response?.data?.message ||
          error.message ||
          "Failed to generate hashtags"
      );

      setResults([]);
    } finally {
      setLoading(false);
    }
  };

  // Hero Search → automatic generation
  useEffect(() => {
    const value = query.trim();

    if (!value) return;

    if (autoGeneratedQuery.current === value) return;

    autoGeneratedQuery.current = value;

    handleGenerate({
      topic: value,
    });
  }, [query]);

  const copyHashtag = async (text) => {
    try {
      await navigator.clipboard.writeText(text);
      alert("Copied!");
    } catch (error) {
      console.error("COPY ERROR:", error);
    }
  };

  const copyAll = async () => {
    try {
      await navigator.clipboard.writeText(results.join("\n"));
      alert("All hashtags copied!");
    } catch (error) {
      console.error("COPY ALL ERROR:", error);
    }
  };

  const faqs = [
    {
      question: "What is a YouTube hashtag generator?",
      answer:
        "A YouTube hashtag generator creates hashtag ideas based on the topic of a YouTube video.",
    },
    {
      question: "Do YouTube hashtags help videos get discovered?",
      answer:
        "Hashtags can provide another way for viewers to find related content, but they are only one part of YouTube's overall discovery system.",
    },
    {
      question: "How many YouTube hashtags should I use?",
      answer:
        "There is no single number that works for every video. Use relevant hashtags rather than adding a large number of unrelated hashtags.",
    },
    {
      question: "Should YouTube hashtags match my video topic?",
      answer:
        "Yes. Hashtags should accurately relate to the subject and content of your video.",
    },
    {
      question: "Is the TubeKit YouTube Hashtag Generator free?",
      answer:
        "Yes. TubeKit provides the YouTube Hashtag Generator as a free tool for creators.",
    },
  ];

  return (
    <>
      <SEO
        title="AI YouTube Hashtag Generator | Free Hashtag Tool | TubeKit"
        description="Generate relevant YouTube hashtags with TubeKit's free AI YouTube Hashtag Generator. Create hashtag ideas based on your video topic and improve your YouTube content strategy."
        keywords="YouTube hashtag generator, AI YouTube hashtag generator, YouTube hashtags, hashtag generator, YouTube SEO hashtags, free YouTube hashtag generator, YouTube hashtag ideas"
        canonical="/tools/hashtag-generator"
        faqs={faqs}
      />

      <ToolLayout>
        <ToolHeader
          title="AI YouTube Hashtag Generator"
          description="Generate relevant YouTube hashtags based on your video topic in seconds."
        />

        {/* Generator */}
        <ToolForm
          onGenerate={handleGenerate}
          loading={loading}
          config={{
            buttonText: "Generate Hashtags",
            topicLabel: "Video Topic",
            topicPlaceholder: "Example: React JS Tutorial",
            initialTopic: query,
            showTone: false,
            showCount: false,
            showLanguage: false,
          }}
        />

        {/* Output */}
        <ToolOutput
          results={results}
          loading={loading}
          onCopy={copyHashtag}
          onCopyAll={copyAll}
          onRegenerate={() => {
            if (lastFormData) {
              handleGenerate(lastFormData);
            }
          }}
        />

        {/* SEO Content */}
        <section className="mt-16 space-y-12">

          {/* Introduction */}
          <div>
            <h2 className="text-3xl font-black tracking-tight">
              <span className="text-red-400">
                AI YouTube Hashtag Generator
              </span>{" "}
              <span className="text-blue-400">
                Free Online Tool
              </span>
            </h2>

            <p className="mt-4 leading-8 text-muted-foreground">
              TubeKit's AI YouTube Hashtag Generator helps creators find
              relevant hashtag ideas based on their video topic. Enter
              your topic and generate hashtag suggestions that you can
              review before publishing your content.
            </p>

            <p className="mt-4 leading-8 text-muted-foreground">
              Hashtags can help identify the subject or category of a
              video and provide viewers with another way to discover
              related content. The most useful hashtags are relevant to
              the actual video.
            </p>
          </div>

          {/* How to Use */}
          <div>
            <h2 className="text-3xl font-black tracking-tight">
              <span className="text-green-400">
                How to Use
              </span>{" "}
              <span className="text-yellow-400">
                the YouTube Hashtag Generator
              </span>
            </h2>

            <ol className="mt-6 list-decimal space-y-3 pl-6 text-muted-foreground">
              <li>Enter your YouTube video's main topic.</li>
              <li>Click the Generate Hashtags button.</li>
              <li>Review the generated hashtag suggestions.</li>
              <li>Remove hashtags that are unrelated to your content.</li>
              <li>Copy the relevant hashtags.</li>
              <li>Use appropriate hashtags when publishing your video.</li>
            </ol>
          </div>

          {/* What Are Hashtags */}
          <div>
            <h2 className="text-3xl font-black tracking-tight">
              <span className="text-yellow-400">
                What Are
              </span>{" "}
              <span className="text-red-400">
                YouTube Hashtags?
              </span>
            </h2>

            <p className="mt-4 leading-8 text-muted-foreground">
              YouTube hashtags are words or phrases preceded by the #
              symbol. They help identify the topic or category of
              content and can provide viewers with another way to find
              related videos.
            </p>

            <p className="mt-4 leading-8 text-muted-foreground">
              For example, a video about YouTube SEO might use relevant
              hashtags such as #YouTubeSEO or #YouTubeTips when those
              hashtags accurately describe the content.
            </p>
          </div>

          {/* Hashtag SEO */}
          <div>
            <h2 className="text-3xl font-black tracking-tight">
              <span className="text-blue-400">
                YouTube Hashtag
              </span>{" "}
              <span className="text-green-400">
                SEO Tips
              </span>
            </h2>

            <p className="mt-4 leading-8 text-muted-foreground">
              Hashtags should support your content rather than replace
              good titles, descriptions, thumbnails or useful videos.
              Choose hashtags that accurately describe what viewers will
              find in your video.
            </p>

            <ul className="mt-6 list-disc space-y-3 pl-6 text-muted-foreground">
              <li>Use hashtags directly related to your video.</li>
              <li>Choose specific hashtags when they fit the topic.</li>
              <li>Use relevant keyword variations naturally.</li>
              <li>Avoid unrelated or misleading hashtags.</li>
              <li>Do not add hashtags simply because they are popular.</li>
              <li>Review every hashtag before publishing.</li>
            </ul>
          </div>

          {/* Hashtags vs Tags */}
          <div>
            <h2 className="text-3xl font-black tracking-tight">
              <span className="text-red-400">
                YouTube Hashtags
              </span>{" "}
              <span className="text-yellow-400">
                vs YouTube Tags
              </span>
            </h2>

            <p className="mt-4 leading-8 text-muted-foreground">
              YouTube hashtags and YouTube tags are not the same thing.
              Hashtags use the # symbol and can be visible to viewers,
              while YouTube tags are metadata added to a video's settings.
            </p>

            <div className="mt-6 overflow-x-auto rounded-2xl border border-white/10">
              <table className="w-full min-w-[600px] border-collapse text-left">
                <thead>
                  <tr className="border-b border-white/10">
                    <th className="px-5 py-4 font-bold text-red-400">
                      Hashtags
                    </th>

                    <th className="px-5 py-4 font-bold text-blue-400">
                      YouTube Tags
                    </th>
                  </tr>
                </thead>

                <tbody>
                  <tr className="border-b border-white/10">
                    <td className="px-5 py-4 text-muted-foreground">
                      Use the # symbol.
                    </td>

                    <td className="px-5 py-4 text-muted-foreground">
                      Added through YouTube's video settings.
                    </td>
                  </tr>

                  <tr>
                    <td className="px-5 py-4 text-muted-foreground">
                      Can help viewers discover related content.
                    </td>

                    <td className="px-5 py-4 text-muted-foreground">
                      Provide additional context about the video.
                    </td>
                  </tr>
                </tbody>
              </table>
            </div>
          </div>

          {/* Features */}
          <div>
            <h2 className="text-3xl font-black tracking-tight">
              <span className="text-green-400">
                YouTube Hashtag Generator
              </span>{" "}
              <span className="text-blue-400">
                Features
              </span>
            </h2>

            <ul className="mt-6 grid gap-3 text-muted-foreground sm:grid-cols-2">
              <li>✓ AI-generated hashtag ideas</li>
              <li>✓ Topic-based suggestions</li>
              <li>✓ Relevant hashtag variations</li>
              <li>✓ Easy copy functionality</li>
              <li>✓ Multiple hashtag suggestions</li>
              <li>✓ Useful for YouTube Shorts</li>
              <li>✓ Useful for long-form videos</li>
              <li>✓ Free to use</li>
            </ul>
          </div>

          {/* Tips */}
          <div>
            <h2 className="text-3xl font-black tracking-tight">
              <span className="text-yellow-400">
                Tips for Better
              </span>{" "}
              <span className="text-red-400">
                YouTube Hashtags
              </span>
            </h2>

            <ul className="mt-6 list-disc space-y-3 pl-6 text-muted-foreground">
              <li>
                Use hashtags that directly describe your video.
              </li>

              <li>
                Choose specific hashtags when they accurately match
                your topic.
              </li>

              <li>
                Avoid unrelated hashtags simply because they are popular.
              </li>

              <li>
                Keep hashtags relevant to your target audience.
              </li>

              <li>
                Review generated hashtags before using them.
              </li>

              <li>
                Focus on useful content instead of relying only on hashtags.
              </li>
            </ul>
          </div>

          {/* Internal Links */}
          <div>
            <h2 className="text-3xl font-black tracking-tight">
              <span className="text-blue-400">
                More Free
              </span>{" "}
              <span className="text-green-400">
                YouTube SEO Tools
              </span>
            </h2>

            <p className="mt-4 text-muted-foreground">
              Build a complete YouTube optimization workflow with
              TubeKit's free creator tools.
            </p>

            <div className="mt-6 grid gap-4 sm:grid-cols-2">

              <Link
                to="/tools/tags-generator"
                className="rounded-2xl border border-red-500/30 bg-red-500/5 p-5 transition hover:border-red-400"
              >
                <h3 className="font-black text-red-400">
                  AI YouTube Tags Generator →
                </h3>

                <p className="mt-2 text-sm text-muted-foreground">
                  Generate relevant tags based on your video topic.
                </p>
              </Link>

              <Link
                to="/tools/keyword-generator"
                className="rounded-2xl border border-yellow-500/30 bg-yellow-500/5 p-5 transition hover:border-yellow-400"
              >
                <h3 className="font-black text-yellow-400">
                  YouTube Keyword Generator →
                </h3>

                <p className="mt-2 text-sm text-muted-foreground">
                  Find relevant keyword ideas for your YouTube videos.
                </p>
              </Link>

              <Link
                to="/tools/title-generator"
                className="rounded-2xl border border-green-500/30 bg-green-500/5 p-5 transition hover:border-green-400"
              >
                <h3 className="font-black text-green-400">
                  AI YouTube Title Generator →
                </h3>

                <p className="mt-2 text-sm text-muted-foreground">
                  Generate engaging title ideas for your videos.
                </p>
              </Link>

              <Link
                to="/tools/description-generator"
                className="rounded-2xl border border-blue-500/30 bg-blue-500/5 p-5 transition hover:border-blue-400"
              >
                <h3 className="font-black text-blue-400">
                  AI YouTube Description Generator →
                </h3>

                <p className="mt-2 text-sm text-muted-foreground">
                  Create clear and SEO-friendly video descriptions.
                </p>
              </Link>

            </div>
          </div>

          {/* FAQ */}
          <div>
            <h2 className="text-3xl font-black tracking-tight">
              <span className="text-red-400">
                Frequently Asked Questions
              </span>{" "}
              <span className="text-blue-400">
                About YouTube Hashtags
              </span>
            </h2>

            <div className="mt-7 space-y-5">
              {faqs.map((faq, index) => (
                <div
                  key={index}
                  className="rounded-2xl border border-white/10 bg-white/[0.02] p-5"
                >
                  <h3 className="text-lg font-black text-white">
                    {faq.question}
                  </h3>

                  <p className="mt-3 leading-7 text-muted-foreground">
                    {faq.answer}
                  </p>
                </div>
              ))}
            </div>
          </div>

        </section>
      </ToolLayout>
    </>
  );
}

export default HashtagGenerator;