import { useEffect, useRef, useState } from "react";
import { Link } from "react-router-dom";
import api from "@/services/api";

import SEO from "@/components/common/SEO";
import ToolLayout from "@/components/tool-layout/ToolLayout";
import ToolHeader from "@/components/tool-layout/ToolHeader";
import ToolForm from "@/components/tool-layout/ToolForm";
import ToolOutput from "@/components/tool-layout/ToolOutput";

function HookGenerator({ query = "" }) {
  const [loading, setLoading] = useState(false);
  const [results, setResults] = useState([]);
  const [lastFormData, setLastFormData] = useState(null);

  // Prevent duplicate auto-generation
  const autoGeneratedQuery = useRef("");

  const faqs = [
    {
      question: "What is a YouTube hook?",
      answer:
        "A YouTube hook is the opening part of a video that introduces the topic and gives viewers a reason to continue watching.",
    },
    {
      question: "How long should a YouTube hook be?",
      answer:
        "There is no fixed length for every video. A good hook should communicate the main idea quickly and avoid unnecessary information.",
    },
    {
      question: "Can AI generate YouTube hooks?",
      answer:
        "Yes. AI can generate different hook ideas based on your video topic. You should review and customize the suggestions to match your content and audience.",
    },
    {
      question: "Should YouTube hooks be clickbait?",
      answer:
        "A hook can create curiosity without being misleading. Avoid promises or claims that the actual video does not deliver.",
    },
    {
      question: "Is the TubeKit YouTube Hook Generator free?",
      answer:
        "Yes. TubeKit provides the AI YouTube Hook Generator as a free tool for creators.",
    },
  ];

  const handleGenerate = async (formData) => {
    try {
      setLoading(true);
      setLastFormData(formData);

      const response = await api.post("/generate", {
        tool: "hook-generator",
        ...formData,
      });

      if (response.data.success) {
        const hooks = response.data.data
          .split("\n")
          .map((item) => item.trim())
          .filter(Boolean);

        setResults(hooks);
      } else {
        setResults([]);
      }
    } catch (error) {
      console.error("HOOK GENERATOR ERROR:", error);
      console.error("RESPONSE:", error.response);
      console.error("REQUEST:", error.request);

      alert(
        error.response?.data?.message ||
          error.message ||
          "Failed to generate hooks"
      );

      setResults([]);
    } finally {
      setLoading(false);
    }
  };

  // Hero Search → automatically generate hooks
  useEffect(() => {
    const value = query.trim();

    if (!value) return;

    if (autoGeneratedQuery.current === value) return;

    autoGeneratedQuery.current = value;

    handleGenerate({
      topic: value,
    });
  }, [query]);

  const copyHook = async (text) => {
    try {
      await navigator.clipboard.writeText(text);
      alert("Copied!");
    } catch (error) {
      console.error("COPY ERROR:", error);
    }
  };

  const copyAll = async () => {
    try {
      await navigator.clipboard.writeText(results.join("\n"));
      alert("All hooks copied!");
    } catch (error) {
      console.error("COPY ALL ERROR:", error);
    }
  };

  return (
    <>
      <SEO
        title="AI YouTube Hook Generator | Free Hook Ideas"
        description="Generate engaging YouTube hooks with TubeKit's free AI YouTube Hook Generator. Create curiosity-driven opening lines for YouTube videos and Shorts in seconds."
        keywords="YouTube hook generator, AI YouTube hook generator, YouTube intro generator, video hook generator, YouTube hook ideas, YouTube Shorts hooks, viral YouTube hooks, free hook generator"
        canonical="/tools/hook-generator"
        faqs={faqs}
      />

      <ToolLayout>
        <ToolHeader
          title="AI YouTube Hook Generator"
          description="Generate engaging, curiosity-driven YouTube hooks for videos and Shorts in seconds."
        />

        <ToolForm
          onGenerate={handleGenerate}
          loading={loading}
          config={{
            buttonText: "Generate Hooks",
            topicLabel: "Video Topic",
            topicPlaceholder: "Example: How to Grow on YouTube",
            initialTopic: query,
            showTone: false,
            showCount: false,
          }}
        />

        <ToolOutput
          results={results}
          loading={loading}
          onCopy={copyHook}
          onCopyAll={copyAll}
          onRegenerate={() => {
            if (lastFormData) {
              handleGenerate(lastFormData);
            }
          }}
        />

        {/* SEO CONTENT */}
        <section className="mt-16 space-y-12">

          {/* HOW TO USE */}
          <div>
            <h2 className="text-2xl font-bold">
              <span className="text-red-400">How to Use</span>{" "}
              <span className="text-yellow-400">
                the YouTube Hook Generator
              </span>
            </h2>

            <p className="mt-4 text-muted-foreground leading-7">
              TubeKit's AI YouTube Hook Generator helps creators generate
              opening lines for YouTube videos and Shorts. Enter your video
              topic, generate multiple hook ideas, review the suggestions,
              and choose the opening that best matches your content.
            </p>

            <ol className="mt-6 list-decimal space-y-3 pl-6 text-muted-foreground">
              <li>Enter your video's main topic or idea.</li>
              <li>Click the Generate Hooks button.</li>
              <li>Review the generated YouTube hook ideas.</li>
              <li>Choose a hook that matches your actual video content.</li>
              <li>Edit the wording to match your natural speaking style.</li>
            </ol>
          </div>

          {/* WHAT IS HOOK */}
          <div>
            <h2 className="text-2xl font-bold">
              <span className="text-blue-400">What Is a</span>{" "}
              <span className="text-red-400">YouTube Hook?</span>
            </h2>

            <p className="mt-4 text-muted-foreground leading-7">
              A YouTube hook is the opening part of a video that introduces
              the topic and gives viewers a reason to continue watching. The
              first few moments of a video should quickly establish what the
              viewer can expect.
            </p>

            <p className="mt-4 text-muted-foreground leading-7">
              A good hook does not need to be complicated. It can be a
              question, problem, surprising fact, result, story, or direct
              statement that is relevant to the video's actual content.
            </p>
          </div>

          {/* WHY HOOK MATTERS */}
          <div>
            <h2 className="text-2xl font-bold">
              <span className="text-yellow-400">Why Are YouTube Hooks</span>{" "}
              <span className="text-green-400">Important?</span>
            </h2>

            <p className="mt-4 text-muted-foreground leading-7">
              The opening of a video helps viewers quickly decide whether
              the content is relevant to them. A clear and interesting
              introduction can make the video's value easier to understand.
            </p>

            <ul className="mt-6 list-disc space-y-3 pl-6 text-muted-foreground">
              <li>Quickly introduce the video's main topic.</li>
              <li>Give viewers context about what they will learn.</li>
              <li>Create curiosity around the subject.</li>
              <li>Set expectations for the rest of the video.</li>
              <li>Make the opening more focused and engaging.</li>
            </ul>
          </div>

          {/* TYPES */}
          <div>
            <h2 className="text-2xl font-bold">
              <span className="text-red-400">Types of</span>{" "}
              <span className="text-blue-400">YouTube Hooks</span>
            </h2>

            <ul className="mt-6 space-y-4 text-muted-foreground">
              <li>
                <strong className="text-white">Question Hook:</strong>{" "}
                Start with a question related to the viewer's problem,
                interest, or goal.
              </li>

              <li>
                <strong className="text-white">Problem Hook:</strong>{" "}
                Introduce a problem that the video is going to solve.
              </li>

              <li>
                <strong className="text-white">Curiosity Hook:</strong>{" "}
                Present an interesting idea that encourages viewers to
                discover more.
              </li>

              <li>
                <strong className="text-white">Result Hook:</strong>{" "}
                Explain what the viewer can learn, achieve, or understand
                from the video.
              </li>

              <li>
                <strong className="text-white">Story Hook:</strong>{" "}
                Begin with a short situation or experience connected to the
                video's topic.
              </li>

              <li>
                <strong className="text-white">Challenge Hook:</strong>{" "}
                Introduce a challenge, experiment, or test related to the
                video.
              </li>
            </ul>
          </div>

          {/* SHORTS */}
          <div>
            <h2 className="text-2xl font-bold">
              <span className="text-green-400">YouTube Shorts</span>{" "}
              <span className="text-yellow-400">Hook Ideas</span>
            </h2>

            <p className="mt-4 text-muted-foreground leading-7">
              YouTube Shorts usually require a concise opening because the
              format is designed around short-form viewing. A Shorts hook
              should communicate the idea quickly and avoid unnecessary
              introductions.
            </p>

            <ul className="mt-6 list-disc space-y-3 pl-6 text-muted-foreground">
              <li>Start directly with the main idea.</li>
              <li>Ask a simple and relevant question.</li>
              <li>Show the result before explaining how it happened.</li>
              <li>Introduce a problem viewers recognize.</li>
              <li>Create curiosity without making misleading claims.</li>
            </ul>
          </div>

          {/* HOOK VS INTRO */}
          <div>
            <h2 className="text-2xl font-bold">
              <span className="text-blue-400">YouTube Hook</span>{" "}
              <span className="text-red-400">vs Introduction</span>
            </h2>

            <div className="mt-6 overflow-x-auto">
              <table className="w-full border-collapse text-left">
                <thead>
                  <tr className="border-b border-slate-700">
                    <th className="px-4 py-3 font-semibold text-white">
                      Hook
                    </th>
                    <th className="px-4 py-3 font-semibold text-white">
                      Introduction
                    </th>
                  </tr>
                </thead>

                <tbody>
                  <tr className="border-b border-slate-800">
                    <td className="px-4 py-4 text-muted-foreground">
                      Captures attention around the main topic.
                    </td>
                    <td className="px-4 py-4 text-muted-foreground">
                      Provides additional context about the video.
                    </td>
                  </tr>

                  <tr className="border-b border-slate-800">
                    <td className="px-4 py-4 text-muted-foreground">
                      Usually concise.
                    </td>
                    <td className="px-4 py-4 text-muted-foreground">
                      Can contain more explanation.
                    </td>
                  </tr>

                  <tr>
                    <td className="px-4 py-4 text-muted-foreground">
                      Creates an initial reason to keep watching.
                    </td>
                    <td className="px-4 py-4 text-muted-foreground">
                      Explains what the video will cover.
                    </td>
                  </tr>
                </tbody>
              </table>
            </div>
          </div>

          {/* FEATURES */}
          <div>
            <h2 className="text-2xl font-bold">
              <span className="text-yellow-400">YouTube Hook Generator</span>{" "}
              <span className="text-green-400">Features</span>
            </h2>

            <ul className="mt-6 grid gap-4 text-muted-foreground sm:grid-cols-2">
              <li>✓ AI-generated YouTube hook ideas</li>
              <li>✓ Topic-based suggestions</li>
              <li>✓ Multiple hook variations</li>
              <li>✓ Different hook styles</li>
              <li>✓ YouTube Shorts hook ideas</li>
              <li>✓ Easy copy functionality</li>
              <li>✓ Regenerate hook ideas</li>
              <li>✓ Free to use</li>
            </ul>
          </div>

          {/* TIPS */}
          <div>
            <h2 className="text-2xl font-bold">
              <span className="text-red-400">Tips for Better</span>{" "}
              <span className="text-blue-400">YouTube Hooks</span>
            </h2>

            <ul className="mt-6 list-disc space-y-3 pl-6 text-muted-foreground">
              <li>Get to the main topic quickly.</li>
              <li>
                Make the opening relevant to the video's actual content.
              </li>
              <li>
                Use clear language that your target audience understands.
              </li>
              <li>
                Create curiosity without making false promises.
              </li>
              <li>Keep the wording natural for your speaking style.</li>
              <li>Deliver on the expectation created by the hook.</li>
              <li>Avoid unnecessary introductions before the main point.</li>
            </ul>
          </div>

          {/* INTERNAL TOOLS */}
          <div>
            <h2 className="text-2xl font-bold">
              <span className="text-green-400">Create a Complete YouTube Video</span>{" "}
              <span className="text-yellow-400">with TubeKit</span>
            </h2>

            <p className="mt-4 text-muted-foreground leading-7">
              A strong hook is only one part of creating a YouTube video.
              You can combine it with a strong title, description, script,
              and thumbnail to build a more complete content package.
            </p>

            <div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
              <Link
                to="/tools/title-generator"
                className="rounded-xl border border-red-500/30 bg-red-500/5 p-5 transition hover:border-red-400 hover:bg-red-500/10"
              >
                <h3 className="font-bold text-red-400">
                  YouTube Title Generator
                </h3>
                <p className="mt-2 text-sm text-muted-foreground">
                  Generate title ideas for your video.
                </p>
              </Link>

              <Link
                to="/tools/script-generator"
                className="rounded-xl border border-yellow-500/30 bg-yellow-500/5 p-5 transition hover:border-yellow-400 hover:bg-yellow-500/10"
              >
                <h3 className="font-bold text-yellow-400">
                  YouTube Script Generator
                </h3>
                <p className="mt-2 text-sm text-muted-foreground">
                  Turn your topic into a structured script.
                </p>
              </Link>

              <Link
                to="/tools/description-generator"
                className="rounded-xl border border-green-500/30 bg-green-500/5 p-5 transition hover:border-green-400 hover:bg-green-500/10"
              >
                <h3 className="font-bold text-green-400">
                  YouTube Description Generator
                </h3>
                <p className="mt-2 text-sm text-muted-foreground">
                  Create useful video descriptions.
                </p>
              </Link>

              <Link
                to="/tools/thumbnail-generator"
                className="rounded-xl border border-blue-500/30 bg-blue-500/5 p-5 transition hover:border-blue-400 hover:bg-blue-500/10"
              >
                <h3 className="font-bold text-blue-400">
                  YouTube Thumbnail Generator
                </h3>
                <p className="mt-2 text-sm text-muted-foreground">
                  Generate thumbnail concepts for your videos.
                </p>
              </Link>
            </div>
          </div>

          {/* FAQ */}
          <div>
            <h2 className="text-2xl font-bold">
              <span className="text-red-400">Frequently Asked</span>{" "}
              <span className="text-yellow-400">Questions</span>
            </h2>

            <div className="mt-8 space-y-7">
              {faqs.map((faq) => (
                <div key={faq.question}>
                  <h3 className="text-lg font-semibold text-white">
                    {faq.question}
                  </h3>

                  <p className="mt-2 text-muted-foreground leading-7">
                    {faq.answer}
                  </p>
                </div>
              ))}
            </div>
          </div>
        </section>
      </ToolLayout>
    </>
  );
}

export default HookGenerator;