import { useEffect, useRef, useState } from "react";
import { Link } from "react-router-dom";
import api from "@/services/api";

import ToolLayout from "@/components/tool-layout/ToolLayout";
import ToolHeader from "@/components/tool-layout/ToolHeader";
import ToolForm from "@/components/tool-layout/ToolForm";
import ToolOutput from "@/components/tool-layout/ToolOutput";
import SEO from "@/components/common/SEO";

function KeywordGenerator({ query = "" }) {
  const [loading, setLoading] = useState(false);
  const [results, setResults] = useState([]);
  const [lastFormData, setLastFormData] = useState(null);

  const autoGeneratedQuery = useRef("");

  const faqs = [
    {
      question: "What is a YouTube keyword generator?",
      answer:
        "A YouTube keyword generator is a tool that creates keyword ideas based on the topic of a YouTube video. These ideas can help creators understand relevant phrases and topics for their content.",
    },
    {
      question: "Do YouTube keywords help videos rank?",
      answer:
        "Relevant keywords can help describe a video's topic more clearly, but keywords alone do not guarantee higher rankings. YouTube discovery depends on multiple factors including relevance, viewer satisfaction, engagement, titles, thumbnails and content quality.",
    },
    {
      question: "Should I put keywords in my YouTube title?",
      answer:
        "If a keyword naturally describes the video's topic, it can be useful in the title. The title should remain clear, accurate and appealing to viewers rather than being filled with keywords.",
    },
    {
      question: "What are long-tail YouTube keywords?",
      answer:
        "Long-tail keywords are more specific phrases that usually describe a narrower search intent. For example, 'how to edit YouTube videos on mobile' is more specific than simply 'YouTube editing'.",
    },
    {
      question: "Is the TubeKit YouTube Keyword Generator free?",
      answer:
        "Yes. TubeKit provides the AI YouTube Keyword Generator as a free tool for creators.",
    },
  ];

  const handleGenerate = async (formData) => {
    try {
      setLoading(true);
      setLastFormData(formData);

      const response = await api.post("/generate", {
        tool: "keyword-generator",
        ...formData,
      });

      if (response.data.success) {
        const keywords = response.data.data
          .split("\n")
          .map((item) => item.trim())
          .filter(Boolean);

        setResults(keywords);
      } else {
        setResults([]);
      }
    } catch (error) {
      console.error("KEYWORD GENERATOR ERROR:", error);
      console.error("RESPONSE:", error.response);
      console.error("REQUEST:", error.request);

      alert(
        error.response?.data?.message ||
          error.message ||
          "Failed to generate keywords"
      );

      setResults([]);
    } finally {
      setLoading(false);
    }
  };

  // Hero Search → automatic keyword generation
  useEffect(() => {
    const value = query.trim();

    if (!value) return;

    if (autoGeneratedQuery.current === value) return;

    autoGeneratedQuery.current = value;

    handleGenerate({
      topic: value,
      language: "English",
      tone: "Professional",
      count: 10,
    });
  }, [query]);

  const copyKeyword = async (text) => {
    try {
      await navigator.clipboard.writeText(text);
      alert("Copied!");
    } catch (error) {
      console.error("COPY ERROR:", error);
    }
  };

  const copyAll = async () => {
    try {
      await navigator.clipboard.writeText(results.join("\n"));
      alert("All keywords copied!");
    } catch (error) {
      console.error("COPY ALL ERROR:", error);
    }
  };

  return (
    <>
      <SEO
        title="AI YouTube Keyword Generator | Free YouTube Keywords"
        description="Generate relevant YouTube keywords with TubeKit's free AI YouTube Keyword Generator. Find keyword ideas, long-tail phrases and search-intent keywords for your videos."
        keywords="YouTube keyword generator, AI YouTube keyword generator, YouTube keywords, YouTube SEO keywords, keyword research tool, YouTube keyword research, long tail YouTube keywords"
        canonical="/tools/keyword-generator"
        faqs={faqs}
      />

      <ToolLayout>
        <ToolHeader
          title="AI YouTube Keyword Generator"
          description="Generate relevant YouTube keyword ideas based on your video topic in seconds."
        />

        <ToolForm
          onGenerate={handleGenerate}
          loading={loading}
          config={{
            buttonText: "Generate Keywords",
            topicLabel: "Video Topic",
            topicPlaceholder: "Example: React Tutorial",
            initialTopic: query,
            showTone: false,
            showCount: false,
            showLanguage: false,
          }}
        />

        <ToolOutput
          results={results}
          loading={loading}
          onCopy={copyKeyword}
          onCopyAll={copyAll}
          onRegenerate={() => {
            if (lastFormData) {
              handleGenerate(lastFormData);
            }
          }}
        />

        {/* SEO CONTENT */}
        <section className="mt-16 space-y-12">

          {/* HOW TO USE */}
          <div>
            <h2 className="text-2xl font-bold">
              <span className="text-red-400">How to Use</span>{" "}
              <span className="text-yellow-400">
                the YouTube Keyword Generator
              </span>
            </h2>

            <p className="mt-4 leading-7 text-muted-foreground">
              TubeKit's AI YouTube Keyword Generator helps creators discover
              relevant keyword ideas based on their video topic. Instead of
              manually brainstorming dozens of search phrases, you can enter
              your main topic and generate related keyword suggestions in
              seconds.
            </p>

            <ol className="mt-6 list-decimal space-y-3 pl-6 text-muted-foreground">
              <li>Enter the main topic of your YouTube video.</li>
              <li>Click the Generate Keywords button.</li>
              <li>Review the generated keyword suggestions.</li>
              <li>Remove keywords that are not relevant to your content.</li>
              <li>Use suitable keywords naturally in your content strategy.</li>
            </ol>
          </div>

          {/* WHAT ARE KEYWORDS */}
          <div>
            <h2 className="text-2xl font-bold">
              <span className="text-blue-400">What Are</span>{" "}
              <span className="text-red-400">YouTube Keywords?</span>
            </h2>

            <p className="mt-4 leading-7 text-muted-foreground">
              YouTube keywords are words and phrases that describe the topic
              or subject of a video. They can help creators understand how
              their content relates to the searches and topics their target
              audience may be interested in.
            </p>

            <p className="mt-4 leading-7 text-muted-foreground">
              For example, a video about learning React could target phrases
              such as "React tutorial", "React JS tutorial for beginners",
              "learn React", or "React project tutorial". The best keywords
              are closely related to what the video actually provides.
            </p>
          </div>

          {/* SEARCH INTENT */}
          <div>
            <h2 className="text-2xl font-bold">
              <span className="text-yellow-400">
                Understanding YouTube
              </span>{" "}
              <span className="text-green-400">Search Intent</span>
            </h2>

            <p className="mt-4 leading-7 text-muted-foreground">
              Search intent describes what a viewer is trying to find when
              entering a search query. Understanding search intent can help
              creators choose keywords that better match the purpose of their
              videos.
            </p>

            <ul className="mt-6 list-disc space-y-3 pl-6 text-muted-foreground">
              <li>
                <strong className="text-white">Informational:</strong>{" "}
                searches looking for explanations, facts or information.
              </li>

              <li>
                <strong className="text-white">How-to:</strong>{" "}
                searches looking for tutorials or step-by-step instructions.
              </li>

              <li>
                <strong className="text-white">Comparison:</strong>{" "}
                searches comparing products, tools, services or ideas.
              </li>

              <li>
                <strong className="text-white">Review:</strong>{" "}
                searches looking for opinions or evaluations.
              </li>

              <li>
                <strong className="text-white">Problem-solving:</strong>{" "}
                searches looking for a solution to a specific problem.
              </li>
            </ul>
          </div>

          {/* LONG TAIL KEYWORDS */}
          <div>
            <h2 className="text-2xl font-bold">
              <span className="text-red-400">Why Use</span>{" "}
              <span className="text-blue-400">Long-Tail Keywords?</span>
            </h2>

            <p className="mt-4 leading-7 text-muted-foreground">
              Long-tail keywords are specific search phrases that describe a
              narrower topic or intent. They can be useful when a creator
              wants to target a particular audience rather than a very broad
              topic.
            </p>

            <div className="mt-6 overflow-x-auto">
              <table className="w-full border-collapse text-left">
                <thead>
                  <tr className="border-b border-slate-700">
                    <th className="px-4 py-3 font-semibold text-white">
                      Broad Keyword
                    </th>
                    <th className="px-4 py-3 font-semibold text-white">
                      More Specific Keyword
                    </th>
                  </tr>
                </thead>

                <tbody>
                  <tr className="border-b border-slate-800">
                    <td className="px-4 py-4 text-muted-foreground">
                      YouTube SEO
                    </td>
                    <td className="px-4 py-4 text-muted-foreground">
                      YouTube SEO tips for beginners
                    </td>
                  </tr>

                  <tr className="border-b border-slate-800">
                    <td className="px-4 py-4 text-muted-foreground">
                      React
                    </td>
                    <td className="px-4 py-4 text-muted-foreground">
                      React JS tutorial for beginners
                    </td>
                  </tr>

                  <tr>
                    <td className="px-4 py-4 text-muted-foreground">
                      Video editing
                    </td>
                    <td className="px-4 py-4 text-muted-foreground">
                      How to edit YouTube videos on mobile
                    </td>
                  </tr>
                </tbody>
              </table>
            </div>
          </div>

          {/* KEYWORD PLACEMENT */}
          <div>
            <h2 className="text-2xl font-bold">
              <span className="text-green-400">Where to Use</span>{" "}
              <span className="text-yellow-400">YouTube Keywords?</span>
            </h2>

            <p className="mt-4 leading-7 text-muted-foreground">
              Once you identify relevant keywords, use them naturally where
              they genuinely describe your video. Avoid forcing the same
              keyword repeatedly into every part of your content.
            </p>

            <ul className="mt-6 grid gap-4 text-muted-foreground sm:grid-cols-2">
              <li className="rounded-xl border border-red-500/30 bg-red-500/5 p-4">
                <strong className="text-red-400">
                  Video Title
                </strong>
                <p className="mt-2 text-sm">
                  Use a relevant phrase when it makes the title clearer.
                </p>
              </li>

              <li className="rounded-xl border border-yellow-500/30 bg-yellow-500/5 p-4">
                <strong className="text-yellow-400">
                  Video Description
                </strong>
                <p className="mt-2 text-sm">
                  Explain the video naturally using relevant terminology.
                </p>
              </li>

              <li className="rounded-xl border border-green-500/30 bg-green-500/5 p-4">
                <strong className="text-green-400">
                  Video Content
                </strong>
                <p className="mt-2 text-sm">
                  Make sure the actual video covers the topic described.
                </p>
              </li>

              <li className="rounded-xl border border-blue-500/30 bg-blue-500/5 p-4">
                <strong className="text-blue-400">
                  Content Strategy
                </strong>
                <p className="mt-2 text-sm">
                  Use keyword ideas to discover related content topics.
                </p>
              </li>
            </ul>
          </div>

          {/* FEATURES */}
          <div>
            <h2 className="text-2xl font-bold">
              <span className="text-red-400">YouTube Keyword Generator</span>{" "}
              <span className="text-green-400">Features</span>
            </h2>

            <ul className="mt-6 grid gap-4 text-muted-foreground sm:grid-cols-2">
              <li>✓ AI-generated keyword ideas</li>
              <li>✓ Topic-based suggestions</li>
              <li>✓ Keyword variations</li>
              <li>✓ Search-intent ideas</li>
              <li>✓ Long-tail keyword ideas</li>
              <li>✓ Easy copy functionality</li>
              <li>✓ Regenerate keyword suggestions</li>
              <li>✓ Free to use</li>
            </ul>
          </div>

          {/* TIPS */}
          <div>
            <h2 className="text-2xl font-bold">
              <span className="text-yellow-400">Tips for Better</span>{" "}
              <span className="text-blue-400">YouTube Keywords</span>
            </h2>

            <ul className="mt-6 list-disc space-y-3 pl-6 text-muted-foreground">
              <li>
                Choose keywords that accurately describe your video.
              </li>

              <li>
                Think about the phrases your target viewers may search for.
              </li>

              <li>
                Include specific phrases when they match your content.
              </li>

              <li>
                Use long-tail keywords when they closely match the video's
                purpose.
              </li>

              <li>
                Avoid unrelated keywords simply because they appear popular.
              </li>

              <li>
                Never sacrifice readability just to include keywords.
              </li>

              <li>
                Make sure your actual video delivers what the keyword
                suggests.
              </li>
            </ul>
          </div>

          {/* INTERNAL LINKS */}
          <div>
            <h2 className="text-2xl font-bold">
              <span className="text-green-400">
                Build a Complete YouTube SEO
              </span>{" "}
              <span className="text-red-400">Strategy with TubeKit</span>
            </h2>

            <p className="mt-4 leading-7 text-muted-foreground">
              Keyword research is only one part of YouTube optimization.
              After finding relevant keyword ideas, you can use TubeKit's
              other creator tools to build your title, description, tags and
              content.
            </p>

            <div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">

              <Link
                to="/tools/title-generator"
                className="rounded-xl border border-red-500/30 bg-red-500/5 p-5 transition hover:border-red-400 hover:bg-red-500/10"
              >
                <h3 className="font-bold text-red-400">
                  YouTube Title Generator
                </h3>
                <p className="mt-2 text-sm text-muted-foreground">
                  Create title ideas using your video topic.
                </p>
              </Link>

              <Link
                to="/tools/tags-generator"
                className="rounded-xl border border-yellow-500/30 bg-yellow-500/5 p-5 transition hover:border-yellow-400 hover:bg-yellow-500/10"
              >
                <h3 className="font-bold text-yellow-400">
                  YouTube Tags Generator
                </h3>
                <p className="mt-2 text-sm text-muted-foreground">
                  Generate relevant tags for your video.
                </p>
              </Link>

              <Link
                to="/tools/description-generator"
                className="rounded-xl border border-green-500/30 bg-green-500/5 p-5 transition hover:border-green-400 hover:bg-green-500/10"
              >
                <h3 className="font-bold text-green-400">
                  YouTube Description Generator
                </h3>
                <p className="mt-2 text-sm text-muted-foreground">
                  Create useful and SEO-friendly descriptions.
                </p>
              </Link>

              <Link
                to="/tools/hashtag-generator"
                className="rounded-xl border border-blue-500/30 bg-blue-500/5 p-5 transition hover:border-blue-400 hover:bg-blue-500/10"
              >
                <h3 className="font-bold text-blue-400">
                  YouTube Hashtag Generator
                </h3>
                <p className="mt-2 text-sm text-muted-foreground">
                  Generate relevant hashtags for your videos.
                </p>
              </Link>

            </div>
          </div>

          {/* FAQ */}
          <div>
            <h2 className="text-2xl font-bold">
              <span className="text-red-400">
                Frequently Asked
              </span>{" "}
              <span className="text-yellow-400">
                Questions
              </span>
            </h2>

            <div className="mt-8 space-y-7">
              {faqs.map((faq) => (
                <div key={faq.question}>
                  <h3 className="text-lg font-semibold text-white">
                    {faq.question}
                  </h3>

                  <p className="mt-2 leading-7 text-muted-foreground">
                    {faq.answer}
                  </p>
                </div>
              ))}
            </div>
          </div>

        </section>
      </ToolLayout>
    </>
  );
}

export default KeywordGenerator;