import { useEffect, useRef, useState } from "react";
import { Link } from "react-router-dom";
import api from "@/services/api";

import SEO from "@/components/common/SEO";
import ToolLayout from "@/components/tool-layout/ToolLayout";
import ToolHeader from "@/components/tool-layout/ToolHeader";
import ToolForm from "@/components/tool-layout/ToolForm";
import ToolOutput from "@/components/tool-layout/ToolOutput";

function OutlineGenerator({ query = "" }) {
  const [loading, setLoading] = useState(false);
  const [results, setResults] = useState("");
  const [lastFormData, setLastFormData] = useState(null);

  // Prevent duplicate API request from Hero Search
  const autoGeneratedQuery = useRef("");

  const handleGenerate = async (formData) => {
    try {
      setLoading(true);
      setLastFormData(formData);

      const response = await api.post("/generate", {
        tool: "outline-generator",
        ...formData,
      });

      if (response.data.success) {
        setResults(response.data.data);
      } else {
        setResults("");
      }
    } catch (error) {
      console.error("OUTLINE GENERATOR ERROR:", error);
      console.error("RESPONSE:", error.response);
      console.error("REQUEST:", error.request);

      alert(
        error.response?.data?.message ||
          error.message ||
          "Failed to generate outline"
      );

      setResults("");
    } finally {
      setLoading(false);
    }
  };

  // Hero Search → automatically generate outline
  useEffect(() => {
    const value = query.trim();

    if (!value) return;
    if (autoGeneratedQuery.current === value) return;

    autoGeneratedQuery.current = value;

    handleGenerate({
      topic: value,
      language: "English",
      tone: "Professional",
    });
  }, [query]);

  const copyOutline = async () => {
    if (!results) return;

    try {
      await navigator.clipboard.writeText(results);
      alert("Outline copied!");
    } catch (error) {
      console.error("COPY ERROR:", error);
    }
  };

  const faqs = [
    {
      question: "What is a YouTube video outline?",
      answer:
        "A YouTube video outline is a structured plan containing the main sections and ideas that will be covered in a YouTube video.",
    },
    {
      question: "Why should I create a YouTube video outline?",
      answer:
        "An outline can help organize ideas, maintain focus, and make the scripting and recording process easier.",
    },
    {
      question: "Can AI create a complete YouTube video outline?",
      answer:
        "Yes. AI can generate a starting structure based on a topic. Review and customize the result so it matches your actual video and audience.",
    },
    {
      question: "Can I use an outline for YouTube Shorts?",
      answer:
        "Yes. Shorts can also benefit from a simple structure that organizes the hook, main point, and conclusion.",
    },
    {
      question: "Is the TubeKit YouTube Outline Generator free?",
      answer:
        "Yes. TubeKit provides the AI YouTube Outline Generator as a free tool for creators.",
    },
  ];

  return (
    <>
      <SEO
        title="AI YouTube Outline Generator | Free Video Outline Maker"
        description="Create structured YouTube video outlines with TubeKit's free AI YouTube Outline Generator. Organize topics, sections, ideas and video structure in seconds."
        keywords="YouTube outline generator, AI YouTube outline generator, video outline generator, YouTube video outline, AI video planner, YouTube content outline, free YouTube outline generator, video structure generator"
        canonical="/tools/outline-generator"
        faqs={faqs}
      />

      <ToolLayout>
        <ToolHeader
          title="AI YouTube Outline Generator"
          description="Create clear and structured YouTube video outlines with AI in seconds."
        />

        <ToolForm
          onGenerate={handleGenerate}
          loading={loading}
          config={{
            buttonText: "Generate Outline",
            topicLabel: "Video Topic",
            topicPlaceholder: "Example: React Tutorial",
            initialTopic: query,
            showTone: false,
            showCount: false,
          }}
        />

        <ToolOutput
          results={results}
          loading={loading}
          onCopy={copyOutline}
          onCopyAll={copyOutline}
          onRegenerate={() => {
            if (lastFormData) {
              handleGenerate(lastFormData);
            }
          }}
        />

        {/* SEO CONTENT */}
        <section className="mt-16 space-y-12">

          {/* Introduction */}
          <div>
            <h2 className="text-3xl font-black tracking-tight">
              <span className="text-red-400">AI YouTube</span>{" "}
              <span className="text-yellow-400">Outline Generator</span>
            </h2>

            <p className="mt-4 leading-8 text-muted-foreground">
              Planning a YouTube video becomes easier when you know exactly
              what you want to cover. TubeKit's AI YouTube Outline Generator
              helps creators turn a video topic into a clear and organized
              content structure.
            </p>

            <p className="mt-4 leading-8 text-muted-foreground">
              Instead of starting with a blank page, enter your topic and
              generate an outline that can be used as a starting point for
              your script, research or recording plan.
            </p>
          </div>

          {/* How to Use */}
          <div>
            <h2 className="text-3xl font-black tracking-tight">
              <span className="text-green-400">How to Use the</span>{" "}
              <span className="text-blue-400">
                YouTube Outline Generator
              </span>
            </h2>

            <p className="mt-4 leading-8 text-muted-foreground">
              Create a structured video outline in a few simple steps:
            </p>

            <ol className="mt-5 list-decimal space-y-3 pl-6 text-muted-foreground">
              <li>Enter the topic or main idea of your YouTube video.</li>
              <li>Click the Generate Outline button.</li>
              <li>Review the suggested video structure.</li>
              <li>Add, remove or rearrange sections when necessary.</li>
              <li>Use the final outline as a guide for your script or recording.</li>
            </ol>
          </div>

          {/* What Is Outline */}
          <div>
            <h2 className="text-3xl font-black tracking-tight">
              <span className="text-red-400">What Is a</span>{" "}
              <span className="text-yellow-400">
                YouTube Video Outline?
              </span>
            </h2>

            <p className="mt-4 leading-8 text-muted-foreground">
              A YouTube video outline is a structured plan that organizes the
              main sections and ideas of a video before the full script is
              written. It helps creators decide what information should be
              presented and in what order.
            </p>

            <p className="mt-4 leading-8 text-muted-foreground">
              A good outline can make the writing and recording process more
              organized while helping the video stay focused on its main
              topic.
            </p>
          </div>

          {/* Structure */}
          <div>
            <h2 className="text-3xl font-black tracking-tight">
              <span className="text-green-400">YouTube Video</span>{" "}
              <span className="text-blue-400">Outline Structure</span>
            </h2>

            <p className="mt-4 leading-8 text-muted-foreground">
              A useful YouTube outline can contain the following sections:
            </p>

            <div className="mt-6 grid gap-4 sm:grid-cols-2">
              <div className="rounded-2xl border border-red-500/30 bg-red-500/5 p-5">
                <h3 className="font-bold text-red-400">
                  1. Hook
                </h3>
                <p className="mt-2 text-sm leading-7 text-muted-foreground">
                  Start with the main idea or reason viewers should continue
                  watching.
                </p>
              </div>

              <div className="rounded-2xl border border-yellow-500/30 bg-yellow-500/5 p-5">
                <h3 className="font-bold text-yellow-400">
                  2. Introduction
                </h3>
                <p className="mt-2 text-sm leading-7 text-muted-foreground">
                  Introduce the subject and establish what the video will
                  cover.
                </p>
              </div>

              <div className="rounded-2xl border border-green-500/30 bg-green-500/5 p-5">
                <h3 className="font-bold text-green-400">
                  3. Main Points
                </h3>
                <p className="mt-2 text-sm leading-7 text-muted-foreground">
                  Organize the important sections, explanations and examples.
                </p>
              </div>

              <div className="rounded-2xl border border-blue-500/30 bg-blue-500/5 p-5">
                <h3 className="font-bold text-blue-400">
                  4. Conclusion & CTA
                </h3>
                <p className="mt-2 text-sm leading-7 text-muted-foreground">
                  Summarize the key points and add a relevant call to action.
                </p>
              </div>
            </div>
          </div>

          {/* Features */}
          <div>
            <h2 className="text-3xl font-black tracking-tight">
              <span className="text-red-400">AI Outline Generator</span>{" "}
              <span className="text-yellow-400">Features</span>
            </h2>

            <ul className="mt-6 grid gap-3 text-muted-foreground sm:grid-cols-2">
              <li>✓ AI-generated video outlines</li>
              <li>✓ Topic-based structure</li>
              <li>✓ Multiple section ideas</li>
              <li>✓ Organized video planning</li>
              <li>✓ Clear content structure</li>
              <li>✓ Easy copy functionality</li>
              <li>✓ Regenerate outline option</li>
              <li>✓ Free to use</li>
            </ul>
          </div>

          {/* Tips */}
          <div>
            <h2 className="text-3xl font-black tracking-tight">
              <span className="text-green-400">Tips for Creating</span>{" "}
              <span className="text-blue-400">
                Better YouTube Outlines
              </span>
            </h2>

            <ul className="mt-6 list-disc space-y-3 pl-6 text-muted-foreground">
              <li>Start with one clear goal for the video.</li>
              <li>Arrange sections in a logical order.</li>
              <li>Keep each section focused on one main idea.</li>
              <li>
                Remove information that does not support the video's purpose.
              </li>
              <li>Include examples when they help explain the topic.</li>
              <li>Adjust the outline to your audience and video format.</li>
              <li>Use the outline as a guide instead of reading it word-for-word.</li>
            </ul>
          </div>

          {/* Internal Links */}
          <div>
            <h2 className="text-3xl font-black tracking-tight">
              <span className="text-red-400">Build Your YouTube</span>{" "}
              <span className="text-yellow-400">Content Faster</span>
            </h2>

            <p className="mt-4 leading-8 text-muted-foreground">
              An outline is the starting point of your content workflow.
              After creating your structure, use TubeKit's other creator
              tools to develop the rest of your video.
            </p>

            <div className="mt-6 grid gap-4 sm:grid-cols-2">

              <Link
                to="/tools/script-generator"
                className="rounded-2xl border border-red-500/30 bg-red-500/5 p-5 transition hover:border-red-400"
              >
                <h3 className="font-bold text-red-400">
                  YouTube Script Generator →
                </h3>

                <p className="mt-2 text-sm text-muted-foreground">
                  Turn your video topic into a structured YouTube script.
                </p>
              </Link>

              <Link
                to="/tools/hook-generator"
                className="rounded-2xl border border-yellow-500/30 bg-yellow-500/5 p-5 transition hover:border-yellow-400"
              >
                <h3 className="font-bold text-yellow-400">
                  YouTube Hook Generator →
                </h3>

                <p className="mt-2 text-sm text-muted-foreground">
                  Create engaging hooks for the beginning of your videos.
                </p>
              </Link>

              <Link
                to="/tools/title-generator"
                className="rounded-2xl border border-green-500/30 bg-green-500/5 p-5 transition hover:border-green-400"
              >
                <h3 className="font-bold text-green-400">
                  YouTube Title Generator →
                </h3>

                <p className="mt-2 text-sm text-muted-foreground">
                  Generate relevant and clickable title ideas.
                </p>
              </Link>

              <Link
                to="/tools/description-generator"
                className="rounded-2xl border border-blue-500/30 bg-blue-500/5 p-5 transition hover:border-blue-400"
              >
                <h3 className="font-bold text-blue-400">
                  YouTube Description Generator →
                </h3>

                <p className="mt-2 text-sm text-muted-foreground">
                  Create useful descriptions for your YouTube videos.
                </p>
              </Link>

              <Link
                to="/tools/shorts-generator"
                className="rounded-2xl border border-red-500/30 bg-red-500/5 p-5 transition hover:border-red-400"
              >
                <h3 className="font-bold text-red-400">
                  YouTube Shorts Generator →
                </h3>

                <p className="mt-2 text-sm text-muted-foreground">
                  Generate content ideas for YouTube Shorts.
                </p>
              </Link>

              <Link
                to="/tools/tags-generator"
                className="rounded-2xl border border-yellow-500/30 bg-yellow-500/5 p-5 transition hover:border-yellow-400"
              >
                <h3 className="font-bold text-yellow-400">
                  YouTube Tags Generator →
                </h3>

                <p className="mt-2 text-sm text-muted-foreground">
                  Generate relevant tags based on your video topic.
                </p>
              </Link>

            </div>
          </div>

          {/* FAQ */}
          <div>
            <h2 className="text-3xl font-black tracking-tight">
              <span className="text-green-400">
                Frequently Asked Questions
              </span>{" "}
              <span className="text-blue-400">
                About YouTube Outlines
              </span>
            </h2>

            <div className="mt-7 space-y-5">
              {faqs.map((faq, index) => (
                <div
                  key={index}
                  className="rounded-2xl border border-white/10 bg-white/[0.02] p-5"
                >
                  <h3 className="text-lg font-bold text-white">
                    {faq.question}
                  </h3>

                  <p className="mt-2 leading-7 text-muted-foreground">
                    {faq.answer}
                  </p>
                </div>
              ))}
            </div>
          </div>

          {/* Final CTA */}
          <div className="rounded-3xl border border-blue-500/30 bg-blue-500/5 p-7">
            <h2 className="text-2xl font-black text-white">
              Create Your YouTube Outline Now
            </h2>

            <p className="mt-3 leading-7 text-muted-foreground">
              Enter your video topic above and generate a structured outline
              that you can customize for your audience and content style.
            </p>

            <div className="mt-5 flex flex-wrap gap-3">
              <button
                onClick={() =>
                  window.scrollTo({
                    top: 0,
                    behavior: "smooth",
                  })
                }
                className="rounded-xl bg-blue-600 px-5 py-3 font-semibold text-white transition hover:bg-blue-500"
              >
                Generate Outline ↑
              </button>

              <Link
                to="/tools/script-generator"
                className="rounded-xl bg-green-600 px-5 py-3 font-semibold text-white transition hover:bg-green-500"
              >
                Create Full Script →
              </Link>
            </div>
          </div>

        </section>
      </ToolLayout>
    </>
  );
}

export default OutlineGenerator;