import { useEffect, useRef, useState } from "react";
import { Link } from "react-router-dom";
import api from "@/services/api";

import SEO from "@/components/common/SEO";
import ToolLayout from "@/components/tool-layout/ToolLayout";
import ToolHeader from "@/components/tool-layout/ToolHeader";
import ToolForm from "@/components/tool-layout/ToolForm";
import ToolOutput from "@/components/tool-layout/ToolOutput";

function ScriptGenerator({ query = "" }) {
  const [loading, setLoading] = useState(false);
  const [results, setResults] = useState("");
  const [lastFormData, setLastFormData] = useState(null);

  const autoGeneratedQuery = useRef("");

  const handleGenerate = async (formData) => {
    try {
      setLoading(true);
      setLastFormData(formData);

      const response = await api.post("/generate", {
        tool: "script-generator",
        ...formData,
      });

      if (response.data.success) {
        setResults(response.data.data);
      } else {
        setResults("");
      }
    } catch (error) {
      console.error("SCRIPT GENERATOR ERROR:", error);
      console.error("RESPONSE:", error.response);
      console.error("REQUEST:", error.request);

      alert(
        error.response?.data?.message ||
          error.message ||
          "Failed to generate script"
      );

      setResults("");
    } finally {
      setLoading(false);
    }
  };

  // Hero Search → automatic generation
  useEffect(() => {
    const value = query.trim();

    if (!value) return;
    if (autoGeneratedQuery.current === value) return;

    autoGeneratedQuery.current = value;

    handleGenerate({
      topic: value,
      language: "English",
      tone: "Professional",
    });
  }, [query]);

  const copyScript = async () => {
    if (!results) return;

    try {
      await navigator.clipboard.writeText(results);
      alert("Script copied!");
    } catch (error) {
      console.error("COPY ERROR:", error);
    }
  };

  const faqs = [
    {
      question: "What is an AI YouTube script generator?",
      answer:
        "An AI YouTube script generator creates a draft video script from a topic and instructions provided by the creator.",
    },
    {
      question: "Can I use an AI script generator for YouTube Shorts?",
      answer:
        "Yes. You can create short-form video scripts by providing a focused topic and concise requirements.",
    },
    {
      question: "Can I edit the generated YouTube script?",
      answer:
        "Yes. AI-generated scripts should be reviewed and customized to match your voice, audience and video content.",
    },
    {
      question: "Is the TubeKit YouTube Script Generator free?",
      answer:
        "Yes. TubeKit provides its AI YouTube Script Generator as a free tool for creators.",
    },
    {
      question: "Should I publish an AI-generated script without editing it?",
      answer:
        "It is recommended to review and edit the generated draft before publishing. Verify factual information and make the script natural for your audience.",
    },
  ];

  return (
    <>
      <SEO
        title="AI YouTube Script Generator | Free YouTube Script Writer"
        description="Create engaging YouTube video scripts with TubeKit's free AI YouTube Script Generator. Generate structured scripts, hooks, introductions, main content and CTAs in seconds."
        keywords="YouTube script generator, AI YouTube script generator, YouTube video script generator, AI script writer, YouTube script writer, free YouTube script generator, YouTube Shorts script generator, video script generator"
        canonical="/tools/script-generator"
        breadcrumbs={[
          { name: "Home", url: "/" },
          { name: "Tools", url: "/tools/script-generator" },
          {
            name: "YouTube Script Generator",
            url: "/tools/script-generator",
          },
        ]}
        faqs={faqs}
      />

      <ToolLayout>
        <ToolHeader
          title="AI YouTube Script Generator"
          description="Generate structured, engaging YouTube video scripts with AI in seconds."
        />

        <ToolForm
          onGenerate={handleGenerate}
          loading={loading}
          config={{
            buttonText: "Generate Script",
            topicLabel: "Video Topic",
            topicPlaceholder: "Example: How to Learn React",
            initialTopic: query,
            showCount: false,
          }}
        />

        <ToolOutput
          results={results}
          loading={loading}
          onCopy={copyScript}
          onCopyAll={copyScript}
          onRegenerate={() => {
            if (lastFormData) {
              handleGenerate(lastFormData);
            }
          }}
        />

        {/* SEO CONTENT */}
        <section className="mt-16 space-y-12">

          {/* INTRO */}
          <div>
            <h2 className="text-3xl font-black tracking-tight text-white">
              <span className="text-red-400">AI YouTube</span>{" "}
              <span className="text-yellow-400">Script Generator</span>
            </h2>

            <p className="mt-4 leading-8 text-muted-foreground">
              Creating a good YouTube video starts with a clear idea and a
              well-structured script. TubeKit's AI YouTube Script Generator
              helps creators turn a topic into an organized video script
              with an introduction, main content, key points and a call to
              action.
            </p>

            <p className="mt-4 leading-8 text-muted-foreground">
              Instead of starting from a blank page, enter your video topic
              and generate a script draft that you can review, customize and
              adapt to your own speaking style.
            </p>
          </div>

          {/* HOW TO USE */}
          <div>
            <h2 className="text-3xl font-black tracking-tight">
              <span className="text-red-400">How to Use the</span>{" "}
              <span className="text-yellow-400">YouTube Script Generator</span>
            </h2>

            <p className="mt-4 leading-8 text-muted-foreground">
              Follow these simple steps to create a YouTube video script:
            </p>

            <ol className="mt-5 list-decimal space-y-3 pl-6 text-muted-foreground">
              <li>Enter the main topic of your YouTube video.</li>
              <li>Provide relevant details or requirements.</li>
              <li>Choose the language and tone when available.</li>
              <li>Click the Generate Script button.</li>
              <li>Review the generated script.</li>
              <li>Edit the script to match your personality and audience.</li>
              <li>Use the final script as a guide while recording.</li>
            </ol>
          </div>

          {/* WHAT IS SCRIPT */}
          <div>
            <h2 className="text-3xl font-black tracking-tight">
              <span className="text-green-400">What Is a</span>{" "}
              <span className="text-blue-400">YouTube Video Script?</span>
            </h2>

            <p className="mt-4 leading-8 text-muted-foreground">
              A YouTube video script is a written plan that organizes what
              will be said or shown during a video. It can include the hook,
              introduction, main points, examples, transitions, conclusion
              and call to action.
            </p>

            <p className="mt-4 leading-8 text-muted-foreground">
              A good script can help creators stay focused, explain ideas
              clearly and maintain a logical structure throughout the video.
            </p>
          </div>

          {/* SCRIPT STRUCTURE */}
          <div>
            <h2 className="text-3xl font-black tracking-tight">
              <span className="text-red-400">Best YouTube Script</span>{" "}
              <span className="text-yellow-400">Structure</span>
            </h2>

            <p className="mt-4 leading-8 text-muted-foreground">
              A useful YouTube script can follow a simple structure:
            </p>

            <div className="mt-6 grid gap-4 sm:grid-cols-2">
              <div className="rounded-2xl border border-red-500/30 bg-red-500/5 p-5">
                <h3 className="font-bold text-red-400">
                  1. Powerful Hook
                </h3>
                <p className="mt-2 text-sm leading-7 text-muted-foreground">
                  Capture attention quickly and make viewers interested in
                  continuing the video.
                </p>
              </div>

              <div className="rounded-2xl border border-yellow-500/30 bg-yellow-500/5 p-5">
                <h3 className="font-bold text-yellow-400">
                  2. Introduction
                </h3>
                <p className="mt-2 text-sm leading-7 text-muted-foreground">
                  Introduce the topic and explain what viewers can expect.
                </p>
              </div>

              <div className="rounded-2xl border border-green-500/30 bg-green-500/5 p-5">
                <h3 className="font-bold text-green-400">
                  3. Main Content
                </h3>
                <p className="mt-2 text-sm leading-7 text-muted-foreground">
                  Explain the important points with examples and useful
                  information.
                </p>
              </div>

              <div className="rounded-2xl border border-blue-500/30 bg-blue-500/5 p-5">
                <h3 className="font-bold text-blue-400">
                  4. Conclusion & CTA
                </h3>
                <p className="mt-2 text-sm leading-7 text-muted-foreground">
                  Summarize the video and use a relevant call to action.
                </p>
              </div>
            </div>
          </div>

          {/* FEATURES */}
          <div>
            <h2 className="text-3xl font-black tracking-tight">
              <span className="text-green-400">AI Script Generator</span>{" "}
              <span className="text-blue-400">Features</span>
            </h2>

            <ul className="mt-6 grid gap-3 text-muted-foreground sm:grid-cols-2">
              <li>✓ AI-generated YouTube script drafts</li>
              <li>✓ Topic-based content generation</li>
              <li>✓ Structured video scripts</li>
              <li>✓ YouTube Shorts script support</li>
              <li>✓ Multiple content sections</li>
              <li>✓ Easy copy functionality</li>
              <li>✓ Regenerate scripts when needed</li>
              <li>✓ Free to use</li>
            </ul>
          </div>

          {/* TIPS */}
          <div>
            <h2 className="text-3xl font-black tracking-tight">
              <span className="text-red-400">Tips for Writing</span>{" "}
              <span className="text-yellow-400">Better YouTube Scripts</span>
            </h2>

            <ul className="mt-6 list-disc space-y-3 pl-6 text-muted-foreground">
              <li>Know who your target audience is.</li>
              <li>Start with a clear purpose for the video.</li>
              <li>Use a strong opening hook.</li>
              <li>Keep the structure easy to follow.</li>
              <li>Use examples where they make the topic clearer.</li>
              <li>Write in a natural speaking style.</li>
              <li>Avoid unnecessary repetition.</li>
              <li>Review AI-generated information before publishing.</li>
            </ul>
          </div>

          {/* INTERNAL TOOLS */}
          <div>
            <h2 className="text-3xl font-black tracking-tight">
              <span className="text-green-400">Improve Your YouTube</span>{" "}
              <span className="text-blue-400">Content Workflow</span>
            </h2>

            <p className="mt-4 leading-8 text-muted-foreground">
              A script is only one part of creating a YouTube video. You can
              use other TubeKit tools to improve different parts of your
              content workflow.
            </p>

            <div className="mt-6 grid gap-4 sm:grid-cols-2">

              <Link
                to="/tools/title-generator"
                className="group rounded-2xl border border-red-500/30 bg-red-500/5 p-5 transition hover:border-red-400"
              >
                <h3 className="font-bold text-red-400">
                  YouTube Title Generator →
                </h3>
                <p className="mt-2 text-sm text-muted-foreground">
                  Generate relevant YouTube title ideas for your video.
                </p>
              </Link>

              <Link
                to="/tools/description-generator"
                className="group rounded-2xl border border-yellow-500/30 bg-yellow-500/5 p-5 transition hover:border-yellow-400"
              >
                <h3 className="font-bold text-yellow-400">
                  YouTube Description Generator →
                </h3>
                <p className="mt-2 text-sm text-muted-foreground">
                  Create structured descriptions for your videos.
                </p>
              </Link>

              <Link
                to="/tools/hook-generator"
                className="group rounded-2xl border border-green-500/30 bg-green-500/5 p-5 transition hover:border-green-400"
              >
                <h3 className="font-bold text-green-400">
                  YouTube Hook Generator →
                </h3>
                <p className="mt-2 text-sm text-muted-foreground">
                  Create engaging opening hooks for your videos.
                </p>
              </Link>

              <Link
                to="/tools/outline-generator"
                className="group rounded-2xl border border-blue-500/30 bg-blue-500/5 p-5 transition hover:border-blue-400"
              >
                <h3 className="font-bold text-blue-400">
                  YouTube Outline Generator →
                </h3>
                <p className="mt-2 text-sm text-muted-foreground">
                  Build a clear structure before writing your full script.
                </p>
              </Link>

              <Link
                to="/tools/shorts-generator"
                className="group rounded-2xl border border-red-500/30 bg-red-500/5 p-5 transition hover:border-red-400"
              >
                <h3 className="font-bold text-red-400">
                  YouTube Shorts Generator →
                </h3>
                <p className="mt-2 text-sm text-muted-foreground">
                  Find content ideas for short-form YouTube videos.
                </p>
              </Link>

            </div>
          </div>

          {/* FAQ */}
          <div>
            <h2 className="text-3xl font-black tracking-tight">
              <span className="text-yellow-400">
                Frequently Asked Questions
              </span>{" "}
              <span className="text-blue-400">About YouTube Scripts</span>
            </h2>

            <div className="mt-7 space-y-6">

              {faqs.map((faq, index) => (
                <div
                  key={index}
                  className="rounded-2xl border border-white/10 bg-white/[0.02] p-5"
                >
                  <h3 className="text-lg font-bold text-white">
                    {faq.question}
                  </h3>

                  <p className="mt-2 leading-7 text-muted-foreground">
                    {faq.answer}
                  </p>
                </div>
              ))}

            </div>
          </div>

          {/* FINAL CTA */}
          <div className="rounded-3xl border border-blue-500/30 bg-blue-500/5 p-7">
            <h2 className="text-2xl font-black text-white">
              Create Your YouTube Script in Seconds
            </h2>

            <p className="mt-3 leading-7 text-muted-foreground">
              Enter your video topic above and let TubeKit generate a
              structured script draft. Review it, customize it and make it
              your own before recording.
            </p>

            <div className="mt-5 flex flex-wrap gap-3">

              <Link
                to="/tools/hook-generator"
                className="rounded-xl bg-red-500 px-5 py-3 font-semibold text-white transition hover:bg-red-400"
              >
                Generate Hooks
              </Link>

              <Link
                to="/tools/title-generator"
                className="rounded-xl bg-yellow-500 px-5 py-3 font-semibold text-black transition hover:bg-yellow-400"
              >
                Generate Titles
              </Link>

            </div>
          </div>

        </section>
      </ToolLayout>
    </>
  );
}

export default ScriptGenerator;