import { useEffect, useRef, useState } from "react";
import { Link } from "react-router-dom";

import api from "@/services/api";

import SEO from "@/components/common/SEO";
import ToolLayout from "@/components/tool-layout/ToolLayout";
import ToolHeader from "@/components/tool-layout/ToolHeader";
import ToolForm from "@/components/tool-layout/ToolForm";

function SectionHeading({ children, color = "blue" }) {
  const colors = {
    red: "border-red-500 bg-red-500/5 text-red-400",
    yellow: "border-yellow-400 bg-yellow-400/5 text-yellow-300",
    green: "border-green-500 bg-green-500/5 text-green-400",
    blue: "border-blue-500 bg-blue-500/5 text-blue-400",
  };

  return (
    <h2
      className={`border-l-4 rounded-r-xl px-5 py-3 text-2xl font-bold tracking-tight sm:text-3xl ${colors[color]}`}
    >
      {children}
    </h2>
  );
}

function ShadowbanDetector({ query = "" }) {
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState(null);
  const [lastFormData, setLastFormData] = useState(null);

  const autoGeneratedQuery = useRef("");

  /* =========================================================
     ANALYZE CHANNEL
     ========================================================= */

  const handleGenerate = async (formData) => {
    try {
      setLoading(true);
      setLastFormData(formData);
      setResult(null);

      const channel = String(formData?.topic || "").trim();

      if (!channel) {
        alert("Please enter a YouTube channel URL or handle.");
        return;
      }

      const response = await api.get("/youtube/shadowban", {
        params: {
          channel,
        },
      });

      if (response.data.success) {
        const data = response.data.data || {};

        setResult({
          channelId: data.channelId || "",
          channelTitle: data.channelTitle || "",
          channelUrl: data.channelUrl || channel,
          status: data.status || "Analysis Ready",
          score: data.score ?? null,
          message:
            data.message ||
            "Public YouTube visibility signals were analyzed.",
          checks: Array.isArray(data.checks)
            ? data.checks
            : [],
        });
      } else {
        alert(
          response.data.message ||
            "Failed to analyze YouTube channel"
        );
      }
    } catch (error) {
      console.error("SHADOWBAN DETECTOR ERROR:", error);
      console.error("RESPONSE:", error.response);
      console.error("REQUEST:", error.request);

      alert(
        error.response?.data?.message ||
          error.message ||
          "Failed to analyze YouTube channel"
      );

      setResult(null);
    } finally {
      setLoading(false);
    }
  };

  /* =========================================================
     HERO SEARCH -> AUTO ANALYZE
     ========================================================= */

  useEffect(() => {
    const value = query.trim();

    if (!value) return;
    if (autoGeneratedQuery.current === value) return;

    autoGeneratedQuery.current = value;

    handleGenerate({
      topic: value,
    });
  }, [query]);

  /* =========================================================
     FAQ
     ========================================================= */

  const faqs = [
    {
      question: "What is a YouTube Shadowban Detector?",
      answer:
        "A YouTube Shadowban Detector reviews publicly available channel and video visibility signals that may help identify discoverability issues.",
    },
    {
      question: "Can a shadowban be confirmed from public data?",
      answer:
        "Public data cannot guarantee a definitive platform-side enforcement diagnosis. The tool should be treated as a visibility and discoverability diagnostic.",
    },
    {
      question: "How do I check my YouTube channel?",
      answer:
        "Paste your YouTube channel URL or supported channel handle into TubeKit and click Analyze Channel.",
    },
    {
      question: "What signals can be checked?",
      answer:
        "The analyzer can review supported public channel, video, visibility, and discoverability signals returned by the YouTube service.",
    },
    {
      question: "Can I analyze another YouTube channel?",
      answer:
        "Yes. A supported public YouTube channel URL or handle can be supplied for analysis.",
    },
    {
      question: "Does the tool guarantee that my channel is shadowbanned?",
      answer:
        "No. A public-data analyzer cannot guarantee a platform-side shadowban diagnosis. It provides available visibility signals and analysis.",
    },
    {
      question: "Is the YouTube Shadowban Detector free?",
      answer:
        "TubeKit provides this creator analysis tool as a free tool.",
    },
    {
      question: "What should I do if visibility looks unusual?",
      answer:
        "Review your channel and video visibility, metadata, content restrictions, search presence, and available YouTube Studio information before drawing conclusions.",
    },
  ];

  const breadcrumbs = [
    {
      name: "Home",
      path: "/",
    },
    {
      name: "YouTube Shadowban Detector",
      path: "/tools/shadowban-detector",
    },
  ];

  return (
    <>
      <SEO
        title="YouTube Shadowban Detector - Check YouTube Visibility | TubeKit"
        description="Check public YouTube visibility and discoverability signals with TubeKit's YouTube Shadowban Detector. Analyze a channel URL or handle and review available signals."
        keywords="YouTube shadowban detector, YouTube shadowban checker, check YouTube shadowban, YouTube visibility checker, YouTube discoverability checker, YouTube channel checker, shadowban test"
        canonical="/tools/shadowban-detector"
        breadcrumbs={breadcrumbs}
        faqs={faqs}
      />

      <ToolLayout>
        <ToolHeader
          title="YouTube Shadowban Detector"
          description="Check public YouTube visibility and discoverability signals using a channel URL or handle."
        />

        <ToolForm
          onGenerate={handleGenerate}
          loading={loading}
          config={{
            buttonText: "Check Shadowban",
            topicLabel: "YouTube Channel URL or Handle",
            topicPlaceholder:
              "Paste YouTube channel URL or enter channel handle...",
            initialTopic: query,
          }}
        />


        {/* ===================================================
            ANALYSIS RESULT
            =================================================== */}

        {!loading && result && (
          <div className="mt-8 overflow-hidden rounded-2xl border border-slate-800 bg-black">
            <div className="border-b border-slate-800 px-5 py-4">
              <p className="text-sm font-medium text-blue-400">
                Channel Analysis
              </p>
            </div>

            <div className="p-5 sm:p-7">
              <div className="flex flex-col gap-5 sm:flex-row sm:items-center sm:justify-between">
                <div className="min-w-0">
                  <h2 className="text-2xl font-bold text-white">
                    {result.channelTitle || "YouTube Channel"}
                  </h2>

                  <p className="mt-2 text-sm text-slate-400">
                    Status:{" "}
                    <span className="font-semibold text-green-400">
                      {result.status}
                    </span>
                  </p>
                </div>

                {result.channelUrl && (
                  <a
                    href={result.channelUrl}
                    target="_blank"
                    rel="noreferrer"
                    className="shrink-0 rounded-xl border border-red-500/30 bg-red-500/5 px-4 py-2 text-sm font-semibold text-red-400 transition hover:border-red-400 hover:bg-red-500/10"
                  >
                    Open Channel
                  </a>
                )}
              </div>

              {result.score !== null && (
                <div className="mt-7 rounded-2xl border border-blue-500/20 bg-blue-500/5 p-6">
                  <p className="text-sm font-medium text-blue-400">
                    Visibility Score
                  </p>

                  <div className="mt-3 flex items-end gap-2">
                    <span className="text-4xl font-black text-white">
                      {result.score}
                    </span>
                    <span className="pb-1 text-sm text-slate-500">
                      / 100
                    </span>
                  </div>
                </div>
              )}

              {result.message && (
                <p className="mt-6 leading-7 text-slate-400">
                  {result.message}
                </p>
              )}

              {result.checks.length > 0 && (
                <div className="mt-7 grid gap-4 sm:grid-cols-2">
                  {result.checks.map((check, index) => (
                    <div
                      key={`${check}-${index}`}
                      className="rounded-xl border border-slate-800 bg-slate-950 p-5"
                    >
                      <p className="text-sm font-semibold text-white">
                        {typeof check === "string"
                          ? check
                          : check.label || "Visibility Signal"}
                      </p>

                      {typeof check !== "string" && check.value && (
                        <p className="mt-2 text-sm text-slate-400">
                          {check.value}
                        </p>
                      )}
                    </div>
                  ))}
                </div>
              )}
            </div>
          </div>
        )}

        {/* ===================================================
            IMPORTANT RESULT NOTE
            =================================================== */}

        {!loading && result && (
          <div className="mt-6 rounded-2xl border border-yellow-400/20 bg-yellow-400/5 p-6">
            <h2 className="text-xl font-bold text-white">
              Important Note
            </h2>

            <p className="mt-3 leading-7 text-slate-400">
              A public-data checker cannot prove a platform-side
              shadowban with certainty. Use the result as a
              visibility diagnostic and compare it with information
              available in YouTube Studio.
            </p>
          </div>
        )}

{/* ===================================================
            SEO CONTENT
            =================================================== */}

        <section className="mt-16 space-y-12">
          <div>
            <SectionHeading color="red">
              Free YouTube Shadowban Detector
            </SectionHeading>

            <p className="mt-5 leading-8 text-slate-300">
              TubeKit's YouTube Shadowban Detector is designed to
              review publicly available visibility and discoverability
              signals for a YouTube channel. Enter a supported
              channel URL or handle to start an analysis.
            </p>

            <p className="mt-4 leading-8 text-slate-300">
              The tool is intended as a diagnostic aid. Public data
              cannot independently confirm every platform-side
              enforcement or recommendation decision.
            </p>
          </div>

          <div>
            <SectionHeading color="yellow">
              How to Use the YouTube Shadowban Detector
            </SectionHeading>

            <p className="mt-5 leading-8 text-slate-300">
              Checking a channel's public visibility signals takes
              only a few steps:
            </p>

            <ol className="mt-5 list-decimal space-y-3 pl-6 leading-8 text-slate-300">
              <li>Copy your YouTube channel URL.</li>
              <li>Paste it into the detector.</li>
              <li>
                Click the{" "}
                <strong className="text-white">
                  Check Shadowban
                </strong>{" "}
                button.
              </li>
              <li>Review the available visibility signals.</li>
              <li>
                Compare the result with your own YouTube Studio
                information.
              </li>
            </ol>
          </div>

          <div>
            <SectionHeading color="green">
              What Does a YouTube Shadowban Mean?
            </SectionHeading>

            <p className="mt-5 leading-8 text-slate-300">
              The term "shadowban" is commonly used by creators to
              describe a situation where content appears to receive
              reduced visibility without an obvious explanation.
              However, a public-data tool cannot establish a
              definitive platform-side enforcement diagnosis from
              visibility metrics alone.
            </p>

            <p className="mt-4 leading-8 text-slate-300">
              Changes in search ranking, recommendations, audience
              behavior, content performance, restrictions, and other
              platform factors can affect discoverability.
            </p>
          </div>

          <div>
            <SectionHeading color="blue">
              Signals for YouTube Visibility Analysis
            </SectionHeading>

            <p className="mt-5 leading-8 text-slate-300">
              A useful visibility review can consider multiple public
              signals rather than relying on a single metric.
            </p>

            <div className="mt-6 grid gap-4 sm:grid-cols-2">
              <div className="rounded-xl border border-red-500/20 bg-red-500/5 p-5">
                <p className="font-semibold text-red-400">
                  Channel Visibility
                </p>
                <p className="mt-2 text-sm leading-6 text-slate-400">
                  Review whether the public channel information is
                  accessible and available.
                </p>
              </div>

              <div className="rounded-xl border border-yellow-400/20 bg-yellow-400/5 p-5">
                <p className="font-semibold text-yellow-300">
                  Video Availability
                </p>
                <p className="mt-2 text-sm leading-6 text-slate-400">
                  Review the availability of recent public videos.
                </p>
              </div>

              <div className="rounded-xl border border-green-500/20 bg-green-500/5 p-5">
                <p className="font-semibold text-green-400">
                  Search Discoverability
                </p>
                <p className="mt-2 text-sm leading-6 text-slate-400">
                  Consider available search and discoverability
                  signals.
                </p>
              </div>

              <div className="rounded-xl border border-blue-500/20 bg-blue-500/5 p-5">
                <p className="font-semibold text-blue-400">
                  Public Metadata
                </p>
                <p className="mt-2 text-sm leading-6 text-slate-400">
                  Review available public channel and video metadata.
                </p>
              </div>
            </div>
          </div>

          <div>
            <SectionHeading color="red">
              Why Use a YouTube Shadowban Detector?
            </SectionHeading>

            <ul className="mt-5 list-disc space-y-3 pl-6 leading-8 text-slate-300">
              <li>Review public channel visibility signals.</li>
              <li>Check discoverability-related information.</li>
              <li>Organize multiple public signals in one report.</li>
              <li>Use the analysis as part of a channel audit.</li>
              <li>Identify areas that may need deeper investigation.</li>
            </ul>
          </div>

          <div>
            <SectionHeading color="yellow">
              What to Check if Your YouTube Reach Changes
            </SectionHeading>

            <p className="mt-5 leading-8 text-slate-300">
              If you notice a change in reach, review your YouTube
              Studio analytics, traffic sources, audience behavior,
              video visibility, content restrictions, and recent
              publishing patterns. Comparing multiple videos can be
              more informative than relying on one performance
              metric.
            </p>

            <p className="mt-4 leading-8 text-slate-300">
              A sudden performance change does not by itself establish
              that a channel has been shadowbanned.
            </p>
          </div>

<div>
            <SectionHeading color="green">
              TubeKit YouTube Shadowban Detector Features
            </SectionHeading>

            <ul className="mt-6 grid gap-3 text-slate-300 sm:grid-cols-2">
              <li className="rounded-lg border border-red-500/20 bg-red-500/5 p-3">
                [OK] Analyze a YouTube channel URL
              </li>

              <li className="rounded-lg border border-yellow-400/20 bg-yellow-400/5 p-3">
                [OK] Analyze supported channel handles
              </li>

              <li className="rounded-lg border border-green-500/20 bg-green-500/5 p-3">
                [OK] Review public visibility signals
              </li>

              <li className="rounded-lg border border-blue-500/20 bg-blue-500/5 p-3">
                [OK] Review discoverability signals
              </li>

              <li className="rounded-lg border border-red-500/20 bg-red-500/5 p-3">
                [OK] Review public metadata
              </li>

              <li className="rounded-lg border border-yellow-400/20 bg-yellow-400/5 p-3">
                [OK] Structured analysis result
              </li>

              <li className="rounded-lg border border-green-500/20 bg-green-500/5 p-3">
                [OK] Mobile-friendly interface
              </li>

              <li className="rounded-lg border border-blue-500/20 bg-blue-500/5 p-3">
                [OK] Simple creator workflow
              </li>

              <li className="rounded-lg border border-red-500/20 bg-red-500/5 p-3">
                [OK] YouTube-focused analysis
              </li>

              <li className="rounded-lg border border-yellow-400/20 bg-yellow-400/5 p-3">
                [OK] Free to use
              </li>
            </ul>
          </div>

          <div>
            <SectionHeading color="blue">
              Important Notes About Shadowban Detection
            </SectionHeading>

            <p className="mt-5 leading-8 text-slate-300">
              There is no public metric that can independently prove
              a platform-side shadowban. The detector should therefore
              be used to review available public signals rather than
              as a definitive enforcement verdict.
            </p>

            <p className="mt-4 leading-8 text-slate-300">
              For account-specific restrictions or enforcement
              information, YouTube Studio and official platform
              notifications are the appropriate places to review your
              channel status.
            </p>
          </div>

          <div>
            <SectionHeading color="yellow">
              More Free YouTube Tools
            </SectionHeading>

            <p className="mt-5 leading-8 text-slate-300">
              Use TubeKit's other creator tools for tags, descriptions,
              titles, SEO, keywords, hashtags, thumbnails, and
              channel research.
            </p>

            <div className="mt-6 grid gap-4 sm:grid-cols-2">
              <Link
                to="/tools/tag-extractor"
                className="rounded-xl border border-red-500/20 bg-red-500/5 p-5 transition hover:border-red-400 hover:bg-red-500/10"
              >
                <span className="font-semibold text-red-400">
                  YouTube Tag Extractor
                </span>
                <p className="mt-2 text-sm text-slate-400">
                  Extract available video tags.
                </p>
              </Link>

              <Link
                to="/tools/description-extractor"
                className="rounded-xl border border-blue-500/20 bg-blue-500/5 p-5 transition hover:border-blue-400 hover:bg-blue-500/10"
              >
                <span className="font-semibold text-blue-400">
                  YouTube Description Extractor
                </span>
                <p className="mt-2 text-sm text-slate-400">
                  Extract available video descriptions.
                </p>
              </Link>

              <Link
                to="/tools/seo-analyzer"
                className="rounded-xl border border-green-500/20 bg-green-500/5 p-5 transition hover:border-green-400 hover:bg-green-500/10"
              >
                <span className="font-semibold text-green-400">
                  YouTube SEO Analyzer
                </span>
                <p className="mt-2 text-sm text-slate-400">
                  Analyze YouTube metadata and SEO signals.
                </p>
              </Link>

              <Link
                to="/tools/channel-analyzer"
                className="rounded-xl border border-yellow-400/20 bg-yellow-400/5 p-5 transition hover:border-yellow-300 hover:bg-yellow-400/10"
              >
                <span className="font-semibold text-yellow-300">
                  YouTube Channel Analyzer
                </span>
                <p className="mt-2 text-sm text-slate-400">
                  Review public channel information.
                </p>
              </Link>

              <Link
                to="/tools/title-generator"
                className="rounded-xl border border-red-500/20 bg-red-500/5 p-5 transition hover:border-red-400 hover:bg-red-500/10"
              >
                <span className="font-semibold text-red-400">
                  YouTube Title Generator
                </span>
                <p className="mt-2 text-sm text-slate-400">
                  Generate YouTube title ideas.
                </p>
              </Link>

              <Link
                to="/tools/keyword-generator"
                className="rounded-xl border border-green-500/20 bg-green-500/5 p-5 transition hover:border-green-400 hover:bg-green-500/10"
              >
                <span className="font-semibold text-green-400">
                  YouTube Keyword Generator
                </span>
                <p className="mt-2 text-sm text-slate-400">
                  Find keyword ideas for YouTube.
                </p>
              </Link>
            </div>
          </div>

          <div>
            <SectionHeading color="green">
              Learn More About YouTube SEO
            </SectionHeading>

            <div className="mt-6 grid gap-4 sm:grid-cols-2">
              <Link
                to="/blog/best-youtube-seo-tools-for-creators"
                className="rounded-xl border border-blue-500/20 bg-blue-500/5 p-5 transition hover:border-blue-400 hover:bg-blue-500/10"
              >
                <span className="font-semibold text-blue-400">
                  Best YouTube SEO Tools for Creators
                </span>
                <p className="mt-2 text-sm text-slate-400">
                  Explore useful YouTube SEO tools and workflows.
                </p>
              </Link>

              <Link
                to="/blog/how-to-write-youtube-titles-that-get-more-clicks"
                className="rounded-xl border border-green-500/20 bg-green-500/5 p-5 transition hover:border-green-400 hover:bg-green-500/10"
              >
                <span className="font-semibold text-green-400">
                  How to Write YouTube Titles That Get More Clicks
                </span>
                <p className="mt-2 text-sm text-slate-400">
                  Learn practical YouTube title techniques.
                </p>
              </Link>
            </div>
          </div>

          <div>
            <SectionHeading color="blue">
              Frequently Asked Questions
            </SectionHeading>

            <div className="mt-6 space-y-4">
              {faqs.map((faq, index) => {
                const colors = [
                  "border-red-500/20 bg-red-500/5",
                  "border-yellow-400/20 bg-yellow-400/5",
                  "border-green-500/20 bg-green-500/5",
                  "border-blue-500/20 bg-blue-500/5",
                ];

                return (
                  <div
                    key={faq.question}
                    className={`rounded-xl border p-5 ${
                      colors[index % 4]
                    }`}
                  >
                    <h3 className="text-lg font-semibold text-white">
                      {faq.question}
                    </h3>

                    <p className="mt-2 leading-7 text-slate-400">
                      {faq.answer}
                    </p>
                  </div>
                );
              })}
            </div>
          </div>
        </section>
      </ToolLayout>
    </>
  );
}

export default ShadowbanDetector;