import { useEffect, useRef, useState } from "react";
import { Link } from "react-router-dom";
import api from "@/services/api";

import SEO from "@/components/common/SEO";
import ToolLayout from "@/components/tool-layout/ToolLayout";
import ToolHeader from "@/components/tool-layout/ToolHeader";
import ToolForm from "@/components/tool-layout/ToolForm";
import ToolOutput from "@/components/tool-layout/ToolOutput";

/* =========================================================
   RGYB SECTION HEADING
   ========================================================= */

function SectionHeading({ children, color = "blue" }) {
  const colors = {
    red: "border-red-500 bg-red-500/5 text-red-400",
    yellow: "border-yellow-400 bg-yellow-400/5 text-yellow-300",
    green: "border-green-500 bg-green-500/5 text-green-400",
    blue: "border-blue-500 bg-blue-500/5 text-blue-400",
  };

  return (
    <h2
      className={`rounded-r-xl border-l-4 px-5 py-3 text-2xl font-bold tracking-tight sm:text-3xl ${colors[color]}`}
    >
      {children}
    </h2>
  );
}

function ShortsGenerator({ query = "" }) {
  const [loading, setLoading] = useState(false);
  const [results, setResults] = useState([]);
  const [lastFormData, setLastFormData] = useState(null);

  const autoGeneratedQuery = useRef("");

  /* =========================================================
     GENERATE SHORTS IDEAS
     ========================================================= */

  const handleGenerate = async (formData) => {
    try {
      setLoading(true);
      setLastFormData(formData);

      const response = await api.post("/generate", {
        tool: "shorts-generator",
        ...formData,
      });

      if (response.data.success) {
        const ideas = response.data.data
          .split("\n")
          .map((item) => item.trim())
          .filter(Boolean);

        setResults(ideas);
      } else {
        setResults([]);
      }
    } catch (error) {
      console.error("SHORTS GENERATOR ERROR:", error);
      console.error("RESPONSE:", error.response);
      console.error("REQUEST:", error.request);

      alert(
        error.response?.data?.message ||
          error.message ||
          "Failed to generate ideas"
      );

      setResults([]);
    } finally {
      setLoading(false);
    }
  };

  /* =========================================================
     HERO SEARCH → AUTO GENERATE
     ========================================================= */

  useEffect(() => {
    const value = query.trim();

    if (!value) return;

    if (autoGeneratedQuery.current === value) return;

    autoGeneratedQuery.current = value;

    handleGenerate({
      topic: value,
    });
  }, [query]);

  /* =========================================================
     COPY
     ========================================================= */

  const copyIdea = async (text) => {
    try {
      await navigator.clipboard.writeText(text);
      alert("Copied!");
    } catch (error) {
      console.error("COPY ERROR:", error);
    }
  };

  const copyAll = async () => {
    try {
      await navigator.clipboard.writeText(results.join("\n"));
      alert("All ideas copied!");
    } catch (error) {
      console.error("COPY ALL ERROR:", error);
    }
  };

  /* =========================================================
     FAQ DATA
     ========================================================= */

  const faqs = [
    {
      question: "What is a YouTube Shorts Generator?",
      answer:
        "A YouTube Shorts Generator is a tool that helps creators generate ideas and content concepts for short-form YouTube videos. TubeKit uses AI to generate Shorts ideas based on the topic you provide.",
    },
    {
      question: "Can AI generate YouTube Shorts ideas?",
      answer:
        "Yes. AI can generate YouTube Shorts ideas based on a topic, niche, or content theme. Creators should review and customize the generated ideas before publishing.",
    },
    {
      question: "How do I get ideas for YouTube Shorts?",
      answer:
        "You can generate ideas from your niche, audience questions, tutorials, facts, trends, stories, comparisons, tips, and other topics relevant to your viewers.",
    },
    {
      question: "How do I make YouTube Shorts more engaging?",
      answer:
        "Start with a clear and relevant hook, get to the main point quickly, keep the video focused on one idea, use clear language, and deliver useful or entertaining information.",
    },
    {
      question: "Can TubeKit generate viral YouTube Shorts ideas?",
      answer:
        "TubeKit can generate engaging Shorts concepts, but no tool can guarantee that a particular Short will go viral. Performance depends on many factors including the topic, execution, audience response, and viewer satisfaction.",
    },
    {
      question: "Can I edit the generated Shorts ideas?",
      answer:
        "Yes. AI-generated ideas are suggestions. You can modify them to match your audience, niche, personality, content style, and the information you want to present.",
    },
    {
      question: "Is TubeKit's YouTube Shorts Generator free?",
      answer:
        "Yes. TubeKit provides the YouTube Shorts Generator as a free tool for creators.",
    },
  ];

  return (
    <>
      {/* =====================================================
          SEO
          ===================================================== */}

      <SEO
        title="YouTube Shorts Generator – Free AI Shorts Ideas | TubeKit"
        description="Generate YouTube Shorts ideas with TubeKit's free AI YouTube Shorts Generator. Get engaging Shorts concepts, video ideas and content inspiration in seconds."
        keywords="YouTube Shorts generator, AI YouTube Shorts generator, YouTube Shorts ideas generator, YouTube Shorts ideas, Shorts ideas, viral Shorts ideas, YouTube short video ideas, free YouTube Shorts generator"
        canonical="/tools/shorts-generator"
        faqs={faqs}
        breadcrumbs={[
          {
            name: "Home",
            path: "/",
          },
          {
            name: "YouTube Shorts Generator",
            path: "/tools/shorts-generator",
          },
        ]}
      />

      <ToolLayout>
        {/* ===================================================
            HEADER
            =================================================== */}

        <ToolHeader
          title="AI YouTube Shorts Generator"
          description="Generate engaging YouTube Shorts ideas and short-form video concepts based on your topic."
        />

        {/* ===================================================
            TOOL FORM
            =================================================== */}

        <ToolForm
          onGenerate={handleGenerate}
          loading={loading}
          config={{
            buttonText: "Generate Shorts Ideas",
            topicLabel: "Shorts Topic",
            topicPlaceholder: "Example: AI Facts",
            initialTopic: query,
            showTone: false,
            showCount: false,
            showLanguage: false,
          }}
        />

        {/* ===================================================
            OUTPUT
            =================================================== */}

        <ToolOutput
          results={results}
          loading={loading}
          onCopy={copyIdea}
          onCopyAll={copyAll}
          onRegenerate={() => {
            if (lastFormData) {
              handleGenerate(lastFormData);
            }
          }}
        />

        {/* ===================================================
            SEO CONTENT
            =================================================== */}

        <section className="mt-16 space-y-12">

          {/* =================================================
              INTRODUCTION
              ================================================= */}

          <div>
            <SectionHeading color="red">
              Free YouTube Shorts Generator
            </SectionHeading>

            <p className="mt-5 leading-8 text-slate-300">
              Coming up with fresh YouTube Shorts ideas can be difficult,
              especially when you want to publish consistently. TubeKit's
              free YouTube Shorts Generator helps creators generate
              short-form video ideas based on a topic or niche.
            </p>

            <p className="mt-4 leading-8 text-slate-300">
              Enter your topic and the AI generates Shorts concepts that
              you can review, customize, and turn into your own videos.
              This can help reduce the time spent brainstorming new
              content ideas.
            </p>

            <p className="mt-4 leading-8 text-slate-300">
              The generated ideas are suggestions, not guaranteed viral
              formulas. The final performance of a Short depends on the
              topic, execution, audience response, and overall viewer
              experience.
            </p>
          </div>

          {/* =================================================
              HOW TO USE
              ================================================= */}

          <div>
            <SectionHeading color="yellow">
              How to Use the YouTube Shorts Generator
            </SectionHeading>

            <p className="mt-5 leading-8 text-slate-300">
              Generate YouTube Shorts ideas in a few simple steps:
            </p>

            <ol className="mt-5 list-decimal space-y-3 pl-6 leading-8 text-slate-300">
              <li>
                Enter the topic or niche you want to create a Short
                about.
              </li>

              <li>
                Click the{" "}
                <strong className="text-white">
                  Generate Shorts Ideas
                </strong>{" "}
                button.
              </li>

              <li>
                Review the generated Shorts concepts.
              </li>

              <li>
                Select an idea that fits your audience.
              </li>

              <li>
                Customize the concept before recording your video.
              </li>
            </ol>
          </div>

          {/* =================================================
              WHAT ARE SHORTS
              ================================================= */}

          <div>
            <SectionHeading color="green">
              What Are YouTube Shorts?
            </SectionHeading>

            <p className="mt-5 leading-8 text-slate-300">
              YouTube Shorts are short-form videos designed for quick,
              mobile-friendly viewing. Creators use Shorts for many types
              of content including tutorials, entertainment, education,
              facts, tips, stories, reviews, and behind-the-scenes
              content.
            </p>

            <p className="mt-4 leading-8 text-slate-300">
              Because short-form videos are consumed quickly, creators
              generally benefit from getting to the main topic without
              unnecessary delays.
            </p>
          </div>

          {/* =================================================
              SHORTS STRUCTURE
              ================================================= */}

          <div>
            <SectionHeading color="blue">
              How to Structure a YouTube Short
            </SectionHeading>

            <div className="mt-6 grid gap-4 sm:grid-cols-2">

              <div className="rounded-xl border border-red-500/20 bg-red-500/5 p-5">
                <h3 className="font-semibold text-red-400">
                  1. Strong Opening
                </h3>

                <p className="mt-2 text-sm leading-7 text-slate-400">
                  Start by clearly establishing the topic or giving the
                  viewer a reason to continue watching.
                </p>
              </div>

              <div className="rounded-xl border border-yellow-400/20 bg-yellow-400/5 p-5">
                <h3 className="font-semibold text-yellow-300">
                  2. Main Idea
                </h3>

                <p className="mt-2 text-sm leading-7 text-slate-400">
                  Deliver the main information quickly and keep the video
                  focused.
                </p>
              </div>

              <div className="rounded-xl border border-green-500/20 bg-green-500/5 p-5">
                <h3 className="font-semibold text-green-400">
                  3. Useful Content
                </h3>

                <p className="mt-2 text-sm leading-7 text-slate-400">
                  Give viewers information, entertainment, or value that
                  matches the promise of the opening.
                </p>
              </div>

              <div className="rounded-xl border border-blue-500/20 bg-blue-500/5 p-5">
                <h3 className="font-semibold text-blue-400">
                  4. Natural Ending
                </h3>

                <p className="mt-2 text-sm leading-7 text-slate-400">
                  Finish the idea clearly and use a relevant call to
                  action when appropriate.
                </p>
              </div>

            </div>
          </div>

          {/* =================================================
              SHORTS IDEAS
              ================================================= */}

          <div>
            <SectionHeading color="red">
              YouTube Shorts Ideas for Different Niches
            </SectionHeading>

            <p className="mt-5 leading-8 text-slate-300">
              The best Shorts ideas depend on your niche and audience.
              Here are some broad content formats you can adapt:
            </p>

            <ul className="mt-6 grid gap-3 sm:grid-cols-2">

              <li className="rounded-lg border border-red-500/20 bg-red-500/5 p-4 text-slate-300">
                ✓ Quick tutorials
              </li>

              <li className="rounded-lg border border-yellow-400/20 bg-yellow-400/5 p-4 text-slate-300">
                ✓ Interesting facts
              </li>

              <li className="rounded-lg border border-green-500/20 bg-green-500/5 p-4 text-slate-300">
                ✓ Tips and tricks
              </li>

              <li className="rounded-lg border border-blue-500/20 bg-blue-500/5 p-4 text-slate-300">
                ✓ Before and after concepts
              </li>

              <li className="rounded-lg border border-red-500/20 bg-red-500/5 p-4 text-slate-300">
                ✓ Common mistakes
              </li>

              <li className="rounded-lg border border-yellow-400/20 bg-yellow-400/5 p-4 text-slate-300">
                ✓ Comparisons
              </li>

              <li className="rounded-lg border border-green-500/20 bg-green-500/5 p-4 text-slate-300">
                ✓ Quick explanations
              </li>

              <li className="rounded-lg border border-blue-500/20 bg-blue-500/5 p-4 text-slate-300">
                ✓ Questions and answers
              </li>

            </ul>
          </div>

          {/* =================================================
              FEATURES
              ================================================= */}

          <div>
            <SectionHeading color="yellow">
              YouTube Shorts Generator Features
            </SectionHeading>

            <ul className="mt-6 grid gap-3 sm:grid-cols-2">

              <li className="rounded-lg border border-red-500/20 bg-red-500/5 p-4 text-slate-300">
                ✓ AI-generated Shorts ideas
              </li>

              <li className="rounded-lg border border-yellow-400/20 bg-yellow-400/5 p-4 text-slate-300">
                ✓ Topic-based suggestions
              </li>

              <li className="rounded-lg border border-green-500/20 bg-green-500/5 p-4 text-slate-300">
                ✓ Short-form content concepts
              </li>

              <li className="rounded-lg border border-blue-500/20 bg-blue-500/5 p-4 text-slate-300">
                ✓ Multiple ideas from one topic
              </li>

              <li className="rounded-lg border border-red-500/20 bg-red-500/5 p-4 text-slate-300">
                ✓ Copy individual ideas
              </li>

              <li className="rounded-lg border border-yellow-400/20 bg-yellow-400/5 p-4 text-slate-300">
                ✓ Copy all generated ideas
              </li>

              <li className="rounded-lg border border-green-500/20 bg-green-500/5 p-4 text-slate-300">
                ✓ Regenerate ideas
              </li>

              <li className="rounded-lg border border-blue-500/20 bg-blue-500/5 p-4 text-slate-300">
                ✓ Free to use
              </li>

            </ul>
          </div>

          {/* =================================================
              VIRAL SHORTS
              ================================================= */}

          <div>
            <SectionHeading color="green">
              How to Make YouTube Shorts More Engaging
            </SectionHeading>

            <p className="mt-5 leading-8 text-slate-300">
              There is no guaranteed formula for making a Short go viral.
              However, creators can improve the quality of their videos by
              focusing on the viewer experience.
            </p>

            <ul className="mt-6 list-disc space-y-3 pl-6 leading-8 text-slate-300">
              <li>
                Start with a clear and relevant opening.
              </li>

              <li>
                Get to the main point quickly.
              </li>

              <li>
                Keep the video focused on one primary idea.
              </li>

              <li>
                Use simple and easy-to-understand language.
              </li>

              <li>
                Remove unnecessary pauses and repetition.
              </li>

              <li>
                Make sure the title and content accurately represent
                the video.
              </li>

              <li>
                Give viewers a useful, entertaining, or interesting
                reason to watch.
              </li>
            </ul>

            <Link
              to="/blog/how-to-make-youtube-shorts-viral"
              className="mt-6 inline-flex rounded-xl border border-green-500/30 bg-green-500/5 px-5 py-3 font-semibold text-green-400 transition hover:border-green-400 hover:bg-green-500/10"
            >
              Read: How to Make YouTube Shorts Viral →
            </Link>
          </div>

          {/* =================================================
              HOOK
              ================================================= */}

          <div>
            <SectionHeading color="blue">
              Create Better Hooks for YouTube Shorts
            </SectionHeading>

            <p className="mt-5 leading-8 text-slate-300">
              The opening seconds of a Short are important because viewers
              can quickly move to other content. A good opening should
              clearly communicate what the video is about without making
              misleading promises.
            </p>

            <p className="mt-4 leading-8 text-slate-300">
              You can use TubeKit's AI Hook Generator to brainstorm
              different opening ideas for your Shorts.
            </p>

            <Link
              to="/tools/hook-generator"
              className="mt-6 inline-flex rounded-xl border border-blue-500/30 bg-blue-500/5 px-5 py-3 font-semibold text-blue-400 transition hover:border-blue-400 hover:bg-blue-500/10"
            >
              Try AI YouTube Hook Generator →
            </Link>
          </div>

          {/* =================================================
              SCRIPT
              ================================================= */}

          <div>
            <SectionHeading color="red">
              Turn Shorts Ideas Into Scripts
            </SectionHeading>

            <p className="mt-5 leading-8 text-slate-300">
              After selecting a Shorts idea, you can turn the concept into
              a structured script. A script can help you organize the
              opening, main information, and ending before recording.
            </p>

            <Link
              to="/tools/script-generator"
              className="mt-6 inline-flex rounded-xl border border-red-500/30 bg-red-500/5 px-5 py-3 font-semibold text-red-400 transition hover:border-red-400 hover:bg-red-500/10"
            >
              Try YouTube Script Generator →
            </Link>
          </div>

          {/* =================================================
              RELATED TOOLS
              ================================================= */}

          <div>
            <SectionHeading color="yellow">
              More Free YouTube Creator Tools
            </SectionHeading>

            <p className="mt-5 leading-8 text-slate-300">
              Planning Shorts involves more than finding an idea. You
              can use other TubeKit tools to work on hooks, titles,
              scripts, hashtags, and thumbnails.
            </p>

            <div className="mt-6 grid gap-4 sm:grid-cols-2">

              <Link
                to="/tools/title-generator"
                className="rounded-xl border border-red-500/20 bg-red-500/5 p-5 transition hover:border-red-400 hover:bg-red-500/10"
              >
                <span className="font-semibold text-red-400">
                  YouTube Title Generator →
                </span>

                <p className="mt-2 text-sm leading-7 text-slate-400">
                  Generate relevant title ideas for your videos.
                </p>
              </Link>

              <Link
                to="/tools/hashtag-generator"
                className="rounded-xl border border-yellow-400/20 bg-yellow-400/5 p-5 transition hover:border-yellow-300 hover:bg-yellow-400/10"
              >
                <span className="font-semibold text-yellow-300">
                  YouTube Hashtag Generator →
                </span>

                <p className="mt-2 text-sm leading-7 text-slate-400">
                  Generate relevant hashtag ideas for your content.
                </p>
              </Link>

              <Link
                to="/tools/thumbnail-generator"
                className="rounded-xl border border-green-500/20 bg-green-500/5 p-5 transition hover:border-green-400 hover:bg-green-500/10"
              >
                <span className="font-semibold text-green-400">
                  AI Thumbnail Generator →
                </span>

                <p className="mt-2 text-sm leading-7 text-slate-400">
                  Create thumbnail concepts for your YouTube content.
                </p>
              </Link>

              <Link
                to="/tools/outline-generator"
                className="rounded-xl border border-blue-500/20 bg-blue-500/5 p-5 transition hover:border-blue-400 hover:bg-blue-500/10"
              >
                <span className="font-semibold text-blue-400">
                  YouTube Outline Generator →
                </span>

                <p className="mt-2 text-sm leading-7 text-slate-400">
                  Build a structured outline before creating your video.
                </p>
              </Link>

            </div>
          </div>

          {/* =================================================
              BLOG LINKS
              ================================================= */}

          <div>
            <SectionHeading color="green">
              Learn More About YouTube Shorts
            </SectionHeading>

            <p className="mt-5 leading-8 text-slate-300">
              Explore more TubeKit guides for creating and improving
              YouTube content.
            </p>

            <div className="mt-6 grid gap-4">

              <Link
                to="/blog/youtube-shorts-ideas-for-beginners"
                className="rounded-xl border border-green-500/20 bg-green-500/5 p-5 transition hover:border-green-400 hover:bg-green-500/10"
              >
                <span className="font-semibold text-green-400">
                  YouTube Shorts Ideas for Beginners →
                </span>

                <p className="mt-2 text-sm leading-7 text-slate-400">
                  Explore practical Shorts ideas and short-form content
                  concepts.
                </p>
              </Link>

              <Link
                to="/blog/how-to-make-youtube-shorts-viral"
                className="rounded-xl border border-red-500/20 bg-red-500/5 p-5 transition hover:border-red-400 hover:bg-red-500/10"
              >
                <span className="font-semibold text-red-400">
                  How to Make YouTube Shorts Viral →
                </span>

                <p className="mt-2 text-sm leading-7 text-slate-400">
                  Learn practical ways to improve your Shorts content and
                  viewer engagement.
                </p>
              </Link>

              <Link
                to="/blog/how-to-get-more-views-on-youtube"
                className="rounded-xl border border-blue-500/20 bg-blue-500/5 p-5 transition hover:border-blue-400 hover:bg-blue-500/10"
              >
                <span className="font-semibold text-blue-400">
                  How to Get More Views on YouTube →
                </span>

                <p className="mt-2 text-sm leading-7 text-slate-400">
                  Explore practical strategies for improving YouTube
                  content and discoverability.
                </p>
              </Link>

            </div>
          </div>

          {/* =================================================
              FAQ
              ================================================= */}

          <div>
            <SectionHeading color="blue">
              Frequently Asked Questions
            </SectionHeading>

            <div className="mt-6 space-y-4">
              {faqs.map((faq, index) => {
                const colors = [
                  "border-red-500/20 bg-red-500/5",
                  "border-yellow-400/20 bg-yellow-400/5",
                  "border-green-500/20 bg-green-500/5",
                  "border-blue-500/20 bg-blue-500/5",
                ];

                return (
                  <div
                    key={faq.question}
                    className={`rounded-xl border p-5 ${colors[index % 4]}`}
                  >
                    <h3 className="text-lg font-semibold text-white">
                      {faq.question}
                    </h3>

                    <p className="mt-2 leading-7 text-slate-400">
                      {faq.answer}
                    </p>
                  </div>
                );
              })}
            </div>
          </div>

        </section>
      </ToolLayout>
    </>
  );
}

export default ShortsGenerator;