import { useEffect, useRef, useState } from "react";
import { Link } from "react-router-dom";

import api from "@/services/api";

import SEO from "@/components/common/SEO";
import ToolLayout from "@/components/tool-layout/ToolLayout";
import ToolHeader from "@/components/tool-layout/ToolHeader";
import ToolForm from "@/components/tool-layout/ToolForm";
import ToolOutput from "@/components/tool-layout/ToolOutput";

function SectionHeading({ children, color = "blue" }) {
  const colors = {
    red: "border-red-500 bg-red-500/5 text-red-400",
    yellow: "border-yellow-400 bg-yellow-400/5 text-yellow-300",
    green: "border-green-500 bg-green-500/5 text-green-400",
    blue: "border-blue-500 bg-blue-500/5 text-blue-400",
  };

  return (
    <h2
      className={`border-l-4 rounded-r-xl px-5 py-3 text-2xl font-bold tracking-tight sm:text-3xl ${colors[color]}`}
    >
      {children}
    </h2>
  );
}

function TagExtractor({ query = "" }) {
  const [loading, setLoading] = useState(false);
  const [results, setResults] = useState([]);
  const [lastFormData, setLastFormData] = useState(null);
  const autoGeneratedQuery = useRef("");

  const handleGenerate = async (formData) => {
    try {
      setLoading(true);
      setLastFormData(formData);

      const url = String(formData?.topic || "").trim();

      if (!url) {
        alert("Please enter a YouTube video URL.");
        setResults([]);
        return;
      }

      const response = await api.get("/youtube/tags", {
        params: { url },
      });

      if (response.data.success) {
        const tags = Array.isArray(response.data.data?.tags)
          ? response.data.data.tags
          : [];

        setResults(tags);
      } else {
        setResults([]);
        alert(response.data.message || "Failed to extract YouTube tags");
      }
    } catch (error) {
      console.error("TAG EXTRACTOR ERROR:", error);
      console.error("RESPONSE:", error.response);
      console.error("REQUEST:", error.request);

      alert(
        error.response?.data?.message ||
          error.message ||
          "Failed to extract YouTube tags"
      );

      setResults([]);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    const value = query.trim();

    if (!value) return;
    if (autoGeneratedQuery.current === value) return;

    autoGeneratedQuery.current = value;

    handleGenerate({ topic: value });
  }, [query]);

  const copyTag = async (text) => {
    try {
      await navigator.clipboard.writeText(text);
      alert("Copied!");
    } catch (error) {
      console.error("COPY ERROR:", error);
    }
  };

  const copyAll = async () => {
    try {
      await navigator.clipboard.writeText(results.join(", "));
      alert("All tags copied!");
    } catch (error) {
      console.error("COPY ALL ERROR:", error);
    }
  };

  const faqs = [
    {
      question: "What is a YouTube Tag Extractor?",
      answer:
        "A YouTube Tag Extractor retrieves available tags associated with a YouTube video.",
    },
    {
      question: "How do I extract tags from a YouTube video?",
      answer:
        "Paste a valid YouTube video URL into TubeKit and click Extract YouTube Tags.",
    },
    {
      question: "Which YouTube URL formats are supported?",
      answer:
        "TubeKit supports standard watch URLs, youtu.be URLs, Shorts URLs, embed URLs, live URLs, mobile URLs, www URLs, and URLs containing additional query parameters.",
    },
    {
      question: "Can I extract tags from YouTube Shorts?",
      answer:
        "Yes. A valid YouTube Shorts URL can be used to identify the video and retrieve available tags.",
    },
    {
      question: "Can I copy all extracted tags?",
      answer:
        "Yes. Use Copy All to copy the extracted tags as a comma-separated list.",
    },
    {
      question: "Are YouTube tags always available?",
      answer:
        "No. Some videos may not have available tags or may be inaccessible.",
    },
    {
      question: "Is the YouTube Tag Extractor free?",
      answer:
        "TubeKit provides this YouTube Tag Extractor as a free creator tool.",
    },
    {
      question: "Can extracted tags be used for research?",
      answer:
        "Yes. Extracted tags can be used as research references, but tags used on your own videos should accurately describe your content.",
    },
  ];

  const breadcrumbs = [
    { name: "Home", path: "/" },
    {
      name: "YouTube Tag Extractor",
      path: "/tools/tag-extractor",
    },
  ];

  return (
    <>
      <SEO
        title="YouTube Tag Extractor â€“ Extract YouTube Video Tags | TubeKit"
        description="Extract available tags from any YouTube video with TubeKit's free YouTube Tag Extractor. Supports videos, Shorts, shortened URLs, embed URLs, live URLs and more."
        keywords="YouTube tag extractor, YouTube tags extractor, extract YouTube tags, YouTube video tag extractor, YouTube tag finder, find YouTube tags, YouTube SEO tags, extract video tags, YouTube Shorts tags"
        canonical="/tools/tag-extractor"
        breadcrumbs={breadcrumbs}
        faqs={faqs}
      />

      <ToolLayout>
        <ToolHeader
          title="YouTube Tag Extractor"
          description="Extract available tags from YouTube videos quickly using a simple video URL."
        />

        <ToolForm
          onGenerate={handleGenerate}
          loading={loading}
          config={{
            buttonText: "Extract YouTube Tags",
            topicLabel: "YouTube Video URL",
            topicPlaceholder:
              "Paste YouTube video URL (watch, youtu.be, Shorts, embed, live)...",
            initialTopic: query,
          }}
        />

<ToolOutput
          results={results}
          loading={loading}
          onCopy={copyTag}
          onCopyAll={copyAll}
          onRegenerate={() => {
            if (lastFormData) {
              handleGenerate(lastFormData);
            }
          }}
        />

        <section className="mt-16 space-y-12">
          <div>
            <SectionHeading color="red">
              Free YouTube Tag Extractor
            </SectionHeading>

            <p className="mt-5 leading-8 text-slate-300">
              TubeKit's free YouTube Tag Extractor helps creators retrieve
              available tags associated with a YouTube video. Enter a
              YouTube video URL and the available tags are displayed in an
              easy-to-copy list.
            </p>

            <p className="mt-4 leading-8 text-slate-300">
              YouTube tags can be useful for content research and
              understanding keywords associated with a video.
            </p>
          </div>

          <div>
            <SectionHeading color="yellow">
              How to Use the YouTube Tag Extractor
            </SectionHeading>

            <p className="mt-5 leading-8 text-slate-300">
              Extracting available YouTube tags takes only a few steps:
            </p>

            <ol className="mt-5 list-decimal space-y-3 pl-6 leading-8 text-slate-300">
              <li>Copy the URL of the YouTube video.</li>
              <li>Paste the URL into the extractor.</li>
              <li>
                Click the <strong className="text-white">Extract YouTube Tags</strong>{" "}
                button.
              </li>
              <li>Review the available tags.</li>
              <li>Copy individual tags or use Copy All.</li>
            </ol>
          </div>

          <div>
            <SectionHeading color="green">
              Supported YouTube URL Formats
            </SectionHeading>

            <p className="mt-5 leading-8 text-slate-300">
              TubeKit supports common YouTube URL formats, including the
              following:
            </p>

            <div className="mt-6 grid gap-4 sm:grid-cols-2">
              <div className="rounded-xl border border-red-500/20 bg-red-500/5 p-5">
                <p className="font-semibold text-red-400">Standard Watch URL</p>
                <p className="mt-2 break-all text-sm text-slate-300">
                  https://www.youtube.com/watch?v=VIDEO_ID
                </p>
              </div>

              <div className="rounded-xl border border-yellow-400/20 bg-yellow-400/5 p-5">
                <p className="font-semibold text-yellow-300">Short URL</p>
                <p className="mt-2 break-all text-sm text-slate-300">
                  https://youtu.be/VIDEO_ID
                </p>
              </div>

              <div className="rounded-xl border border-green-500/20 bg-green-500/5 p-5">
                <p className="font-semibold text-green-400">Shorts URL</p>
                <p className="mt-2 break-all text-sm text-slate-300">
                  https://www.youtube.com/shorts/VIDEO_ID
                </p>
              </div>

              <div className="rounded-xl border border-blue-500/20 bg-blue-500/5 p-5">
                <p className="font-semibold text-blue-400">Embed URL</p>
                <p className="mt-2 break-all text-sm text-slate-300">
                  https://www.youtube.com/embed/VIDEO_ID
                </p>
              </div>

              <div className="rounded-xl border border-red-500/20 bg-red-500/5 p-5">
                <p className="font-semibold text-red-400">Live URL</p>
                <p className="mt-2 break-all text-sm text-slate-300">
                  https://www.youtube.com/live/VIDEO_ID
                </p>
              </div>

              <div className="rounded-xl border border-yellow-400/20 bg-yellow-400/5 p-5">
                <p className="font-semibold text-yellow-300">Mobile URL</p>
                <p className="mt-2 break-all text-sm text-slate-300">
                  https://m.youtube.com/watch?v=VIDEO_ID
                </p>
              </div>

              <div className="rounded-xl border border-green-500/20 bg-green-500/5 p-5">
                <p className="font-semibold text-green-400">WWW URL</p>
                <p className="mt-2 break-all text-sm text-slate-300">
                  https://www.youtube.com/watch?v=VIDEO_ID
                </p>
              </div>

              <div className="rounded-xl border border-blue-500/20 bg-blue-500/5 p-5">
                <p className="font-semibold text-blue-400">
                  URL With Extra Parameters
                </p>
                <p className="mt-2 break-all text-sm text-slate-300">
                  https://www.youtube.com/watch?v=VIDEO_ID&feature=share
                </p>
              </div>
            </div>
          </div>

          <div>
            <SectionHeading color="blue">
              What Is a YouTube Tag Extractor?
            </SectionHeading>

            <p className="mt-5 leading-8 text-slate-300">
              A YouTube Tag Extractor is a tool that retrieves available tags
              associated with a YouTube video. These tags can provide
              additional context about the topics and keywords associated
              with the video.
            </p>

            <p className="mt-4 leading-8 text-slate-300">
              Creators can use tag extraction as part of their content
              research and YouTube optimization workflow.
            </p>
          </div>

          <div>
            <SectionHeading color="red">
              Why Use a YouTube Tag Extractor?
            </SectionHeading>

            <ul className="mt-5 list-disc space-y-3 pl-6 leading-8 text-slate-300">
              <li>Quickly inspect available video tags.</li>
              <li>Research keywords used around similar content.</li>
              <li>Collect tags for content planning and analysis.</li>
              <li>Copy the complete tag list quickly.</li>
              <li>Analyze videos using multiple URL formats.</li>
            </ul>
          </div>

          <div>
            <SectionHeading color="yellow">
              How to Use Extracted Tags for YouTube Research
            </SectionHeading>

            <p className="mt-5 leading-8 text-slate-300">
              Extracted tags can be used as one source of information during
              YouTube content research. Compare tags across relevant videos
              to identify recurring topics and terminology.
            </p>

            <p className="mt-4 leading-8 text-slate-300">
              Do not automatically copy every extracted tag into your own
              video. Use keywords that genuinely describe your content.
            </p>
          </div>
<div>
            <SectionHeading color="green">
              TubeKit YouTube Tag Extractor Features
            </SectionHeading>

            <ul className="mt-6 grid gap-3 text-slate-300 sm:grid-cols-2">
              <li className="rounded-lg border border-red-500/20 bg-red-500/5 p-3">
                âœ“ Extract available YouTube video tags
              </li>
              <li className="rounded-lg border border-yellow-400/20 bg-yellow-400/5 p-3">
                âœ“ Supports standard YouTube URLs
              </li>
              <li className="rounded-lg border border-green-500/20 bg-green-500/5 p-3">
                âœ“ Supports youtu.be URLs
              </li>
              <li className="rounded-lg border border-blue-500/20 bg-blue-500/5 p-3">
                âœ“ Supports YouTube Shorts URLs
              </li>
              <li className="rounded-lg border border-red-500/20 bg-red-500/5 p-3">
                âœ“ Supports embed URLs
              </li>
              <li className="rounded-lg border border-yellow-400/20 bg-yellow-400/5 p-3">
                âœ“ Supports live URLs
              </li>
              <li className="rounded-lg border border-green-500/20 bg-green-500/5 p-3">
                âœ“ Copy individual tags
              </li>
              <li className="rounded-lg border border-blue-500/20 bg-blue-500/5 p-3">
                âœ“ Copy all extracted tags
              </li>
              <li className="rounded-lg border border-red-500/20 bg-red-500/5 p-3">
                âœ“ Regenerate or retry extraction
              </li>
              <li className="rounded-lg border border-yellow-400/20 bg-yellow-400/5 p-3">
                âœ“ Mobile-friendly interface
              </li>
              <li className="rounded-lg border border-green-500/20 bg-green-500/5 p-3">
                âœ“ Simple creator workflow
              </li>
              <li className="rounded-lg border border-blue-500/20 bg-blue-500/5 p-3">
                âœ“ Free to use
              </li>
            </ul>
          </div>

          <div>
            <SectionHeading color="blue">
              Important Notes About YouTube Tags
            </SectionHeading>

            <p className="mt-5 leading-8 text-slate-300">
              Not every YouTube video will necessarily return a list of tags.
              Availability depends on the video's available metadata and the
              data returned by the YouTube service.
            </p>

            <p className="mt-4 leading-8 text-slate-300">
              If a video is private, unavailable, deleted, invalid, or cannot
              be accessed, the extractor may not return tags.
            </p>
          </div>

          <div>
            <SectionHeading color="yellow">
              More Free YouTube Tools
            </SectionHeading>

            <p className="mt-5 leading-8 text-slate-300">
              Use TubeKit's other creator tools for titles, descriptions,
              keywords, hashtags, thumbnails, and scripts.
            </p>

            <div className="mt-6 grid gap-4 sm:grid-cols-2">
              <Link
                to="/tools/title-generator"
                className="group rounded-xl border border-red-500/20 bg-red-500/5 p-5 transition hover:border-red-400 hover:bg-red-500/10"
              >
                <span className="font-semibold text-red-400">
                  YouTube Title Generator
                </span>
                <p className="mt-2 text-sm text-slate-400">
                  Generate YouTube title ideas.
                </p>
              </Link>

              <Link
                to="/tools/description-generator"
                className="group rounded-xl border border-blue-500/20 bg-blue-500/5 p-5 transition hover:border-blue-400 hover:bg-blue-500/10"
              >
                <span className="font-semibold text-blue-400">
                  YouTube Description Generator
                </span>
                <p className="mt-2 text-sm text-slate-400">
                  Create YouTube description ideas.
                </p>
              </Link>

              <Link
                to="/tools/tags-generator"
                className="group rounded-xl border border-green-500/20 bg-green-500/5 p-5 transition hover:border-green-400 hover:bg-green-500/10"
              >
                <span className="font-semibold text-green-400">
                  YouTube Tags Generator
                </span>
                <p className="mt-2 text-sm text-slate-400">
                  Generate tag ideas for your own content.
                </p>
              </Link>

              <Link
                to="/tools/keyword-generator"
                className="group rounded-xl border border-yellow-400/20 bg-yellow-400/5 p-5 transition hover:border-yellow-300 hover:bg-yellow-400/10"
              >
                <span className="font-semibold text-yellow-300">
                  YouTube Keyword Generator
                </span>
                <p className="mt-2 text-sm text-slate-400">
                  Find keyword ideas for YouTube.
                </p>
              </Link>

              <Link
                to="/tools/thumbnail-generator"
                className="group rounded-xl border border-red-500/20 bg-red-500/5 p-5 transition hover:border-red-400 hover:bg-red-500/10"
              >
                <span className="font-semibold text-red-400">
                  YouTube Thumbnail Generator
                </span>
                <p className="mt-2 text-sm text-slate-400">
                  Generate thumbnail concepts.
                </p>
              </Link>

              <Link
                to="/tools/hashtag-generator"
                className="group rounded-xl border border-green-500/20 bg-green-500/5 p-5 transition hover:border-green-400 hover:bg-green-500/10"
              >
                <span className="font-semibold text-green-400">
                  YouTube Hashtag Generator
                </span>
                <p className="mt-2 text-sm text-slate-400">
                  Generate relevant YouTube hashtags.
                </p>
              </Link>
            </div>
          </div>
<div>
            <SectionHeading color="green">
              Learn More About YouTube SEO
            </SectionHeading>

            <div className="mt-6 grid gap-4 sm:grid-cols-2">
              <Link
                to="/blog/best-youtube-seo-tools-for-creators"
                className="rounded-xl border border-blue-500/20 bg-blue-500/5 p-5 transition hover:border-blue-400 hover:bg-blue-500/10"
              >
                <span className="font-semibold text-blue-400">
                  Best YouTube SEO Tools for Creators
                </span>
                <p className="mt-2 text-sm text-slate-400">
                  Explore useful YouTube SEO tools and workflows.
                </p>
              </Link>

              <Link
                to="/blog/how-to-write-youtube-titles-that-get-more-clicks"
                className="rounded-xl border border-green-500/20 bg-green-500/5 p-5 transition hover:border-green-400 hover:bg-green-500/10"
              >
                <span className="font-semibold text-green-400">
                  How to Write YouTube Titles That Get More Clicks
                </span>
                <p className="mt-2 text-sm text-slate-400">
                  Learn practical YouTube title techniques.
                </p>
              </Link>
            </div>
          </div>

          <div>
            <SectionHeading color="blue">
              Frequently Asked Questions
            </SectionHeading>

            <div className="mt-6 space-y-4">
              {faqs.map((faq, index) => {
                const colors = [
                  "border-red-500/20 bg-red-500/5",
                  "border-yellow-400/20 bg-yellow-400/5",
                  "border-green-500/20 bg-green-500/5",
                  "border-blue-500/20 bg-blue-500/5",
                ];

                return (
                  <div
                    key={faq.question}
                    className={`rounded-xl border p-5 ${colors[index % 4]}`}
                  >
                    <h3 className="text-lg font-semibold text-white">
                      {faq.question}
                    </h3>
                    <p className="mt-2 leading-7 text-slate-400">
                      {faq.answer}
                    </p>
                  </div>
                );
              })}
            </div>
          </div>
        </section>
      </ToolLayout>
    </>
  );
}

export default TagExtractor;