import { useEffect, useRef, useState } from "react";
import { Link } from "react-router-dom";

import api from "@/services/api";

import SEO from "@/components/common/SEO";
import ToolLayout from "@/components/tool-layout/ToolLayout";
import ToolHeader from "@/components/tool-layout/ToolHeader";
import ToolForm from "@/components/tool-layout/ToolForm";
import ToolOutput from "@/components/tool-layout/ToolOutput";

/* =========================================================
   RGYB SECTION HEADING
   ========================================================= */

function SectionHeading({ children, color = "blue" }) {
  const colors = {
    red: "border-red-500 bg-red-500/5 text-red-400",
    yellow: "border-yellow-400 bg-yellow-400/5 text-yellow-300",
    green: "border-green-500 bg-green-500/5 text-green-400",
    blue: "border-blue-500 bg-blue-500/5 text-blue-400",
  };

  return (
    <h2
      className={`rounded-r-xl border-l-4 px-5 py-3 text-2xl font-bold tracking-tight sm:text-3xl ${colors[color]}`}
    >
      {children}
    </h2>
  );
}

/* =========================================================
   TAGS GENERATOR
   ========================================================= */

function TagsGenerator({ query = "" }) {
  const [loading, setLoading] = useState(false);
  const [results, setResults] = useState([]);
  const [lastFormData, setLastFormData] = useState(null);

  const autoGeneratedQuery = useRef("");

  /* =========================================================
     GENERATE TAGS
     ========================================================= */

  const handleGenerate = async (formData) => {
    try {
      setLoading(true);
      setLastFormData(formData);

      const response = await api.post("/generate", {
        tool: "tags-generator",
        ...formData,
      });

      if (response.data.success) {
        const tags = response.data.data
          .split(",")
          .map((tag) => tag.trim())
          .filter(Boolean);

        setResults(tags);
      } else {
        setResults([]);
      }
    } catch (error) {
      console.error("TAGS GENERATOR ERROR:", error);
      console.error("RESPONSE:", error.response);
      console.error("REQUEST:", error.request);

      alert(
        error.response?.data?.message ||
          error.message ||
          "Failed to generate tags"
      );

      setResults([]);
    } finally {
      setLoading(false);
    }
  };

  /* =========================================================
     HERO SEARCH → AUTO GENERATE
     ========================================================= */

  useEffect(() => {
    const value = query.trim();

    if (!value) return;

    if (autoGeneratedQuery.current === value) return;

    autoGeneratedQuery.current = value;

    handleGenerate({
      topic: value,
    });
  }, [query]);

  /* =========================================================
     COPY
     ========================================================= */

  const copyTag = async (text) => {
    try {
      await navigator.clipboard.writeText(text);
      alert("Copied!");
    } catch (error) {
      console.error("COPY ERROR:", error);
    }
  };

  const copyAll = async () => {
    try {
      await navigator.clipboard.writeText(results.join(", "));
      alert("All tags copied!");
    } catch (error) {
      console.error("COPY ALL ERROR:", error);
    }
  };

  /* =========================================================
     FAQ
     ========================================================= */

  const faqs = [
    {
      question: "What is a YouTube Tags Generator?",
      answer:
        "A YouTube Tags Generator creates relevant tag ideas based on the topic of a YouTube video. TubeKit uses AI to generate keyword variations that can help describe the subject of your content.",
    },
    {
      question: "Do YouTube tags help videos rank?",
      answer:
        "YouTube tags can provide additional context about a video's content, but they are only one part of YouTube's discovery system. Relevance, content quality, viewer satisfaction, titles, thumbnails, and other signals also matter.",
    },
    {
      question: "How many YouTube tags should I use?",
      answer:
        "There is no universal number of tags that works for every video. Use relevant tags that accurately describe your content instead of adding unrelated keywords.",
    },
    {
      question: "What are the best tags for YouTube videos?",
      answer:
        "The best tags are closely related to the actual topic of your video. They can include your main topic, specific phrases, relevant variations, and terms that accurately describe the content.",
    },
    {
      question: "Can AI generate YouTube tags?",
      answer:
        "Yes. AI can generate tag ideas from a video topic. The suggestions should still be reviewed by the creator to make sure they accurately describe the video.",
    },
    {
      question: "Should YouTube tags match the video topic?",
      answer:
        "Yes. YouTube tags should be relevant to the actual subject of the video. Avoid misleading or unrelated tags.",
    },
    {
      question: "Is TubeKit's YouTube Tags Generator free?",
      answer:
        "Yes. TubeKit provides the AI YouTube Tags Generator as a free tool for creators.",
    },
  ];

  return (
    <>
      {/* =====================================================
          SEO
          ===================================================== */}

      <SEO
        title="YouTube Tags Generator – Free AI Tags Generator | TubeKit"
        description="Generate relevant YouTube tags with TubeKit's free AI YouTube Tags Generator. Get keyword variations and tag ideas for your videos in seconds."
        keywords="YouTube tags generator, AI YouTube tags generator, YouTube tag generator, free YouTube tags generator, YouTube SEO tags, YouTube tags, video tags generator, YouTube keyword tags, tags for YouTube videos"
        canonical="/tools/tags-generator"
        faqs={faqs}
        breadcrumbs={[
          {
            name: "Home",
            path: "/",
          },
          {
            name: "YouTube Tags Generator",
            path: "/tools/tags-generator",
          },
        ]}
      />

      <ToolLayout>
        {/* ===================================================
            HEADER
            =================================================== */}

        <ToolHeader
          title="AI YouTube Tags Generator"
          description="Generate relevant YouTube tags and keyword variations based on your video topic."
        />

        {/* ===================================================
            TOOL FORM
            =================================================== */}

        <ToolForm
          onGenerate={handleGenerate}
          loading={loading}
          config={{
            buttonText: "Generate YouTube Tags",
            topicLabel: "Video Topic",
            topicPlaceholder: "Example: React JS Tutorial",
            initialTopic: query,
            showCount: false,
            showTone: false,
            showLanguage: false,
          }}
        />

        {/* ===================================================
            OUTPUT
            =================================================== */}

        <ToolOutput
          results={results}
          loading={loading}
          onCopy={copyTag}
          onCopyAll={copyAll}
          onRegenerate={() => {
            if (lastFormData) {
              handleGenerate(lastFormData);
            }
          }}
        />

        {/* ===================================================
            SEO CONTENT
            =================================================== */}

        <section className="mt-16 space-y-12">

          {/* =================================================
              INTRODUCTION
              ================================================= */}

          <div>
            <SectionHeading color="red">
              Free YouTube Tags Generator
            </SectionHeading>

            <p className="mt-5 leading-8 text-slate-300">
              TubeKit's free YouTube Tags Generator helps creators
              generate relevant tag ideas based on the topic of their
              video. Instead of manually brainstorming dozens of
              keyword variations, you can enter your topic and generate
              tag suggestions in seconds.
            </p>

            <p className="mt-4 leading-8 text-slate-300">
              YouTube tags can provide additional context about your
              video. However, tags are only one part of YouTube's overall
              discovery system. Your tags should always accurately
              describe the content of the video.
            </p>

            <p className="mt-4 leading-8 text-slate-300">
              TubeKit's AI YouTube Tags Generator is designed to make
              the tag research and brainstorming process faster and
              easier for creators.
            </p>
          </div>

          {/* =================================================
              HOW TO USE
              ================================================= */}

          <div>
            <SectionHeading color="yellow">
              How to Use the YouTube Tags Generator
            </SectionHeading>

            <p className="mt-5 leading-8 text-slate-300">
              Generate YouTube tags with these simple steps:
            </p>

            <ol className="mt-5 list-decimal space-y-3 pl-6 leading-8 text-slate-300">
              <li>
                Enter the main topic of your YouTube video.
              </li>

              <li>
                Click the{" "}
                <strong className="text-white">
                  Generate YouTube Tags
                </strong>{" "}
                button.
              </li>

              <li>
                Review the generated tag suggestions.
              </li>

              <li>
                Remove tags that are unrelated to your video.
              </li>

              <li>
                Copy the relevant tags.
              </li>

              <li>
                Use only tags that accurately describe your content.
              </li>
            </ol>
          </div>

          {/* =================================================
              WHAT ARE TAGS
              ================================================= */}

          <div>
            <SectionHeading color="green">
              What Are YouTube Tags?
            </SectionHeading>

            <p className="mt-5 leading-8 text-slate-300">
              YouTube tags are words or phrases that can describe the
              topic and subject of a video. They can provide additional
              context about the content, especially when there are
              common spelling variations or closely related terms.
            </p>

            <p className="mt-4 leading-8 text-slate-300">
              For example, a video about React could potentially use
              relevant phrases such as "React JS tutorial", "React
              tutorial", "learn React", or other terms that genuinely
              describe the video's content.
            </p>

            <p className="mt-4 leading-8 text-slate-300">
              The important point is relevance. Adding unrelated popular
              keywords does not make a tag useful.
            </p>
          </div>

          {/* =================================================
              TAG TYPES
              ================================================= */}

          <div>
            <SectionHeading color="blue">
              Types of YouTube Tags You Can Generate
            </SectionHeading>

            <div className="mt-6 grid gap-4 sm:grid-cols-2">

              <div className="rounded-xl border border-red-500/20 bg-red-500/5 p-5">
                <h3 className="font-semibold text-red-400">
                  Main Topic Tags
                </h3>

                <p className="mt-2 text-sm leading-7 text-slate-400">
                  Directly describe the primary subject of your video.
                </p>
              </div>

              <div className="rounded-xl border border-yellow-400/20 bg-yellow-400/5 p-5">
                <h3 className="font-semibold text-yellow-300">
                  Keyword Variations
                </h3>

                <p className="mt-2 text-sm leading-7 text-slate-400">
                  Include relevant variations of the main topic and
                  related phrases.
                </p>
              </div>

              <div className="rounded-xl border border-green-500/20 bg-green-500/5 p-5">
                <h3 className="font-semibold text-green-400">
                  Specific Tags
                </h3>

                <p className="mt-2 text-sm leading-7 text-slate-400">
                  Describe a particular subject, feature, method, or
                  concept covered in the video.
                </p>
              </div>

              <div className="rounded-xl border border-blue-500/20 bg-blue-500/5 p-5">
                <h3 className="font-semibold text-blue-400">
                  Long-Tail Phrases
                </h3>

                <p className="mt-2 text-sm leading-7 text-slate-400">
                  More specific phrases that closely match the video's
                  actual topic.
                </p>
              </div>

            </div>
          </div>

          {/* =================================================
              FEATURES
              ================================================= */}

          <div>
            <SectionHeading color="red">
              YouTube Tags Generator Features
            </SectionHeading>

            <ul className="mt-6 grid gap-3 sm:grid-cols-2">

              <li className="rounded-lg border border-red-500/20 bg-red-500/5 p-4 text-slate-300">
                ✓ AI-generated YouTube tag suggestions
              </li>

              <li className="rounded-lg border border-yellow-400/20 bg-yellow-400/5 p-4 text-slate-300">
                ✓ Topic-based tag generation
              </li>

              <li className="rounded-lg border border-green-500/20 bg-green-500/5 p-4 text-slate-300">
                ✓ Relevant keyword variations
              </li>

              <li className="rounded-lg border border-blue-500/20 bg-blue-500/5 p-4 text-slate-300">
                ✓ Multiple tag ideas
              </li>

              <li className="rounded-lg border border-red-500/20 bg-red-500/5 p-4 text-slate-300">
                ✓ One-click copy
              </li>

              <li className="rounded-lg border border-yellow-400/20 bg-yellow-400/5 p-4 text-slate-300">
                ✓ Copy all generated tags
              </li>

              <li className="rounded-lg border border-green-500/20 bg-green-500/5 p-4 text-slate-300">
                ✓ Regenerate suggestions
              </li>

              <li className="rounded-lg border border-blue-500/20 bg-blue-500/5 p-4 text-slate-300">
                ✓ Free to use
              </li>

            </ul>
          </div>

          {/* =================================================
              BETTER TAGS
              ================================================= */}

          <div>
            <SectionHeading color="yellow">
              How to Choose Better YouTube Tags
            </SectionHeading>

            <p className="mt-5 leading-8 text-slate-300">
              AI-generated tags should be treated as suggestions rather
              than a list that must be used completely. Review every tag
              and keep only the terms that accurately describe your
              video.
            </p>

            <ul className="mt-6 list-disc space-y-3 pl-6 leading-8 text-slate-300">
              <li>
                Choose tags that accurately describe your video.
              </li>

              <li>
                Include relevant variations of your main topic.
              </li>

              <li>
                Use specific phrases when they match the content.
              </li>

              <li>
                Consider relevant long-tail keyword phrases.
              </li>

              <li>
                Remove unrelated or misleading tags.
              </li>

              <li>
                Do not add keywords only because they appear popular.
              </li>

              <li>
                Keep your metadata consistent with the actual video.
              </li>
            </ul>
          </div>

          {/* =================================================
              TAGS VS KEYWORDS
              ================================================= */}

          <div>
            <SectionHeading color="green">
              YouTube Tags vs YouTube Keywords
            </SectionHeading>

            <p className="mt-5 leading-8 text-slate-300">
              YouTube tags and keywords are related, but they are not
              exactly the same thing.
            </p>

            <p className="mt-4 leading-8 text-slate-300">
              A keyword is a search term or phrase that represents a
              topic people may search for. A tag is metadata associated
              with a video that can provide additional context about its
              content.
            </p>

            <p className="mt-4 leading-8 text-slate-300">
              Good keyword research can therefore help you understand
              the language your audience uses, while relevant tags can
              provide additional context for the video.
            </p>

            <Link
              to="/tools/keyword-generator"
              className="mt-6 inline-flex rounded-xl border border-green-500/30 bg-green-500/5 px-5 py-3 font-semibold text-green-400 transition hover:border-green-400 hover:bg-green-500/10"
            >
              Try YouTube Keyword Generator →
            </Link>
          </div>

          {/* =================================================
              TAGS AND TITLE
              ================================================= */}

          <div>
            <SectionHeading color="blue">
              YouTube Tags, Titles and Descriptions
            </SectionHeading>

            <p className="mt-5 leading-8 text-slate-300">
              Your video's metadata should communicate a consistent
              topic. Your title, description, and tags should accurately
              represent what the viewer will find in the video.
            </p>

            <p className="mt-4 leading-8 text-slate-300">
              Instead of repeating the same keyword excessively, focus
              on clear language and accurate descriptions of the
              content.
            </p>

            <div className="mt-6 grid gap-4 sm:grid-cols-2">

              <Link
                to="/tools/title-generator"
                className="rounded-xl border border-red-500/20 bg-red-500/5 p-5 transition hover:border-red-400 hover:bg-red-500/10"
              >
                <span className="font-semibold text-red-400">
                  YouTube Title Generator →
                </span>

                <p className="mt-2 text-sm leading-7 text-slate-400">
                  Generate relevant and engaging YouTube title ideas.
                </p>
              </Link>

              <Link
                to="/tools/description-generator"
                className="rounded-xl border border-yellow-400/20 bg-yellow-400/5 p-5 transition hover:border-yellow-300 hover:bg-yellow-400/10"
              >
                <span className="font-semibold text-yellow-300">
                  YouTube Description Generator →
                </span>

                <p className="mt-2 text-sm leading-7 text-slate-400">
                  Create useful descriptions for your YouTube videos.
                </p>
              </Link>

            </div>
          </div>

          {/* =================================================
              TAG EXAMPLES
              ================================================= */}

          <div>
            <SectionHeading color="red">
              YouTube Tags Example
            </SectionHeading>

            <p className="mt-5 leading-8 text-slate-300">
              Suppose your video topic is:
            </p>

            <div className="mt-4 rounded-xl border border-red-500/20 bg-red-500/5 p-5">
              <p className="font-semibold text-red-400">
                "How to Learn React JS for Beginners"
              </p>
            </div>

            <p className="mt-5 leading-8 text-slate-300">
              Relevant tag ideas could include phrases such as:
            </p>

            <div className="mt-5 rounded-xl border border-blue-500/20 bg-blue-500/5 p-5">
              <p className="leading-8 text-slate-300">
                React JS tutorial, React tutorial for beginners, learn
                React JS, React JS beginners, React development, React
                course, JavaScript React tutorial
              </p>
            </div>

            <p className="mt-4 leading-8 text-slate-400">
              The exact tags should always depend on the actual content
              of your video.
            </p>
          </div>

          {/* =================================================
              MORE TOOLS
              ================================================= */}

          <div>
            <SectionHeading color="yellow">
              More Free YouTube SEO Tools
            </SectionHeading>

            <p className="mt-5 leading-8 text-slate-300">
              Tags are only one part of YouTube content optimization.
              TubeKit provides additional tools that can help with
              titles, descriptions, keywords, thumbnails, scripts, and
              hashtags.
            </p>

            <div className="mt-6 grid gap-4 sm:grid-cols-2">

              <Link
                to="/tools/keyword-generator"
                className="rounded-xl border border-yellow-400/20 bg-yellow-400/5 p-5 transition hover:border-yellow-300 hover:bg-yellow-400/10"
              >
                <span className="font-semibold text-yellow-300">
                  YouTube Keyword Generator →
                </span>

                <p className="mt-2 text-sm text-slate-400">
                  Generate keyword ideas for your YouTube content.
                </p>
              </Link>

              <Link
                to="/tools/hashtag-generator"
                className="rounded-xl border border-green-500/20 bg-green-500/5 p-5 transition hover:border-green-400 hover:bg-green-500/10"
              >
                <span className="font-semibold text-green-400">
                  YouTube Hashtag Generator →
                </span>

                <p className="mt-2 text-sm text-slate-400">
                  Generate relevant YouTube hashtag ideas.
                </p>
              </Link>

              <Link
                to="/tools/thumbnail-generator"
                className="rounded-xl border border-blue-500/20 bg-blue-500/5 p-5 transition hover:border-blue-400 hover:bg-blue-500/10"
              >
                <span className="font-semibold text-blue-400">
                  AI Thumbnail Generator →
                </span>

                <p className="mt-2 text-sm text-slate-400">
                  Generate creative thumbnail concepts for your videos.
                </p>
              </Link>

              <Link
                to="/tools/script-generator"
                className="rounded-xl border border-red-500/20 bg-red-500/5 p-5 transition hover:border-red-400 hover:bg-red-500/10"
              >
                <span className="font-semibold text-red-400">
                  YouTube Script Generator →
                </span>

                <p className="mt-2 text-sm text-slate-400">
                  Generate structured scripts for YouTube videos.
                </p>
              </Link>

            </div>
          </div>

          {/* =================================================
              BLOG INTERNAL LINKS
              ================================================= */}

          <div>
            <SectionHeading color="green">
              Learn More About YouTube SEO
            </SectionHeading>

            <p className="mt-5 leading-8 text-slate-300">
              Continue learning about YouTube SEO and content
              optimization with TubeKit's creator guides.
            </p>

            <div className="mt-6 grid gap-4">

              <Link
                to="/blog/how-to-find-youtube-keywords"
                className="rounded-xl border border-green-500/20 bg-green-500/5 p-5 transition hover:border-green-400 hover:bg-green-500/10"
              >
                <span className="font-semibold text-green-400">
                  How to Find YouTube Keywords for Your Videos →
                </span>

                <p className="mt-2 text-sm leading-7 text-slate-400">
                  Learn how to find relevant keywords and use them
                  naturally in your YouTube content.
                </p>
              </Link>

              <Link
                to="/blog/how-to-write-youtube-description-for-seo"
                className="rounded-xl border border-yellow-400/20 bg-yellow-400/5 p-5 transition hover:border-yellow-300 hover:bg-yellow-400/10"
              >
                <span className="font-semibold text-yellow-300">
                  How to Write a YouTube Description for SEO →
                </span>

                <p className="mt-2 text-sm leading-7 text-slate-400">
                  Learn how to create useful YouTube descriptions that
                  support your overall content strategy.
                </p>
              </Link>

              <Link
                to="/blog/best-youtube-seo-tools-for-creators"
                className="rounded-xl border border-blue-500/20 bg-blue-500/5 p-5 transition hover:border-blue-400 hover:bg-blue-500/10"
              >
                <span className="font-semibold text-blue-400">
                  Best YouTube SEO Tools for Creators →
                </span>

                <p className="mt-2 text-sm leading-7 text-slate-400">
                  Explore useful tools for titles, keywords, tags,
                  scripts, and content planning.
                </p>
              </Link>

            </div>
          </div>

          {/* =================================================
              FAQ
              ================================================= */}

          <div>
            <SectionHeading color="blue">
              Frequently Asked Questions
            </SectionHeading>

            <div className="mt-6 space-y-4">
              {faqs.map((faq, index) => {
                const colors = [
                  "border-red-500/20 bg-red-500/5",
                  "border-yellow-400/20 bg-yellow-400/5",
                  "border-green-500/20 bg-green-500/5",
                  "border-blue-500/20 bg-blue-500/5",
                ];

                return (
                  <div
                    key={faq.question}
                    className={`rounded-xl border p-5 ${colors[index % 4]}`}
                  >
                    <h3 className="text-lg font-semibold text-white">
                      {faq.question}
                    </h3>

                    <p className="mt-2 leading-7 text-slate-400">
                      {faq.answer}
                    </p>
                  </div>
                );
              })}
            </div>
          </div>

        </section>
      </ToolLayout>
    </>
  );
}

export default TagsGenerator;