import { useEffect, useRef, useState } from "react";
import { Link } from "react-router-dom";

import api from "@/services/api";

import SEO from "@/components/common/SEO";
import ToolLayout from "@/components/tool-layout/ToolLayout";
import ToolHeader from "@/components/tool-layout/ToolHeader";
import ToolForm from "@/components/tool-layout/ToolForm";
import ToolOutput from "@/components/tool-layout/ToolOutput";

/* =========================================================
   RGYB SECTION HEADING
   ========================================================= */

function SectionHeading({ children, color = "blue" }) {
  const colors = {
    red: "border-red-500 bg-red-500/5 text-red-400",
    yellow: "border-yellow-400 bg-yellow-400/5 text-yellow-300",
    green: "border-green-500 bg-green-500/5 text-green-400",
    blue: "border-blue-500 bg-blue-500/5 text-blue-400",
  };

  return (
    <h2
      className={`rounded-r-xl border-l-4 px-5 py-3 text-2xl font-bold tracking-tight sm:text-3xl ${colors[color]}`}
    >
      {children}
    </h2>
  );
}

/* =========================================================
   THUMBNAIL GENERATOR
   ========================================================= */

function ThumbnailGenerator({ query = "" }) {
  const [loading, setLoading] = useState(false);
  const [results, setResults] = useState([]);
  const [lastFormData, setLastFormData] = useState(null);

  // Prevent duplicate Hero Search request
  const autoGeneratedQuery = useRef("");

  /* =========================================================
     GENERATE
     ========================================================= */

  const handleGenerate = async (formData) => {
    try {
      setLoading(true);
      setLastFormData(formData);

      const response = await api.post("/generate", {
        tool: "thumbnail-generator",
        ...formData,
      });

      if (response.data.success) {
        const ideas = response.data.data
          .split("\n")
          .map((item) => item.trim())
          .filter(Boolean);

        setResults(ideas);
      } else {
        setResults([]);
      }
    } catch (error) {
      console.error("THUMBNAIL GENERATOR ERROR:", error);
      console.error("RESPONSE:", error.response);
      console.error("REQUEST:", error.request);

      alert(
        error.response?.data?.message ||
          error.message ||
          "Failed to generate thumbnail ideas"
      );

      setResults([]);
    } finally {
      setLoading(false);
    }
  };

  /* =========================================================
     HERO SEARCH → AUTO GENERATE
     ========================================================= */

  useEffect(() => {
    const value = query.trim();

    if (!value) return;

    if (autoGeneratedQuery.current === value) return;

    autoGeneratedQuery.current = value;

    handleGenerate({
      topic: value,
      language: "English",
      tone: "Professional",
    });
  }, [query]);

  /* =========================================================
     COPY
     ========================================================= */

  const copyIdea = async (text) => {
    try {
      await navigator.clipboard.writeText(text);
      alert("Copied!");
    } catch (error) {
      console.error("COPY ERROR:", error);
    }
  };

  const copyAll = async () => {
    try {
      await navigator.clipboard.writeText(results.join("\n"));
      alert("All thumbnail ideas copied!");
    } catch (error) {
      console.error("COPY ALL ERROR:", error);
    }
  };

  /* =========================================================
     FAQ
     ========================================================= */

  const faqs = [
    {
      question: "What is an AI YouTube thumbnail generator?",
      answer:
        "An AI YouTube thumbnail generator creates thumbnail concepts and visual ideas based on the topic of your video. TubeKit helps creators brainstorm thumbnail concepts, text ideas, visual elements, and compositions.",
    },
    {
      question: "How do I create a good YouTube thumbnail?",
      answer:
        "Use a clear subject, strong visual hierarchy, readable elements, and a design that accurately represents the video. Avoid overcrowding the thumbnail with too many elements.",
    },
    {
      question: "Can AI create YouTube thumbnail ideas?",
      answer:
        "Yes. AI can generate thumbnail concepts based on a video's topic. The generated ideas can then be adapted to your channel's visual style and the actual content of your video.",
    },
    {
      question: "Can I use the TubeKit thumbnail generator for YouTube Shorts?",
      answer:
        "Yes. You can enter a YouTube Shorts topic and use the generated concepts as creative direction for your Shorts thumbnails and visual branding.",
    },
    {
      question: "What should a YouTube thumbnail contain?",
      answer:
        "A thumbnail can contain a clear subject, relevant visual elements, short readable text when necessary, and enough contrast to make the main idea easy to understand.",
    },
    {
      question: "Does a good thumbnail guarantee more views?",
      answer:
        "No. A thumbnail alone cannot guarantee more views. Performance also depends on the video's topic, title, audience, content quality, viewer satisfaction, and other factors.",
    },
    {
      question: "Is TubeKit's AI Thumbnail Generator free?",
      answer:
        "Yes. TubeKit provides this AI YouTube Thumbnail Generator as a free tool for creators.",
    },
  ];

  /* =========================================================
     BREADCRUMBS
     ========================================================= */

  const breadcrumbs = [
    {
      name: "Home",
      path: "/",
    },
    {
      name: "YouTube Thumbnail Generator",
      path: "/tools/thumbnail-generator",
    },
  ];

  return (
    <>
      {/* =====================================================
          SEO
          ===================================================== */}

      <SEO
        title="YouTube Thumbnail Generator – Free AI Thumbnail Ideas | TubeKit"
        description="Generate creative YouTube thumbnail ideas with TubeKit's free AI Thumbnail Generator. Get visual concepts, text ideas and composition suggestions for videos and Shorts."
        keywords="YouTube thumbnail generator, AI YouTube thumbnail generator, free thumbnail generator, YouTube thumbnail ideas, thumbnail idea generator, AI thumbnail ideas, YouTube thumbnail maker, video thumbnail generator, YouTube Shorts thumbnail ideas"
        canonical="/tools/thumbnail-generator"
        breadcrumbs={breadcrumbs}
        faqs={faqs}
      />

      <ToolLayout>

        {/* ===================================================
            TOOL HEADER
            =================================================== */}

        <ToolHeader
          title="AI YouTube Thumbnail Generator"
          description="Generate creative, clickable and relevant YouTube thumbnail concepts with AI in seconds."
        />

        {/* ===================================================
            TOOL FORM
            =================================================== */}

        <ToolForm
          onGenerate={handleGenerate}
          loading={loading}
          config={{
            buttonText: "Generate Thumbnail Ideas",
            topicLabel: "Video Topic",
            topicPlaceholder: "Example: Learn React in 30 Days",
            initialTopic: query,
            showTone: false,
            showCount: false,
          }}
        />

        {/* ===================================================
            OUTPUT
            =================================================== */}

        <ToolOutput
          results={results}
          loading={loading}
          onCopy={copyIdea}
          onCopyAll={copyAll}
          onRegenerate={() => {
            if (lastFormData) {
              handleGenerate(lastFormData);
            }
          }}
        />

        {/* ===================================================
            SEO CONTENT
            =================================================== */}

        <section className="mt-16 space-y-12">

          {/* =================================================
              INTRO
              ================================================= */}

          <div>
            <SectionHeading color="red">
              Free YouTube Thumbnail Generator
            </SectionHeading>

            <p className="mt-5 leading-8 text-slate-300">
              TubeKit's free YouTube Thumbnail Generator helps creators
              brainstorm attractive and relevant thumbnail concepts
              based on their video topic. Instead of starting your
              thumbnail design from a blank canvas, enter your topic
              and generate multiple visual ideas in seconds.
            </p>

            <p className="mt-4 leading-8 text-slate-300">
              A YouTube thumbnail gives viewers a quick visual
              impression of your video. A useful thumbnail should make
              the main subject easy to understand while accurately
              representing what viewers will find in the video.
            </p>

            <p className="mt-4 leading-8 text-slate-300">
              TubeKit focuses on generating creative direction rather
              than promising a guaranteed CTR or a guaranteed increase
              in views.
            </p>
          </div>

          {/* =================================================
              HOW TO USE
              ================================================= */}

          <div>
            <SectionHeading color="yellow">
              How to Use the YouTube Thumbnail Generator
            </SectionHeading>

            <p className="mt-5 leading-8 text-slate-300">
              Creating thumbnail concepts with TubeKit is simple:
            </p>

            <ol className="mt-5 list-decimal space-y-3 pl-6 leading-8 text-slate-300">
              <li>
                Enter the topic or main idea of your YouTube video.
              </li>

              <li>
                Click the{" "}
                <strong className="text-white">
                  Generate Thumbnail Ideas
                </strong>{" "}
                button.
              </li>

              <li>
                Review the generated thumbnail concepts.
              </li>

              <li>
                Select an idea that accurately represents your video.
              </li>

              <li>
                Adapt the concept to your channel's visual identity.
              </li>

              <li>
                Create the final thumbnail using your preferred design
                software.
              </li>
            </ol>
          </div>

          {/* =================================================
              WHAT IS
              ================================================= */}

          <div>
            <SectionHeading color="green">
              What Is a YouTube Thumbnail Generator?
            </SectionHeading>

            <p className="mt-5 leading-8 text-slate-300">
              A YouTube thumbnail generator is a tool that helps
              creators develop visual concepts for YouTube videos.
              Instead of manually brainstorming every design element,
              creators can provide a topic and receive ideas for
              composition, visuals, text, expressions, colors, and
              other creative elements.
            </p>

            <p className="mt-4 leading-8 text-slate-300">
              An AI thumbnail generator can make the brainstorming
              process faster by producing multiple concepts that can be
              reviewed and customized.
            </p>
          </div>

          {/* =================================================
              GOOD THUMBNAIL
              ================================================= */}

          <div>
            <SectionHeading color="blue">
              What Makes a Good YouTube Thumbnail?
            </SectionHeading>

            <p className="mt-5 leading-8 text-slate-300">
              There is no single design that works for every YouTube
              channel. However, an effective thumbnail should make the
              video's main idea easy to understand quickly.
            </p>

            <ul className="mt-5 list-disc space-y-3 pl-6 leading-8 text-slate-300">
              <li>
                Use a clear and recognizable main subject.
              </li>

              <li>
                Keep the visual hierarchy easy to understand.
              </li>

              <li>
                Use readable text when text adds useful context.
              </li>

              <li>
                Avoid unnecessary visual clutter.
              </li>

              <li>
                Use contrast to separate important elements.
              </li>

              <li>
                Make sure the thumbnail accurately represents the
                video.
              </li>

              <li>
                Maintain a recognizable visual style across your
                channel.
              </li>
            </ul>
          </div>

          {/* =================================================
              THUMBNAIL ELEMENTS
              ================================================= */}

          <div>
            <SectionHeading color="red">
              Important YouTube Thumbnail Elements
            </SectionHeading>

            <div className="mt-6 space-y-4">

              <div className="rounded-xl border border-red-500/20 bg-red-500/5 p-5">
                <h3 className="text-lg font-semibold text-red-400">
                  Main Subject
                </h3>

                <p className="mt-2 leading-7 text-slate-400">
                  Make the main person, object, product, or concept
                  recognizable immediately.
                </p>
              </div>

              <div className="rounded-xl border border-yellow-400/20 bg-yellow-400/5 p-5">
                <h3 className="text-lg font-semibold text-yellow-300">
                  Short Text
                </h3>

                <p className="mt-2 leading-7 text-slate-400">
                  If text is necessary, keep it short and readable.
                  Avoid filling the thumbnail with paragraphs.
                </p>
              </div>

              <div className="rounded-xl border border-green-500/20 bg-green-500/5 p-5">
                <h3 className="text-lg font-semibold text-green-400">
                  Visual Hierarchy
                </h3>

                <p className="mt-2 leading-7 text-slate-400">
                  The viewer should be able to identify the most
                  important visual element first.
                </p>
              </div>

              <div className="rounded-xl border border-blue-500/20 bg-blue-500/5 p-5">
                <h3 className="text-lg font-semibold text-blue-400">
                  Consistent Branding
                </h3>

                <p className="mt-2 leading-7 text-slate-400">
                  A consistent visual style can help viewers recognize
                  your content across your channel.
                </p>
              </div>

            </div>
          </div>

          {/* =================================================
              THUMBNAIL IDEAS
              ================================================= */}

          <div>
            <SectionHeading color="yellow">
              YouTube Thumbnail Ideas for Different Content
            </SectionHeading>

            <p className="mt-5 leading-8 text-slate-300">
              Different video categories may benefit from different
              visual approaches. Your thumbnail should match the topic
              and the expectations of the intended audience.
            </p>

            <div className="mt-6 grid gap-4 sm:grid-cols-2">

              <div className="rounded-xl border border-red-500/20 bg-red-500/5 p-5">
                <h3 className="font-semibold text-red-400">
                  Gaming
                </h3>

                <p className="mt-2 text-sm leading-6 text-slate-400">
                  Focus on recognizable game moments, characters,
                  reactions, challenges, or results.
                </p>
              </div>

              <div className="rounded-xl border border-yellow-400/20 bg-yellow-400/5 p-5">
                <h3 className="font-semibold text-yellow-300">
                  Technology
                </h3>

                <p className="mt-2 text-sm leading-6 text-slate-400">
                  Highlight the product, feature, comparison, or result
                  that the video focuses on.
                </p>
              </div>

              <div className="rounded-xl border border-green-500/20 bg-green-500/5 p-5">
                <h3 className="font-semibold text-green-400">
                  Education
                </h3>

                <p className="mt-2 text-sm leading-6 text-slate-400">
                  Clearly communicate the lesson, problem, skill, or
                  outcome viewers will learn.
                </p>
              </div>

              <div className="rounded-xl border border-blue-500/20 bg-blue-500/5 p-5">
                <h3 className="font-semibold text-blue-400">
                  Fitness
                </h3>

                <p className="mt-2 text-sm leading-6 text-slate-400">
                  Focus on the exercise, transformation, technique, or
                  specific result covered in the video.
                </p>
              </div>

            </div>
          </div>

          {/* =================================================
              FEATURES
              ================================================= */}

          <div>
            <SectionHeading color="green">
              TubeKit Thumbnail Generator Features
            </SectionHeading>

            <ul className="mt-6 grid gap-3 text-slate-300 sm:grid-cols-2">

              <li className="rounded-lg border border-red-500/20 bg-red-500/5 p-4">
                ✓ AI-generated thumbnail concepts
              </li>

              <li className="rounded-lg border border-yellow-400/20 bg-yellow-400/5 p-4">
                ✓ Topic-based thumbnail ideas
              </li>

              <li className="rounded-lg border border-green-500/20 bg-green-500/5 p-4">
                ✓ Visual composition suggestions
              </li>

              <li className="rounded-lg border border-blue-500/20 bg-blue-500/5 p-4">
                ✓ Text and design concepts
              </li>

              <li className="rounded-lg border border-red-500/20 bg-red-500/5 p-4">
                ✓ Multiple concept variations
              </li>

              <li className="rounded-lg border border-yellow-400/20 bg-yellow-400/5 p-4">
                ✓ Easy copy functionality
              </li>

              <li className="rounded-lg border border-green-500/20 bg-green-500/5 p-4">
                ✓ Regenerate ideas
              </li>

              <li className="rounded-lg border border-blue-500/20 bg-blue-500/5 p-4">
                ✓ Free to use
              </li>

            </ul>
          </div>

          {/* =================================================
              TIPS
              ================================================= */}

          <div>
            <SectionHeading color="blue">
              Tips for Better YouTube Thumbnails
            </SectionHeading>

            <ul className="mt-6 list-disc space-y-3 pl-6 leading-8 text-slate-300">
              <li>
                Make the main subject recognizable at a small size.
              </li>

              <li>
                Keep the design simple instead of overcrowding it.
              </li>

              <li>
                Use text only when it provides useful context.
              </li>

              <li>
                Make sure the thumbnail accurately represents the
                video's content.
              </li>

              <li>
                Use a consistent visual identity across your channel.
              </li>

              <li>
                Compare different concepts and learn from your
                audience's response.
              </li>
            </ul>
          </div>

          {/* =================================================
              TITLE + THUMBNAIL
              ================================================= */}

          <div>
            <SectionHeading color="red">
              YouTube Title and Thumbnail Should Work Together
            </SectionHeading>

            <p className="mt-5 leading-8 text-slate-300">
              Your YouTube title and thumbnail are often viewed
              together. They should complement each other rather than
              simply repeating the exact same information.
            </p>

            <p className="mt-4 leading-8 text-slate-300">
              For example, the title can explain the topic while the
              thumbnail provides a strong visual representation of the
              main idea. Both should accurately represent what the
              viewer will find in the video.
            </p>

            <div className="mt-6">
              <Link
                to="/tools/title-generator"
                className="inline-flex rounded-xl border border-red-500/30 bg-red-500/5 px-5 py-3 font-semibold text-red-400 transition hover:border-red-400 hover:bg-red-500/10"
              >
                Generate YouTube Titles →
              </Link>
            </div>
          </div>

          {/* =================================================
              RELATED TOOLS
              ================================================= */}

          <div>
            <SectionHeading color="yellow">
              More Free YouTube Creator Tools
            </SectionHeading>

            <p className="mt-5 leading-8 text-slate-300">
              Thumbnail design is only one part of creating YouTube
              content. Use TubeKit's other tools to plan titles,
              descriptions, keywords, tags, scripts, and Shorts.
            </p>

            <div className="mt-6 grid gap-4 sm:grid-cols-2">

              <Link
                to="/tools/title-generator"
                className="rounded-xl border border-red-500/20 bg-red-500/5 p-5 transition hover:border-red-400 hover:bg-red-500/10"
              >
                <span className="font-semibold text-red-400">
                  YouTube Title Generator →
                </span>

                <p className="mt-2 text-sm leading-6 text-slate-400">
                  Generate AI-powered title ideas for your videos.
                </p>
              </Link>

              <Link
                to="/tools/description-generator"
                className="rounded-xl border border-blue-500/20 bg-blue-500/5 p-5 transition hover:border-blue-400 hover:bg-blue-500/10"
              >
                <span className="font-semibold text-blue-400">
                  YouTube Description Generator →
                </span>

                <p className="mt-2 text-sm leading-6 text-slate-400">
                  Create useful YouTube description ideas.
                </p>
              </Link>

              <Link
                to="/tools/keyword-generator"
                className="rounded-xl border border-yellow-400/20 bg-yellow-400/5 p-5 transition hover:border-yellow-300 hover:bg-yellow-400/10"
              >
                <span className="font-semibold text-yellow-300">
                  YouTube Keyword Generator →
                </span>

                <p className="mt-2 text-sm leading-6 text-slate-400">
                  Generate keyword ideas for YouTube content planning.
                </p>
              </Link>

              <Link
                to="/tools/script-generator"
                className="rounded-xl border border-green-500/20 bg-green-500/5 p-5 transition hover:border-green-400 hover:bg-green-500/10"
              >
                <span className="font-semibold text-green-400">
                  YouTube Script Generator →
                </span>

                <p className="mt-2 text-sm leading-6 text-slate-400">
                  Create structured video script ideas with AI.
                </p>
              </Link>

              <Link
                to="/tools/shorts-generator"
                className="rounded-xl border border-red-500/20 bg-red-500/5 p-5 transition hover:border-red-400 hover:bg-red-500/10"
              >
                <span className="font-semibold text-red-400">
                  YouTube Shorts Generator →
                </span>

                <p className="mt-2 text-sm leading-6 text-slate-400">
                  Generate Shorts content ideas for your channel.
                </p>
              </Link>

              <Link
                to="/tools/hashtag-generator"
                className="rounded-xl border border-blue-500/20 bg-blue-500/5 p-5 transition hover:border-blue-400 hover:bg-blue-500/10"
              >
                <span className="font-semibold text-blue-400">
                  YouTube Hashtag Generator →
                </span>

                <p className="mt-2 text-sm leading-6 text-slate-400">
                  Generate relevant hashtag suggestions.
                </p>
              </Link>

            </div>
          </div>

          {/* =================================================
              BLOGS
              ================================================= */}

          <div>
            <SectionHeading color="green">
              Learn More About YouTube Thumbnails
            </SectionHeading>

            <p className="mt-5 leading-8 text-slate-300">
              Learn more about YouTube thumbnails, SEO, titles, and
              content optimization with TubeKit's creator guides.
            </p>

            <div className="mt-6 grid gap-4 sm:grid-cols-2">

              <Link
                to="/blog/how-to-create-better-youtube-thumbnails"
                className="rounded-xl border border-green-500/20 bg-green-500/5 p-5 transition hover:border-green-400 hover:bg-green-500/10"
              >
                <span className="font-semibold text-green-400">
                  How to Create Better YouTube Thumbnails →
                </span>

                <p className="mt-2 text-sm leading-6 text-slate-400">
                  Learn practical principles for creating clearer and
                  more useful YouTube thumbnails.
                </p>
              </Link>

              <Link
                to="/blog/how-to-write-youtube-titles-that-get-more-clicks"
                className="rounded-xl border border-red-500/20 bg-red-500/5 p-5 transition hover:border-red-400 hover:bg-red-500/10"
              >
                <span className="font-semibold text-red-400">
                  How to Write YouTube Titles That Get More Clicks →
                </span>

                <p className="mt-2 text-sm leading-6 text-slate-400">
                  Learn how titles and thumbnails can work together to
                  communicate your video's value.
                </p>
              </Link>

              <Link
                to="/blog/best-youtube-seo-tools-for-creators"
                className="rounded-xl border border-blue-500/20 bg-blue-500/5 p-5 transition hover:border-blue-400 hover:bg-blue-500/10"
              >
                <span className="font-semibold text-blue-400">
                  Best YouTube SEO Tools for Creators →
                </span>

                <p className="mt-2 text-sm leading-6 text-slate-400">
                  Explore useful tools for YouTube creators and content
                  optimization.
                </p>
              </Link>

            </div>
          </div>

          {/* =================================================
              FAQ
              ================================================= */}

          <div>
            <SectionHeading color="blue">
              Frequently Asked Questions
            </SectionHeading>

            <div className="mt-6 space-y-4">

              {faqs.map((faq, index) => {
                const colors = [
                  "border-red-500/20 bg-red-500/5",
                  "border-yellow-400/20 bg-yellow-400/5",
                  "border-green-500/20 bg-green-500/5",
                  "border-blue-500/20 bg-blue-500/5",
                ];

                return (
                  <div
                    key={faq.question}
                    className={`rounded-xl border p-5 ${colors[index % 4]}`}
                  >
                    <h3 className="text-lg font-semibold text-white">
                      {faq.question}
                    </h3>

                    <p className="mt-2 leading-7 text-slate-400">
                      {faq.answer}
                    </p>
                  </div>
                );
              })}

            </div>
          </div>

        </section>
      </ToolLayout>
    </>
  );
}

export default ThumbnailGenerator;