import { useEffect, useRef, useState } from "react";
import { Link } from "react-router-dom";

import api from "@/services/api";

import SEO from "@/components/common/SEO";
import ToolLayout from "@/components/tool-layout/ToolLayout";
import ToolHeader from "@/components/tool-layout/ToolHeader";
import ToolForm from "@/components/tool-layout/ToolForm";
import ToolOutput from "@/components/tool-layout/ToolOutput";

/* =========================================================
   RGYB SEO SECTION HEADING
   ========================================================= */

function SectionHeading({ children, color = "blue" }) {
  const colors = {
    red: "border-red-500 bg-red-500/5 text-red-400",
    yellow: "border-yellow-400 bg-yellow-400/5 text-yellow-300",
    green: "border-green-500 bg-green-500/5 text-green-400",
    blue: "border-blue-500 bg-blue-500/5 text-blue-400",
  };

  return (
    <h2
      className={`border-l-4 rounded-r-xl px-5 py-3 text-2xl font-bold tracking-tight sm:text-3xl ${colors[color]}`}
    >
      {children}
    </h2>
  );
}

/* =========================================================
   TITLE GENERATOR
   ========================================================= */

function TitleGenerator({ query = "" }) {
  const [loading, setLoading] = useState(false);
  const [results, setResults] = useState([]);
  const [lastFormData, setLastFormData] = useState(null);

  // Prevent duplicate Hero auto-generation
  const autoGeneratedQuery = useRef("");

  /* =========================================================
     GENERATE
     ========================================================= */

  const handleGenerate = async (formData) => {
    try {
      setLoading(true);
      setLastFormData(formData);

      const response = await api.post("/generate", {
        tool: "title-generator",
        ...formData,
      });

      if (response.data.success) {
        const titles = response.data.data
          .split("\n")
          .map((item) => item.trim())
          .filter(Boolean);

        setResults(titles);
      } else {
        setResults([]);
      }
    } catch (error) {
      console.error("TITLE GENERATOR ERROR:", error);
      console.error("RESPONSE:", error.response);
      console.error("REQUEST:", error.request);

      alert(
        error.response?.data?.message ||
          error.message ||
          "Failed to generate titles"
      );

      setResults([]);
    } finally {
      setLoading(false);
    }
  };

  /* =========================================================
     HERO SEARCH → AUTO GENERATE
     ========================================================= */

  useEffect(() => {
    const value = query.trim();

    if (!value) return;

    if (autoGeneratedQuery.current === value) return;

    autoGeneratedQuery.current = value;

    handleGenerate({
      topic: value,
      language: "English",
      tone: "Professional",
      count: 10,
    });
  }, [query]);

  /* =========================================================
     COPY
     ========================================================= */

  const copyTitle = async (text) => {
    try {
      await navigator.clipboard.writeText(text);
      alert("Copied!");
    } catch (error) {
      console.error("COPY ERROR:", error);
    }
  };

  const copyAll = async () => {
    try {
      await navigator.clipboard.writeText(results.join("\n"));
      alert("All titles copied!");
    } catch (error) {
      console.error("COPY ALL ERROR:", error);
    }
  };

  /* =========================================================
     FAQ
     ========================================================= */

  const faqs = [
    {
      question: "What is a YouTube title generator?",
      answer:
        "A YouTube title generator creates title ideas based on your video topic. TubeKit uses AI to generate multiple title variations that you can review, edit, and choose from before publishing your video.",
    },
    {
      question: "How can I create a good YouTube title?",
      answer:
        "Start with a clear description of your video's topic and audience. A good YouTube title should communicate the video's value, create appropriate curiosity, and accurately represent the content without misleading viewers.",
    },
    {
      question: "Is this YouTube title generator free?",
      answer:
        "Yes. TubeKit provides this AI YouTube Title Generator as a free tool for creators.",
    },
    {
      question: "Can AI generate YouTube titles?",
      answer:
        "Yes. AI can generate multiple YouTube title ideas from a topic or description. You should review the suggestions and make sure the final title accurately represents your video.",
    },
    {
      question: "Can I generate YouTube Shorts titles?",
      answer:
        "Yes. TubeKit's YouTube Title Generator can be used to create title ideas for both long-form YouTube videos and YouTube Shorts.",
    },
    {
      question: "Are AI-generated YouTube titles good for SEO?",
      answer:
        "AI-generated titles can help you explore relevant wording and title ideas, but SEO performance depends on search intent, relevance, competition, content quality, and how well the title matches the actual video.",
    },
    {
      question: "How long should a YouTube title be?",
      answer:
        "There is no single perfect title length for every video. Keep the important information clear and avoid unnecessary words. Make sure the main idea is understandable before the title is truncated in search or other surfaces.",
    },
    {
      question: "Can I edit the generated YouTube titles?",
      answer:
        "Yes. Generated suggestions are ideas rather than final publishing instructions. You can edit them to better match your video's content, audience, and style.",
    },
  ];

  /* =========================================================
     BREADCRUMBS
     ========================================================= */

  const breadcrumbs = [
    {
      name: "Home",
      path: "/",
    },
    {
      name: "YouTube Title Generator",
      path: "/tools/title-generator",
    },
  ];

  return (
    <>
      {/* =====================================================
          SEO
          ===================================================== */}

      <SEO
        title="YouTube Title Generator – Free AI Title Generator | TubeKit"
        description="Create catchy and SEO-friendly YouTube titles with TubeKit's free AI YouTube Title Generator. Generate title ideas for YouTube videos and Shorts in seconds."
        keywords="YouTube title generator, AI YouTube title generator, free YouTube title generator, YouTube video title generator, YouTube title maker, YouTube SEO title generator, YouTube title ideas, catchy YouTube titles, YouTube Shorts title generator"
        canonical="/tools/title-generator"
        breadcrumbs={breadcrumbs}
        faqs={faqs}
      />

      <ToolLayout>
        {/* ===================================================
            TOOL HEADER
            =================================================== */}

        <ToolHeader
          title="AI YouTube Title Generator"
          description="Create catchy, relevant and SEO-friendly YouTube title ideas with TubeKit's free AI title generator."
        />

        {/* ===================================================
            TOOL FORM
            =================================================== */}

        <ToolForm
          onGenerate={handleGenerate}
          loading={loading}
          config={{
            buttonText: "Generate Titles",
            topicLabel: "Video Topic",
            topicPlaceholder: "Example: How to Grow on YouTube",
            initialTopic: query,
          }}
        />

        {/* ===================================================
            OUTPUT
            =================================================== */}

        <ToolOutput
          results={results}
          loading={loading}
          onCopy={copyTitle}
          onCopyAll={copyAll}
          onRegenerate={() => {
            if (lastFormData) {
              handleGenerate(lastFormData);
            }
          }}
        />

        {/* ===================================================
            SEO CONTENT
            =================================================== */}

        <section className="mt-16 space-y-12">

          {/* =================================================
              1. INTRODUCTION
              ================================================= */}

          <div>
            <SectionHeading color="red">
              Free YouTube Title Generator
            </SectionHeading>

            <p className="mt-5 leading-8 text-slate-300">
              TubeKit's free YouTube Title Generator helps creators
              generate engaging title ideas from a video topic. Instead
              of starting with a blank page, enter what your video is
              about and get multiple YouTube title suggestions that you
              can review, customize, and use as inspiration.
            </p>

            <p className="mt-4 leading-8 text-slate-300">
              A strong YouTube title should clearly communicate the
              video's topic while giving viewers a reason to click.
              The best title depends on your audience, search intent,
              video content, competition, and overall presentation.
            </p>

            <p className="mt-4 leading-8 text-slate-300">
              TubeKit makes the brainstorming process faster by giving
              you multiple AI-generated YouTube title ideas in seconds.
            </p>
          </div>

          {/* =================================================
              2. HOW TO USE
              ================================================= */}

          <div>
            <SectionHeading color="yellow">
              How to Use the YouTube Title Generator
            </SectionHeading>

            <p className="mt-5 leading-8 text-slate-300">
              Creating YouTube title ideas with TubeKit takes only a few
              simple steps:
            </p>

            <ol className="mt-5 list-decimal space-y-3 pl-6 leading-8 text-slate-300">
              <li>
                Enter the main topic or idea of your YouTube video.
              </li>

              <li>
                Select your preferred language, tone, and number of
                results.
              </li>

              <li>
                Click the <strong className="text-white">
                  Generate Titles
                </strong>{" "}
                button.
              </li>

              <li>
                Review the generated YouTube title suggestions.
              </li>

              <li>
                Edit the title if necessary so it accurately represents
                your video.
              </li>

              <li>
                Copy your preferred title and use it when publishing
                your video.
              </li>
            </ol>
          </div>

          {/* =================================================
              3. WHAT IS
              ================================================= */}

          <div>
            <SectionHeading color="green">
              What Is a YouTube Title Generator?
            </SectionHeading>

            <p className="mt-5 leading-8 text-slate-300">
              A YouTube title generator is an online tool that creates
              title ideas based on information about a video. It helps
              creators explore different ways to describe the same
              topic and find wording that is clear, relevant, and
              suitable for their target audience.
            </p>

            <p className="mt-4 leading-8 text-slate-300">
              An AI YouTube title generator can produce multiple
              variations quickly, making it useful during the video
              planning, SEO research, and publishing process.
            </p>

            <p className="mt-4 leading-8 text-slate-300">
              Instead of relying on one title idea, creators can compare
              several options and choose the one that best represents
              their content.
            </p>
          </div>

          {/* =================================================
              4. AI
              ================================================= */}

          <div>
            <SectionHeading color="blue">
              How Does an AI YouTube Title Generator Work?
            </SectionHeading>

            <p className="mt-5 leading-8 text-slate-300">
              TubeKit takes the topic and options you provide and sends
              them to its AI generation system. The AI then creates
              multiple title ideas based on the supplied information.
            </p>

            <p className="mt-4 leading-8 text-slate-300">
              The generated titles should be treated as suggestions,
              not guaranteed ranking formulas. Always review the final
              title and make sure it accurately describes what viewers
              will find in your video.
            </p>
          </div>

          {/* =================================================
              5. GOOD TITLE
              ================================================= */}

          <div>
            <SectionHeading color="red">
              What Makes a Good YouTube Title?
            </SectionHeading>

            <p className="mt-5 leading-8 text-slate-300">
              A good YouTube title makes the subject of the video clear
              while giving viewers enough information to understand why
              the video may be useful or interesting.
            </p>

            <ul className="mt-5 list-disc space-y-3 pl-6 leading-8 text-slate-300">
              <li>
                Clearly communicate the video's main topic.
              </li>

              <li>
                Use specific and understandable wording.
              </li>

              <li>
                Match the title with the actual video content.
              </li>

              <li>
                Consider the search intent of your target audience.
              </li>

              <li>
                Create curiosity without making misleading claims.
              </li>

              <li>
                Avoid unnecessary words and repetitive phrasing.
              </li>
            </ul>
          </div>

          {/* =================================================
              6. TITLE EXAMPLES
              ================================================= */}

          <div>
            <SectionHeading color="yellow">
              YouTube Title Examples
            </SectionHeading>

            <p className="mt-5 leading-8 text-slate-300">
              Different topics require different title approaches.
              Here are examples of how a basic topic can be turned into
              a more specific YouTube title.
            </p>

            <div className="mt-6 space-y-4">

              <div className="rounded-xl border border-red-500/20 bg-red-500/5 p-5">
                <p className="font-semibold text-red-400">
                  Topic: YouTube Growth
                </p>

                <p className="mt-2 text-slate-300">
                  How to Grow a YouTube Channel: 7 Practical Strategies
                </p>
              </div>

              <div className="rounded-xl border border-yellow-400/20 bg-yellow-400/5 p-5">
                <p className="font-semibold text-yellow-300">
                  Topic: YouTube SEO
                </p>

                <p className="mt-2 text-slate-300">
                  YouTube SEO for Beginners: How to Optimize Your Videos
                </p>
              </div>

              <div className="rounded-xl border border-green-500/20 bg-green-500/5 p-5">
                <p className="font-semibold text-green-400">
                  Topic: YouTube Shorts
                </p>

                <p className="mt-2 text-slate-300">
                  10 YouTube Shorts Ideas for Beginners
                </p>
              </div>

            </div>
          </div>

          {/* =================================================
              7. SHORTS
              ================================================= */}

          <div>
            <SectionHeading color="green">
              YouTube Shorts Title Ideas
            </SectionHeading>

            <p className="mt-5 leading-8 text-slate-300">
              You can also use the generator to create title ideas for
              YouTube Shorts. Shorts titles should quickly communicate
              the subject of the video and match the content viewers
              are about to watch.
            </p>

            <p className="mt-4 leading-8 text-slate-300">
              Try entering a specific Shorts topic rather than a very
              broad phrase. This gives the AI more useful information
              when generating title suggestions.
            </p>

            <div className="mt-6">
              <Link
                to="/tools/shorts-generator"
                className="inline-flex rounded-xl border border-green-500/30 bg-green-500/5 px-5 py-3 font-semibold text-green-400 transition hover:border-green-400 hover:bg-green-500/10"
              >
                Create YouTube Shorts Ideas →
              </Link>
            </div>
          </div>

          {/* =================================================
              8. SEO TIPS
              ================================================= */}

          <div>
            <SectionHeading color="blue">
              YouTube Title SEO Tips
            </SectionHeading>

            <p className="mt-5 leading-8 text-slate-300">
              A YouTube title can support discoverability when it
              accurately matches what viewers are searching for and
              what the video actually provides.
            </p>

            <ul className="mt-5 list-disc space-y-3 pl-6 leading-8 text-slate-300">
              <li>
                Use words that accurately describe the video's subject.
              </li>

              <li>
                Think about what your target audience would search for.
              </li>

              <li>
                Put important information where it is easy to
                understand.
              </li>

              <li>
                Avoid misleading clickbait that does not match the
                video.
              </li>

              <li>
                Make the title specific rather than unnecessarily
                broad.
              </li>

              <li>
                Compare different title ideas before choosing the
                final version.
              </li>
            </ul>
          </div>

          {/* =================================================
              9. FEATURES
              ================================================= */}

          <div>
            <SectionHeading color="red">
              TubeKit YouTube Title Generator Features
            </SectionHeading>

            <ul className="mt-6 grid gap-3 text-slate-300 sm:grid-cols-2">

              <li className="rounded-lg border border-red-500/20 bg-red-500/5 p-3">
                ✓ AI-generated YouTube title ideas
              </li>

              <li className="rounded-lg border border-yellow-400/20 bg-yellow-400/5 p-3">
                ✓ Multiple title variations
              </li>

              <li className="rounded-lg border border-green-500/20 bg-green-500/5 p-3">
                ✓ SEO-focused suggestions
              </li>

              <li className="rounded-lg border border-blue-500/20 bg-blue-500/5 p-3">
                ✓ Different writing tones
              </li>

              <li className="rounded-lg border border-red-500/20 bg-red-500/5 p-3">
                ✓ Multiple language options
              </li>

              <li className="rounded-lg border border-yellow-400/20 bg-yellow-400/5 p-3">
                ✓ Adjustable number of results
              </li>

              <li className="rounded-lg border border-green-500/20 bg-green-500/5 p-3">
                ✓ One-click title copying
              </li>

              <li className="rounded-lg border border-blue-500/20 bg-blue-500/5 p-3">
                ✓ Regenerate title suggestions
              </li>

              <li className="rounded-lg border border-red-500/20 bg-red-500/5 p-3">
                ✓ Works for YouTube videos
              </li>

              <li className="rounded-lg border border-yellow-400/20 bg-yellow-400/5 p-3">
                ✓ Works for YouTube Shorts
              </li>

              <li className="rounded-lg border border-green-500/20 bg-green-500/5 p-3">
                ✓ Free to use
              </li>

            </ul>
          </div>

          {/* =================================================
              10. RELATED TOOLS
              ================================================= */}

          <div>
            <SectionHeading color="yellow">
              More Free YouTube Tools
            </SectionHeading>

            <p className="mt-5 leading-8 text-slate-300">
              Creating a strong title is only one part of YouTube
              content optimization. Use TubeKit's other free tools to
              prepare your description, tags, hashtags, keywords, and
              video script.
            </p>

            <div className="mt-6 grid gap-4 sm:grid-cols-2">

              <Link
                to="/tools/description-generator"
                className="group rounded-xl border border-blue-500/20 bg-blue-500/5 p-5 transition hover:border-blue-400 hover:bg-blue-500/10"
              >
                <span className="font-semibold text-blue-400">
                  YouTube Description Generator →
                </span>

                <p className="mt-2 text-sm leading-6 text-slate-400">
                  Generate useful YouTube description ideas for your
                  videos.
                </p>
              </Link>

              <Link
                to="/tools/tags-generator"
                className="group rounded-xl border border-green-500/20 bg-green-500/5 p-5 transition hover:border-green-400 hover:bg-green-500/10"
              >
                <span className="font-semibold text-green-400">
                  YouTube Tags Generator →
                </span>

                <p className="mt-2 text-sm leading-6 text-slate-400">
                  Generate relevant YouTube tag ideas for your content.
                </p>
              </Link>

              <Link
                to="/tools/keyword-generator"
                className="group rounded-xl border border-yellow-400/20 bg-yellow-400/5 p-5 transition hover:border-yellow-300 hover:bg-yellow-400/10"
              >
                <span className="font-semibold text-yellow-300">
                  YouTube Keyword Generator →
                </span>

                <p className="mt-2 text-sm leading-6 text-slate-400">
                  Find keyword ideas to support your YouTube content
                  planning.
                </p>
              </Link>

              <Link
                to="/tools/thumbnail-generator"
                className="group rounded-xl border border-red-500/20 bg-red-500/5 p-5 transition hover:border-red-400 hover:bg-red-500/10"
              >
                <span className="font-semibold text-red-400">
                  YouTube Thumbnail Generator →
                </span>

                <p className="mt-2 text-sm leading-6 text-slate-400">
                  Generate creative thumbnail concepts for your videos.
                </p>
              </Link>

              <Link
                to="/tools/script-generator"
                className="group rounded-xl border border-blue-500/20 bg-blue-500/5 p-5 transition hover:border-blue-400 hover:bg-blue-500/10"
              >
                <span className="font-semibold text-blue-400">
                  YouTube Script Generator →
                </span>

                <p className="mt-2 text-sm leading-6 text-slate-400">
                  Create structured YouTube video script ideas.
                </p>
              </Link>

              <Link
                to="/tools/hashtag-generator"
                className="group rounded-xl border border-green-500/20 bg-green-500/5 p-5 transition hover:border-green-400 hover:bg-green-500/10"
              >
                <span className="font-semibold text-green-400">
                  YouTube Hashtag Generator →
                </span>

                <p className="mt-2 text-sm leading-6 text-slate-400">
                  Generate relevant hashtag suggestions for YouTube
                  content.
                </p>
              </Link>

            </div>
          </div>

          {/* =================================================
              11. RELATED BLOGS
              ================================================= */}

          <div>
            <SectionHeading color="green">
              Learn More About YouTube Titles & SEO
            </SectionHeading>

            <p className="mt-5 leading-8 text-slate-300">
              Want to improve your YouTube titles further? Read these
              TubeKit guides for practical YouTube SEO and content
              optimization tips.
            </p>

            <div className="mt-6 grid gap-4 sm:grid-cols-2">

              <Link
                to="/blog/how-to-write-youtube-titles-that-get-more-clicks"
                className="rounded-xl border border-green-500/20 bg-green-500/5 p-5 transition hover:border-green-400 hover:bg-green-500/10"
              >
                <span className="font-semibold text-green-400">
                  How to Write YouTube Titles That Get More Clicks →
                </span>

                <p className="mt-2 text-sm leading-6 text-slate-400">
                  Learn practical techniques for creating clearer and
                  more compelling YouTube titles.
                </p>
              </Link>

              <Link
                to="/blog/best-youtube-seo-tools-for-creators"
                className="rounded-xl border border-blue-500/20 bg-blue-500/5 p-5 transition hover:border-blue-400 hover:bg-blue-500/10"
              >
                <span className="font-semibold text-blue-400">
                  Best YouTube SEO Tools for Creators →
                </span>

                <p className="mt-2 text-sm leading-6 text-slate-400">
                  Explore useful tools for YouTube titles, keywords,
                  descriptions, tags, and content planning.
                </p>
              </Link>

            </div>
          </div>

          {/* =================================================
              12. FAQ
              ================================================= */}

          <div>
            <SectionHeading color="blue">
              Frequently Asked Questions
            </SectionHeading>

            <div className="mt-6 space-y-4">

              {faqs.map((faq, index) => {
                const colors = [
                  "border-red-500/20 bg-red-500/5",
                  "border-yellow-400/20 bg-yellow-400/5",
                  "border-green-500/20 bg-green-500/5",
                  "border-blue-500/20 bg-blue-500/5",
                ];

                return (
                  <div
                    key={faq.question}
                    className={`rounded-xl border p-5 ${colors[index % 4]}`}
                  >
                    <h3 className="text-lg font-semibold text-white">
                      {faq.question}
                    </h3>

                    <p className="mt-2 leading-7 text-slate-400">
                      {faq.answer}
                    </p>
                  </div>
                );
              })}

            </div>
          </div>

        </section>
      </ToolLayout>
    </>
  );
}

export default TitleGenerator;