function Disclaimer() {
  const lastUpdated = "August 2026";

  return (
    <main className="min-h-screen bg-slate-950 text-white">
      <div className="mx-auto max-w-5xl px-6 py-16">

        <span className="rounded-full border border-blue-500/30 bg-blue-500/10 px-4 py-2 text-sm text-blue-400">
          Legal
        </span>

        <h1 className="mt-6 text-4xl font-black sm:text-5xl">
          Disclaimer
        </h1>

        <p className="mt-3 text-slate-400">
          Last Updated: {lastUpdated}
        </p>

        <p className="mt-8 text-lg leading-8 text-slate-300">
          The information and tools provided on TubeKit are intended
          for general informational and educational purposes only.
        </p>

        <Section
          title="1. General Information"
          content={[
            "TubeKit provides AI-powered and utility tools for YouTube creators.",
            "The information available on this website is provided in good faith but without guarantees of completeness or accuracy."
          ]}
        />

        <Section
          title="2. AI Generated Content"
          content={[
            "Content generated by AI should always be reviewed before publishing.",
            "TubeKit does not guarantee the originality, legality, or factual accuracy of AI-generated content."
          ]}
        />

        <Section
          title="3. No Professional Advice"
          content={[
            "TubeKit does not provide legal, financial, tax, business, or professional advice.",
            "Always consult qualified professionals when making important decisions."
          ]}
        />

        <Section
          title="4. YouTube Platform"
          content={[
            "TubeKit is an independent platform and is not affiliated with, endorsed by, or sponsored by YouTube or Google unless explicitly stated."
          ]}
        />

        <Section
          title="5. Third-Party APIs"
          content={[
            "Some features rely on third-party APIs such as Google Gemini and the YouTube Data API.",
            "Availability and accuracy of those services are outside our control."
          ]}
        />

        <Section
          title="6. External Links"
          content={[
            "TubeKit may contain links to third-party websites.",
            "We are not responsible for the content, privacy practices, or services offered by external websites."
          ]}
        />

        <Section
          title="7. Limitation of Liability"
          content={[
            "TubeKit shall not be held responsible for any direct, indirect, incidental, or consequential damages arising from the use of this website or its tools."
          ]}
        />

        <Section
          title="8. Changes"
          content={[
            "This Disclaimer may be updated from time to time without prior notice.",
            "The latest version will always be available on this page."
          ]}
        />

      </div>
    </main>
  );
}

function Section({ title, content }) {
  return (
    <section className="mt-12">

      <h2 className="text-2xl font-bold">
        {title}
      </h2>

      <ul className="mt-5 list-disc space-y-3 pl-6 text-slate-300">

        {content.map((item) => (
          <li key={item}>
            {item}
          </li>
        ))}

      </ul>

    </section>
  );
}

export default Disclaimer;